"use client";

import { ChevronLeft, ChevronRight, Database, Filter, ShieldCheck } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { useSmartCareAuth } from "../components/auth-provider";

type AuditLog = { id:number;occurredAt:string;actorUserId:string|null;actorName:string;actionType:string;tableName:string|null;recordId:string|null;pagePath:string|null;oldData:unknown;newData:unknown;metadata:unknown };
type UserOption = { id:string;name:string };

export default function AuditLogsPage() {
  const { user } = useSmartCareAuth();
  const [logs,setLogs]=useState<AuditLog[]>([]),[users,setUsers]=useState<UserOption[]>([]),[actions,setActions]=useState<string[]>([]);
  const [userId,setUserId]=useState(""),[action,setAction]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[page,setPage]=useState(1),[total,setTotal]=useState(0),[totalPages,setTotalPages]=useState(1),[error,setError]=useState(""),[loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);setError("");const params=new URLSearchParams({page:String(page)});if(userId)params.set("userId",userId);if(action)params.set("action",action);if(from)params.set("from",from);if(to)params.set("to",to);const response=await fetch(`/api/audit-logs?${params}`,{cache:"no-store"});const data=await response.json() as {logs?:AuditLog[];users?:UserOption[];actions?:string[];pagination?:{page:number;pageSize:number;total:number;totalPages:number};error?:string};setLoading(false);if(!response.ok){setError(data.error||"Unable to load audit logs");return}setLogs(data.logs||[]);setUsers(data.users||[]);setActions(data.actions||[]);setTotal(data.pagination?.total||0);setTotalPages(data.pagination?.totalPages||1)},[userId,action,from,to,page]);
  useEffect(()=>{if(user?.role==="ADMIN")void load()},[user?.role,load]);
  if (!user) return null;
  if (user.role !== "ADMIN") return <main className="dashboard-main section-page"><section className="empty-state"><ShieldCheck size={36}/><h1>Admin access required</h1><p>The audit trail is restricted to ADMIN users.</p></section></main>;
  return <main className="dashboard-main section-page"><section className="page-heading"><div><p className="eyebrow">Security and accountability</p><h1>Audit Log</h1><p className="page-subtitle">Review sign-ins, page navigation, and database row creation, changes, and deletion.</p></div></section>
    <section className="toolbar-card audit-filters"><label className="filter-select"><Filter size={15}/><select value={userId} onChange={event=>{setUserId(event.target.value);setPage(1)}}><option value="">All users</option>{users.map(option=><option key={option.id} value={option.id}>{option.name}</option>)}</select></label><label>From<input type="date" value={from} onChange={event=>{setFrom(event.target.value);setPage(1)}}/></label><label>To<input type="date" value={to} min={from||undefined} onChange={event=>{setTo(event.target.value);setPage(1)}}/></label><label className="filter-select"><Database size={15}/><select value={action} onChange={event=>{setAction(event.target.value);setPage(1)}}><option value="">All actions</option>{actions.map(value=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select></label><button className="button secondary" onClick={()=>{setUserId("");setAction("");setFrom("");setTo("");setPage(1)}}>Clear filters</button><span className="result-count">{total} events</span></section>
    {error&&<p className="form-error">{error}</p>}
    <section className="budget-table-card"><div className="responsive-table"><table className="audit-table"><thead><tr><th>Date and time</th><th>User</th><th>Action</th><th>Target</th><th>Record / Page</th><th>Details</th></tr></thead><tbody>{logs.map(log=><tr key={log.id}><td><time>{new Date(log.occurredAt).toLocaleString()}</time></td><td><strong>{log.actorName}</strong><small>{log.actorUserId||"Automated server action"}</small></td><td><span className={`audit-action ${log.actionType.toLowerCase()}`}>{log.actionType.replaceAll("_"," ")}</span></td><td>{log.tableName||"Application"}</td><td>{log.pagePath||log.recordId||"—"}</td><td>{Boolean(log.oldData||log.newData||log.metadata)&&<details><summary>View data</summary><pre>{JSON.stringify({old:log.oldData,new:log.newData,metadata:log.metadata},null,2)}</pre></details>}</td></tr>)}{!loading&&!logs.length&&<tr><td colSpan={6} className="empty-row">No audit events match these filters.</td></tr>}{loading&&<tr><td colSpan={6} className="empty-row">Loading audit trail…</td></tr>}</tbody></table></div><footer className="audit-pagination"><span>{total?`Showing ${(page-1)*15+1}–${Math.min(page*15,total)} of ${total}`:"No events"}</span><div><button className="button secondary" disabled={page<=1||loading} onClick={()=>setPage(value=>Math.max(1,value-1))}><ChevronLeft size={16}/> Previous</button><strong>Page {page} of {totalPages}</strong><button className="button secondary" disabled={page>=totalPages||loading} onClick={()=>setPage(value=>Math.min(totalPages,value+1))}>Next <ChevronRight size={16}/></button></div></footer></section>
  </main>;
}
