"use client";

import { ArchiveRestore, ArrowLeft, FileText, Printer, RotateCcw, ShieldCheck, X } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useSmartCareAuth } from "../../components/auth-provider";

type ArchivedAsset={id:string;name:string;project:string;category:string;serialNumber:string;purchaseDate:string;acquisitionCost:number;deletedAt:string;deletedBy:string};
type Bundle={asset:ArchivedAsset;purchaseOrder?:{id:string;po_date:string;supplier:string;total:number;status:string;received_at?:string}|null;tasks?:Array<{id:string;title:string;next_due:string;status:string}>;orders?:Array<{id:string;title:string;status:string;createdAt:string;completedAt?:string;resolution?:string}>;events?:Array<{id:string;title:string;type:string;performed_at:string;notes:string}>;diagnostics?:Array<{id:number;observed_symptom:string;created_at:string}>};

export default function ArchivedAssetsPage(){
  const{user}=useSmartCareAuth();
  const[assets,setAssets]=useState<ArchivedAsset[]>([]),[selected,setSelected]=useState<Bundle|null>(null),[restoreOpen,setRestoreOpen]=useState(false),[confirmation,setConfirmation]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const isAdmin=user?.role==="ADMIN";
  async function refresh(){const response=await fetch("/api/assets/archived",{cache:"no-store"}),data=await response.json();if(!response.ok)throw new Error(data.error||"Unable to load archive");setAssets(data.assets||[]);}
  useEffect(()=>{if(isAdmin)refresh().catch(reason=>setError(reason.message));},[isAdmin]);
  async function open(asset:ArchivedAsset){setError("");const response=await fetch(`/api/assets/archived?id=${encodeURIComponent(asset.id)}`,{cache:"no-store"}),data=await response.json();if(!response.ok){setError(data.error||"Unable to open lifecycle report");return;}setSelected(data);}
  async function restore(){if(!selected)return;setBusy(true);setError("");try{const response=await fetch("/api/assets/archived",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:selected.asset.id,confirmation})}),data=await response.json();if(!response.ok)throw new Error(data.error||"Unable to restore asset");setRestoreOpen(false);setSelected(null);setConfirmation("");await refresh();}catch(reason){setError(reason instanceof Error?reason.message:"Unable to restore asset");}finally{setBusy(false);}}
  if(!isAdmin)return <main className="dashboard-main section-page"><section className="empty-state"><ShieldCheck size={34}/><h1>Admin access required</h1><p>Archived assets and restoration controls are restricted to ADMIN users.</p></section></main>;
  return <main className="dashboard-main section-page archived-assets-page"><Link className="back-link no-print" href="/assets"><ArrowLeft size={16}/> Back to assets</Link><section className="page-heading no-print"><div><p className="eyebrow">Admin asset archive</p><h1>Archived Assets & Lifecycle Reports</h1><p className="page-subtitle">Review purchasing, receiving, maintenance and end-of-life history, then restore an asset when required.</p></div><span className="pilot-badge"><ShieldCheck size={16}/> Admin only</span></section>{error&&<p className="form-error">{error}</p>}
  <section className="archive-layout"><aside className="archive-list no-print"><header><ArchiveRestore size={19}/><div><h2>Archived assets</h2><small>{assets.length} record(s)</small></div></header>{assets.map(asset=><button key={asset.id} className={selected?.asset.id===asset.id?"active":""} onClick={()=>open(asset)}><span><strong>{asset.name}</strong><small>{asset.id} · {asset.project}</small></span><time>{new Date(asset.deletedAt).toLocaleDateString()}</time></button>)}{!assets.length&&<p>No archived assets.</p>}</aside>
  <article className="archive-report">{selected?<><header className="archive-report-header"><div><p className="eyebrow">Complete asset lifecycle</p><h1>{selected.asset.name}</h1><span>{selected.asset.id} · {selected.asset.category} · {selected.asset.serialNumber}</span></div><div className="no-print"><button className="button secondary" onClick={()=>window.print()}><Printer size={17}/> Print report</button><button className="button primary" onClick={()=>{setConfirmation("");setRestoreOpen(true)}}><RotateCcw size={17}/> Restore asset</button></div></header><section className="archive-report-summary"><div><small>Project</small><strong>{selected.asset.project}</strong></div><div><small>Purchased</small><strong>{selected.asset.purchaseDate||"Not recorded"}</strong></div><div><small>Purchase value</small><strong>QAR {Number(selected.asset.acquisitionCost||0).toLocaleString()}</strong></div><div><small>Archived</small><strong>{new Date(selected.asset.deletedAt).toLocaleString()}</strong></div></section><section className="archive-report-section"><h2>Purchasing & receiving</h2>{selected.purchaseOrder?<dl><div><dt>Purchase order</dt><dd>{selected.purchaseOrder.id}</dd></div><div><dt>Supplier</dt><dd>{selected.purchaseOrder.supplier}</dd></div><div><dt>Value</dt><dd>QAR {Number(selected.purchaseOrder.total||0).toLocaleString()}</dd></div><div><dt>Received</dt><dd>{selected.purchaseOrder.received_at||"Not recorded"}</dd></div></dl>:<p>No linked purchase order.</p>}</section><section className="archive-report-section"><h2>Maintenance lifecycle</h2><div className="lifecycle-report-list">{(selected.orders||[]).map(order=><article key={order.id}><FileText size={16}/><div><strong>{order.id} · {order.title}</strong><small>{order.status} · {order.createdAt}{order.completedAt?` · completed ${order.completedAt}`:""}</small>{order.resolution&&<p>{order.resolution}</p>}</div></article>)}{(selected.events||[]).map(event=><article key={event.id}><FileText size={16}/><div><strong>{event.type} · {event.title}</strong><small>{event.performed_at}</small>{event.notes&&<p>{event.notes}</p>}</div></article>)}{!(selected.orders||[]).length&&!(selected.events||[]).length&&<p>No maintenance history.</p>}</div></section><footer>Archived by {selected.asset.deletedBy||"System"} · Records retained for audit and lifecycle reporting.</footer></>:<div className="archive-report-empty"><FileText size={38}/><h2>Select an archived asset</h2><p>Its complete purchasing-to-end-of-life report will appear here.</p></div>}</article></section>
  {restoreOpen&&selected&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setRestoreOpen(false)} aria-label="Cancel"/><section className="modal-card archive-asset-modal"><button className="modal-close" onClick={()=>setRestoreOpen(false)}><X size={20}/></button><span className="modal-icon"><RotateCcw size={22}/></span><p className="eyebrow">Admin restoration</p><h2>Restore {selected.asset.name}?</h2><p>The asset will return to active lists with all retained history.</p><label>Type <strong>{selected.asset.id}</strong> to confirm<input value={confirmation} onChange={event=>setConfirmation(event.target.value)}/></label><div className="archive-actions"><button className="button secondary" onClick={()=>setRestoreOpen(false)}>Cancel</button><button className="button primary" onClick={restore} disabled={busy||confirmation.trim()!==selected.asset.id}>{busy?"Restoring…":"Restore asset"}</button></div></section></div>}</main>;
}
