"use client";
import { AlertTriangle,CalendarDays,CheckCircle2,Clock3,Plus,Wrench,X } from "lucide-react";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
type Task={id:string;assetId:string;assetName:string;title:string;cadence:string;nextDue:string;status:string;source:string;workOrderId?:string};
type Asset={id:string;name:string}; type User={id:number;name:string;role:string;active:boolean};
const today=()=>new Date().toISOString().slice(0,10);
export default function MaintenancePage(){const[tasks,setTasks]=useState<Task[]>([]),[assets,setAssets]=useState<Asset[]>([]),[users,setUsers]=useState<User[]>([]),[filter,setFilter]=useState<"All"|"Due"|"Upcoming">("All"),[open,setOpen]=useState(false),[selectedDate,setSelectedDate]=useState(today()),[error,setError]=useState("");
 async function refresh(){const[t,a,u]=await Promise.all([fetch("/api/maintenance",{cache:"no-store"}),fetch("/api/assets",{cache:"no-store"}),fetch("/api/users",{cache:"no-store"})]);const[td,ad,ud]=await Promise.all([t.json(),a.json(),u.json()]);setTasks(td.maintenanceTasks||[]);setAssets(ad.assets||[]);setUsers((ud.users||[]).filter((x:User)=>x.active&&["TECHNICIAN","MANAGER","ADMIN"].includes(x.role)))}useEffect(()=>{refresh().catch(()=>setError("Unable to load maintenance plan."))},[]);
 const rows=useMemo(()=>tasks.filter(t=>filter==="All"||(filter==="Due"?t.nextDue<=today():t.nextDue>today())),[tasks,filter]);const due=tasks.filter(t=>t.nextDue<=today()).length,upcoming=tasks.filter(t=>t.nextDue>today()).length;
 async function create(fd:FormData){setError("");const dueDate=String(fd.get("dueDate")||selectedDate),payload={assetId:String(fd.get("assetId")),title:String(fd.get("title")),description:String(fd.get("description")),cadence:String(fd.get("cadence")),priority:String(fd.get("priority")),assignee:String(fd.get("assignee")),dueDate,scheduledStart:`${dueDate}T${String(fd.get("time")||"09:00")}`,source:"Lab calendar / Maintenance Planner"};const r=await fetch("/api/maintenance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok){setError(d.error||"Unable to create task");return}setOpen(false);await refresh()}
 const now=new Date(),year=now.getFullYear(),month=now.getMonth(),first=new Date(year,month,1).getDay(),days=new Date(year,month+1,0).getDate(),monthLabel=now.toLocaleDateString("en-QA",{month:"long",year:"numeric"});
 return <main className="dashboard-main section-page"><section className="page-heading"><div><p className="eyebrow">Preventive maintenance</p><h1>Maintenance Planner</h1><p className="page-subtitle">Every maintenance task creates a linked work order and can be scheduled directly from the Lab calendar.</p></div><button className="button primary" onClick={()=>{setSelectedDate(today());setOpen(true)}}><Wrench size={18}/> Add maintenance task</button></section>{error&&<p className="form-error">{error}</p>}
 <section className="summary-strip"><article><span className="summary-icon coral"><AlertTriangle/></span><div><strong>{due}</strong><small>Due / overdue</small></div></article><article><span className="summary-icon amber"><Clock3/></span><div><strong>{upcoming}</strong><small>Upcoming</small></div></article><article><span className="summary-icon teal"><CheckCircle2/></span><div><strong>{tasks.filter(t=>t.status.toLowerCase().includes("complete")).length}</strong><small>Completed</small></div></article><article><span className="summary-icon blue"><CalendarDays/></span><div><strong>{tasks.length}</strong><small>Planned tasks</small></div></article></section>
 <section className="maintenance-layout"><article className="detail-section maintenance-table-card"><div className="section-title"><h2>Maintenance schedule</h2><div className="mini-tabs">{(["All","Due","Upcoming"] as const).map(f=><button className={filter===f?"active":""} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div></div><div className="responsive-table"><table><thead><tr><th>Task / Work order</th><th>Asset</th><th>Cadence</th><th>Next due</th><th>Status</th></tr></thead><tbody>{rows.map(task=><tr key={task.id}><td><strong>{task.workOrderId?<Link href={`/work-orders?open=${encodeURIComponent(task.workOrderId)}`}>{task.title}</Link>:task.title}</strong><small>{task.workOrderId||task.source}</small></td><td><Link href={`/assets/${task.assetId}`}>{task.assetName||task.assetId}<small>{task.assetId}</small></Link></td><td>{task.cadence}</td><td>{task.nextDue}</td><td><span className={`table-status ${task.nextDue<=today()?"overdue":"upcoming"}`}>{task.nextDue<=today()?"Due":"Upcoming"}</span></td></tr>)}</tbody></table></div></article>
 <aside className="maintenance-side"><article className="detail-section"><div className="section-title"><h2>{monthLabel}</h2><span>Lab calendar · click a date</span></div><div className="mini-calendar"><div className="calendar-head">{["S","M","T","W","T","F","S"].map((d,i)=><span key={`${d}-${i}`}>{d}</span>)}</div><div className="calendar-days">{Array.from({length:42},(_,i)=>{const day=i-first+1;if(day<1||day>days)return <span className="muted" key={i}/>;const date=`${year}-${String(month+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`,hasTask=tasks.some(t=>t.nextDue===date);return <button className={`${date===today()?"today":""} ${hasTask?"has-task":""}`} key={i} onClick={()=>{setSelectedDate(date);setOpen(true)}}>{day}</button>})}</div></div><div className="calendar-legend"><span><i className="today"/> Today</span><span><i/> Planned task</span></div></article><article className="callout-card"><Wrench size={22}/><h3>Calendar-linked workflow</h3><p>Select any Lab calendar date to open Add Maintenance Task with that schedule prefilled.</p><Link href="/work-orders">Open Work Order Control</Link></article></aside></section>
 {open&&<div className="modal-layer drawer-layer"><button className="modal-backdrop" onClick={()=>setOpen(false)}/><section className="issue-drawer"><div className="drawer-header"><div><p className="eyebrow">Maintenance + Work Order</p><h2>Add maintenance task</h2></div><button className="modal-close inline" onClick={()=>setOpen(false)}><X/></button></div><form action={create}><label>Asset<select name="assetId" required>{assets.map(a=><option key={a.id} value={a.id}>{a.name} · {a.id}</option>)}</select></label><label>Work required<input name="title" required placeholder="Inspect and service equipment"/></label><label>Description<textarea name="description" rows={4} placeholder="Checklist, readings and evidence required…"/></label><div className="form-grid"><label>Schedule date<input name="dueDate" type="date" value={selectedDate} onChange={e=>setSelectedDate(e.target.value)}/></label><label>Start time<input name="time" type="time" defaultValue="09:00"/></label></div><div className="form-grid"><label>Cadence<select name="cadence"><option>One-off</option><option>Weekly</option><option>Monthly</option><option>Quarterly</option><option>Annual</option></select></label><label>Priority<select name="priority"><option>Normal</option><option>High</option><option>Critical</option></select></label></div><label>Assignee technician<select name="assignee"><option>Unassigned</option>{users.map(u=><option key={u.id}>{u.name}</option>)}</select></label><button className="button primary full"><Plus size={18}/> Create task + work order</button></form></section></div>}
 </main>}

