import { createClient } from "./supabase/server";
import { isPlatformAdministrator,type UserRecord } from "./database";

type Row=Record<string,unknown>;
function text(v:unknown,f=""){return v==null?f:String(v)}
function num(v:unknown,f=0){const n=Number(v);return Number.isFinite(n)?n:f}
function rel(v:unknown,key="full_name"){const row=Array.isArray(v)?v[0]:v;return row&&typeof row==="object"?text((row as Row)[key]):""}
function fail(error:{message?:string}|null){if(error)throw new Error(error.message||"Supabase operation failed")}
export type TrackableType="task"|"activity"|"kpi"|"milestone";
const select="*,projects(name),owner:profiles!trackable_items_owner_user_id_fkey(full_name,email),reviewer:profiles!trackable_items_reviewer_id_fkey(full_name,email),groups(name),progress_logs(*,profiles(full_name))";
function trackable(row:Row){return{id:text(row.id),projectId:text(row.project_id),projectName:rel(row.projects,"name"),type:text(row.type),title:text(row.title),description:text(row.description),category:text(row.category),ownerType:row.owner_type?text(row.owner_type):null,ownerId:text(row.owner_user_id||row.owner_group_id)||null,ownerName:rel(row.owner)||rel(row.groups,"name")||"Unassigned",reviewerId:text(row.reviewer_id)||null,reviewerName:rel(row.reviewer)||"",groupTargetMode:text(row.group_target_mode,"shared"),metricType:row.metric_type?text(row.metric_type):null,targetValue:row.target_value==null?null:num(row.target_value),currentValue:row.current_value==null?null:num(row.current_value),unit:text(row.unit),frequency:text(row.frequency),status:text(row.status),progressPercent:num(row.progress_percent),priority:text(row.priority),weight:num(row.weight,1),startDate:text(row.start_date),dueDate:text(row.due_date),deferReason:text(row.defer_reason),responseNote:text(row.response_note),respondedAt:text(row.responded_at),sourceKey:text(row.source_key),createdBy:text(row.created_by),createdAt:text(row.created_at),logs:(Array.isArray(row.progress_logs)?row.progress_logs as Row[]:[]).sort((a,b)=>text(b.created_at).localeCompare(text(a.created_at))).map(log=>({id:text(log.id),updatedBy:rel(log.profiles),value:log.value==null?null:num(log.value),progressPercent:log.progress_percent==null?null:num(log.progress_percent),status:text(log.status),note:text(log.note),attachmentUrl:text(log.attachment_url),createdAt:text(log.created_at)}))}}
export async function listTrackables(filters:Row={}){const s=await createClient();let q=s.from("trackable_items").select(select).order("due_date",{ascending:true,nullsFirst:false});if(filters.projectId)q=q.eq("project_id",text(filters.projectId));if(filters.type)q=q.eq("type",text(filters.type));if(filters.status)q=q.eq("status",text(filters.status));if(filters.ownerUserId)q=q.eq("owner_user_id",text(filters.ownerUserId));if(filters.ownerGroupId)q=q.eq("owner_group_id",text(filters.ownerGroupId));if(filters.from)q=q.gte("due_date",text(filters.from));if(filters.to)q=q.lte("due_date",text(filters.to));const{data,error}=await q;fail(error);return(data||[]).map(r=>trackable(r as Row))}
export async function getTrackable(id:string){const s=await createClient();const{data,error}=await s.from("trackable_items").select(select).eq("id",id).maybeSingle();fail(error);return data?trackable(data as Row):undefined}
export async function canRespondToTrackable(item:ReturnType<typeof trackable>,actor:UserRecord){if(isPlatformAdministrator(actor.role))return true;if(item.ownerType==="user")return item.ownerId===actor.id;if(item.ownerType==="group"&&item.ownerId){const s=await createClient(),{data,error}=await s.from("group_members").select("user_id").eq("group_id",item.ownerId).eq("user_id",actor.id).maybeSingle();fail(error);return Boolean(data)}return false}
function itemRow(input:Row,actor:UserRecord){const type=text(input.type,"task").toLowerCase(),ownerType=text(input.ownerType);return{project_id:text(input.projectId),type,title:text(input.title),description:text(input.description),category:text(input.category),owner_type:ownerType||null,owner_user_id:ownerType==="user"?text(input.ownerId)||null:null,owner_group_id:ownerType==="group"?text(input.ownerId)||null:null,reviewer_id:text(input.reviewerId)||null,group_target_mode:text(input.groupTargetMode,"shared"),metric_type:type==="kpi"?text(input.metricType,"numeric"):null,target_value:type==="kpi"?num(input.targetValue):null,current_value:type==="kpi"?num(input.currentValue):null,unit:type==="kpi"?text(input.unit):null,frequency:type==="kpi"?text(input.frequency,"monthly"):null,status:text(input.status,type==="task"?"pending":"not_started"),progress_percent:num(input.progressPercent),priority:text(input.priority,"normal").toLowerCase(),weight:num(input.weight,1),start_date:text(input.startDate)||null,due_date:text(input.dueDate)||null,source_key:text(input.sourceKey)||null,source_config:input.sourceConfig&&typeof input.sourceConfig==="object"?input.sourceConfig:{},created_by:actor.id}}
async function notifyOwners(item:Row,id:string,title:string,message:string){const s=await createClient();const ids:string[]=[];if(text(item.owner_user_id))ids.push(text(item.owner_user_id));if(text(item.owner_group_id)){const{data}=await s.from("group_members").select("user_id").eq("group_id",text(item.owner_group_id));for(const r of data||[])ids.push(r.user_id)}if(ids.length)fail((await s.from("notifications").insert([...new Set(ids)].map(user_id=>({user_id,entity_type:"trackable_item",entity_id:id,title,message})))).error)}
export async function createTrackable(input:Row,actor:UserRecord){const s=await createClient(),row=itemRow(input,actor);if(!row.project_id||!row.title)throw new Error("Project and title are required");if(Boolean(row.owner_user_id)===Boolean(row.owner_group_id))throw new Error("Choose one user or one group as owner");const{data,error}=await s.from("trackable_items").insert(row).select(select).single();fail(error);await s.from("progress_logs").insert({trackable_item_id:data.id,updated_by:actor.id,progress_percent:row.progress_percent,status:row.status,note:"Item created"});await notifyOwners(row,data.id,`New ${row.type} assigned`,`${row.title}${row.due_date?` · due ${row.due_date}`:""}`);return trackable(data as Row)}
export async function updateTrackable(id:string,input:Row,actor:UserRecord){const s=await createClient(),current=await getTrackable(id);if(!current)return;const patch:Row={};for(const[k,column]of Object.entries({title:"title",description:"description",category:"category",status:"status",progressPercent:"progress_percent",currentValue:"current_value",targetValue:"target_value",unit:"unit",priority:"priority",weight:"weight",startDate:"start_date",dueDate:"due_date",reviewerId:"reviewer_id"}))if(input[k]!==undefined)patch[column]=input[k]===""?null:input[k];if(input.action){const action=text(input.action);patch.status=action==="accept"?"accepted":action==="defer"?"deferred":action==="complete"?"completed":current.status;if(action==="defer"&&!text(input.note).trim())throw new Error("A defer reason is required");patch.defer_reason=action==="defer"?text(input.note):null;patch.response_note=text(input.note)||null;patch.responded_at=new Date().toISOString();}const{data,error}=await s.from("trackable_items").update(patch).eq("id",id).select(select).single();fail(error);await s.from("progress_logs").insert({trackable_item_id:id,updated_by:actor.id,value:patch.current_value??null,progress_percent:patch.progress_percent??null,status:patch.status??null,note:text(input.note)||"Item updated",attachment_url:text(input.attachmentUrl)||null});if(current.createdBy&&current.createdBy!==actor.id)await s.from("notifications").insert({user_id:current.createdBy,entity_type:"trackable_item",entity_id:id,title:`${current.title} updated`,message:text(input.note)||`Status changed to ${patch.status||current.status}`});return trackable(data as Row)}
export async function deleteTrackable(id:string){const s=await createClient();const{error}=await s.from("trackable_items").delete().eq("id",id);fail(error);return true}
export async function applyTrackableSourceEvent(input:Row){const sourceKey=text(input.sourceKey).trim();if(!sourceKey)throw new Error("sourceKey is required");const s=await createClient(),{data,error}=await s.rpc("apply_trackable_source_event",{p_source_key:sourceKey,p_current_value:num(input.currentValue),p_progress_percent:input.progressPercent==null?null:num(input.progressPercent),p_note:text(input.note,"Automated source update")});fail(error);return getTrackable(text(data))}
export async function assignTrackable(id:string,input:Row){const ownerType=text(input.ownerType),ownerId=text(input.ownerId);if(!['user','group'].includes(ownerType)||!ownerId)throw new Error("Choose one user or group");const s=await createClient(),patch={owner_type:ownerType,owner_user_id:ownerType==='user'?ownerId:null,owner_group_id:ownerType==='group'?ownerId:null,reviewer_id:text(input.reviewerId)||null,group_target_mode:text(input.groupTargetMode,'shared')};const{data,error}=await s.from("trackable_items").update(patch).eq("id",id).select(select).single();fail(error);await notifyOwners(patch,id,"Project control assignment",`${data.title} was assigned to you.`);return trackable(data as Row)}
export async function listGroups(projectId?:string){const s=await createClient();let q=s.from("groups").select("*,group_members(user_id,profiles(full_name,email))").order("name");if(projectId)q=q.eq("project_id",projectId);const{data,error}=await q;fail(error);return(data||[]).map(g=>({id:g.id,projectId:g.project_id,name:g.name,description:g.description,members:(g.group_members||[]).map((m:Row)=>({id:m.user_id,name:rel(m.profiles)}))}))}
export async function createGroup(input:Row,actor:UserRecord){const s=await createClient();const{data,error}=await s.from("groups").insert({project_id:text(input.projectId),name:text(input.name),description:text(input.description),created_by:actor.id}).select().single();fail(error);const members=Array.isArray(input.memberIds)?input.memberIds.map(String):[];if(members.length)fail((await s.from("group_members").insert(members.map(user_id=>({group_id:data.id,user_id})))).error);return data}
export async function listRisks(projectId?:string){const s=await createClient();let q=s.from("risk_issues").select("*,projects(name),owner:profiles!risk_issues_owner_user_id_fkey(full_name,email),creator:profiles!risk_issues_created_by_fkey(full_name,email)").order("created_at",{ascending:false});if(projectId)q=q.eq("project_id",projectId);const{data,error}=await q;fail(error);return(data||[]).map(r=>({id:r.id,projectId:r.project_id,projectName:rel(r.projects,"name"),title:r.title,description:r.description,severity:r.severity,status:r.status,ownerId:r.owner_user_id,ownerName:rel(r.owner),createdBy:r.created_by,createdByName:rel(r.creator),dueDate:r.due_date,createdAt:r.created_at}))}
export async function createRisk(input:Row,actor:UserRecord){const s=await createClient();const{data,error}=await s.from("risk_issues").insert({project_id:text(input.projectId),title:text(input.title),description:text(input.description),severity:text(input.severity,"medium"),status:text(input.status,"open"),owner_user_id:text(input.ownerId)||null,due_date:text(input.dueDate)||null,created_by:actor.id}).select().single();fail(error);if(data.owner_user_id)await s.from("notifications").insert({user_id:data.owner_user_id,entity_type:"risk_issue",entity_id:data.id,title:"Risk assigned",message:data.title});return data}
export async function updateRisk(id:string,input:Row){const s=await createClient();const patch=Object.fromEntries(Object.entries({title:input.title,description:input.description,severity:input.severity,status:input.status,owner_user_id:input.ownerId,due_date:input.dueDate}).filter(([,v])=>v!==undefined));const{data,error}=await s.from("risk_issues").update(patch).eq("id",id).select().single();fail(error);return data}
export async function deleteRisk(id:string){const s=await createClient();fail((await s.from("risk_issues").delete().eq("id",id)).error);return true}
