-- Ibtechar SmartCare Order Progress installation
-- Run this once in Supabase SQL Editor after the existing SmartCare schema/migrations.

begin;

create table if not exists public.order_progress (
  id uuid primary key default gen_random_uuid(),
  purchase_request_id text not null unique references public.purchase_requests(id) on delete restrict,
  purchase_request_item_id text,
  purchase_order_id text references public.purchase_orders(id) on delete set null,
  project_id uuid not null references public.projects(id) on delete restrict,
  requested_by uuid references public.profiles(id) on delete set null,
  responsible_user_id uuid references public.profiles(id) on delete set null,
  item_name text not null,
  description text not null default '',
  quantity integer not null default 1 check (quantity > 0),
  supplier text not null default '',
  progress_percentage integer not null default 0 check (progress_percentage between 0 and 100),
  status text not null default 'Purchase Request Created',
  expected_delivery_date date,
  actual_delivery_date date,
  tracking_reference text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id) on delete set null
);

create table if not exists public.order_progress_updates (
  id bigint generated by default as identity primary key,
  order_progress_id uuid not null references public.order_progress(id) on delete cascade,
  previous_percentage integer not null,
  new_percentage integer not null,
  previous_status text not null,
  new_status text not null,
  previous_expected_delivery_date date,
  new_expected_delivery_date date,
  previous_actual_delivery_date date,
  new_actual_delivery_date date,
  previous_supplier text not null default '',
  new_supplier text not null default '',
  previous_tracking_reference text not null default '',
  new_tracking_reference text not null default '',
  note text not null default '',
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.order_progress_users (
  id bigint generated by default as identity primary key,
  order_progress_id uuid not null references public.order_progress(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  relationship_type text not null,
  created_at timestamptz not null default now(),
  unique(order_progress_id, user_id, relationship_type)
);

create index if not exists order_progress_project_idx on public.order_progress(project_id, status);
create index if not exists order_progress_status_idx on public.order_progress(status, progress_percentage);
create index if not exists order_progress_expected_idx on public.order_progress(expected_delivery_date);
create index if not exists order_progress_updates_item_idx on public.order_progress_updates(order_progress_id, created_at desc);
create index if not exists order_progress_users_item_idx on public.order_progress_users(order_progress_id, user_id);

create or replace function public.set_order_progress_updated_at()
returns trigger language plpgsql set search_path = ''
as $$ begin new.updated_at = now(); return new; end $$;

drop trigger if exists order_progress_set_updated_at on public.order_progress;
create trigger order_progress_set_updated_at
before update on public.order_progress
for each row execute function public.set_order_progress_updated_at();

-- Backfill requests created before Order Progress was installed.
insert into public.order_progress (
  purchase_request_id, purchase_order_id, project_id, requested_by,
  item_name, description, quantity, progress_percentage, status
)
select
  pr.id,
  pr.purchase_order_id,
  pr.project_id,
  pr.requester_user_id,
  coalesce(nullif(pr.reason, ''), nullif(pr.description, ''), 'Purchase request item'),
  coalesce(pr.description, ''),
  1,
  0,
  case
    when lower(coalesce(pr.status, '')) like '%reject%' then 'Rejected'
    when pr.purchase_order_id is not null then 'PO Issued'
    else 'Purchase Request Created'
  end
from public.purchase_requests pr
where not exists (
  select 1 from public.order_progress op
  where op.purchase_request_id = pr.id
);

insert into public.order_progress_updates (
  order_progress_id, previous_percentage, new_percentage,
  previous_status, new_status, note, created_by
)
select
  op.id, 0, op.progress_percentage,
  'Purchase Request Created', op.status,
  'Order Progress initialized from existing Purchase Request.',
  op.requested_by
from public.order_progress op
where not exists (
  select 1 from public.order_progress_updates u
  where u.order_progress_id = op.id
);

insert into public.app_modules(module_key, title, path, enabled, sort_order)
values ('order_progress', 'Order Progress', '/order-progress', true, 115)
on conflict (module_key) do update
set title = excluded.title, path = excluded.path, enabled = true, sort_order = excluded.sort_order;

insert into public.user_permissions(user_id, module_key, can_view, can_create, can_edit, can_delete, can_approve)
select p.id, 'order_progress', true, true, true, false, false
from public.profiles p
join public.roles r on r.id = p.role_id
where p.active
  and r.name in ('CEO', 'ADMIN', 'MANAGER', 'FINANCE', 'TECHNICIAN', 'STAFF', 'VIEWER')
on conflict (user_id, module_key) do update
set can_view = true,
    can_create = excluded.can_create,
    can_edit = excluded.can_edit;

alter table public.order_progress enable row level security;
alter table public.order_progress_updates enable row level security;
alter table public.order_progress_users enable row level security;

drop policy if exists order_progress_read on public.order_progress;
drop policy if exists order_progress_write on public.order_progress;
drop policy if exists order_progress_updates_read on public.order_progress_updates;
drop policy if exists order_progress_updates_write on public.order_progress_updates;
drop policy if exists order_progress_users_read on public.order_progress_users;
drop policy if exists order_progress_users_write on public.order_progress_users;

create policy order_progress_read on public.order_progress
for select to authenticated
using (
  app_private.can_project(project_id, 'view')
  or requested_by = (select auth.uid())
  or responsible_user_id = (select auth.uid())
);

create policy order_progress_write on public.order_progress
for all to authenticated
using (
  app_private.can_project(project_id, 'edit')
  or requested_by = (select auth.uid())
  or responsible_user_id = (select auth.uid())
)
with check (
  app_private.can_project(project_id, 'edit')
  or requested_by = (select auth.uid())
  or responsible_user_id = (select auth.uid())
);

create policy order_progress_updates_read on public.order_progress_updates
for select to authenticated
using (exists (
  select 1 from public.order_progress op
  where op.id = order_progress_id
    and (
      app_private.can_project(op.project_id, 'view')
      or op.requested_by = (select auth.uid())
      or op.responsible_user_id = (select auth.uid())
    )
));

create policy order_progress_updates_write on public.order_progress_updates
for insert to authenticated
with check (exists (
  select 1 from public.order_progress op
  where op.id = order_progress_id
    and (
      app_private.can_project(op.project_id, 'edit')
      or op.requested_by = (select auth.uid())
      or op.responsible_user_id = (select auth.uid())
    )
));

create policy order_progress_users_read on public.order_progress_users
for select to authenticated
using (exists (
  select 1 from public.order_progress op
  where op.id = order_progress_id
    and (
      app_private.can_project(op.project_id, 'view')
      or op.requested_by = (select auth.uid())
      or op.responsible_user_id = (select auth.uid())
    )
));

create policy order_progress_users_write on public.order_progress_users
for all to authenticated
using (exists (
  select 1 from public.order_progress op
  where op.id = order_progress_id
    and app_private.can_project(op.project_id, 'edit')
))
with check (exists (
  select 1 from public.order_progress op
  where op.id = order_progress_id
    and app_private.can_project(op.project_id, 'edit')
));

commit;
