"use client";

import {ArrowDown, ChevronRight, CircleDollarSign, Folder, FolderTree, Plus, X} from "lucide-react";
import Link from "next/link";
import {useEffect, useMemo, useState} from "react";
import {useSmartCareAuth} from "../components/auth-provider";

type Project={id:string;name:string;manager:string;approvedBudget:number;committed:number;spent:number;availableBudget?:number;unallocatedBudget?:number;allocatedToChildren?:number;status:string;parentProjectId?:string|null;projectCode?:string};
const money=new Intl.NumberFormat("en-QA",{style:"currency",currency:"QAR",maximumFractionDigits:0});
const percent=(value:number,total:number)=>total?Math.min(100,Math.round(value/total*100)):0;

export default function SubProjectsPage(){
 const{can}=useSmartCareAuth(),[projects,setProjects]=useState<Project[]>([]),[open,setOpen]=useState(false),[error,setError]=useState("");
 async function refresh(){const r=await fetch("/api/projects",{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load projects");setProjects(d.projects||[])}
 useEffect(()=>{refresh().catch(e=>setError(e.message))},[]);
 const mains=useMemo(()=>projects.filter(p=>!p.parentProjectId),[projects]);
 const children=useMemo(()=>projects.filter(p=>p.parentProjectId),[projects]);
 const totals=useMemo(()=>({parents:mains.length,children:children.length,allocated:children.reduce((sum,p)=>sum+p.approvedBudget,0),spent:children.reduce((sum,p)=>sum+p.spent,0)}),[mains,children]);
 async function create(fd:FormData){const r=await fetch("/api/projects",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:String(fd.get("name")),manager:String(fd.get("manager")),approvedBudget:Number(fd.get("approvedBudget")),parentProjectId:String(fd.get("parentProjectId")),projectCode:String(fd.get("projectCode"))})}),d=await r.json();if(!r.ok){setError(d.error||"Unable to create sub-project");return}setOpen(false);await refresh()}
 return <main className="dashboard-main section-page subprojects-page">
  <section className="page-heading"><div><p className="eyebrow">Project hierarchy</p><h1>Sub-projects</h1><p className="page-subtitle">Break a main project into smaller, independently managed work packages. Their budgets and results roll up to the parent project.</p></div>{can("projects","create")&&<button className="button primary" onClick={()=>setOpen(true)}><Plus size={17}/> New sub-project</button>}</section>
  {error&&<p className="form-error">{error}</p>}
  <section className="subproject-concept" aria-label="How sub-projects work"><div className="concept-copy"><span><FolderTree size={20}/></span><div><strong>How the hierarchy works</strong><p>A main project holds the total approved budget. You allocate part of it to sub-projects, then manage each sub-project’s owner, spending and delivery separately.</p></div></div><div className="concept-flow" aria-hidden="true"><span><Folder size={17}/> Main project</span><ChevronRight size={16}/><span><CircleDollarSign size={17}/> Allocate budget</span><ChevronRight size={16}/><span><FolderTree size={17}/> Sub-projects</span></div></section>
  <section className="subproject-summary" aria-label="Sub-project portfolio summary"><article><small>Main projects</small><strong>{totals.parents}</strong><span>Budget owners</span></article><article><small>Sub-projects</small><strong>{totals.children}</strong><span>Controlled work packages</span></article><article><small>Allocated to sub-projects</small><strong>{money.format(totals.allocated)}</strong><span>Combined allocations</span></article><article><small>Sub-project spend</small><strong>{money.format(totals.spent)}</strong><span>{percent(totals.spent,totals.allocated)}% of allocated budget</span></article></section>
  <div className="hierarchy-heading"><div><p className="eyebrow">Parent-to-child view</p><h2>Project structure</h2></div><span>{children.length} sub-project{children.length===1?"":"s"} across {mains.length} main project{mains.length===1?"":"s"}</span></div>
  <section className="project-hierarchy-list">
   {mains.map(main=>{const cs=children.filter(c=>c.parentProjectId===main.id),allocated=main.allocatedToChildren??cs.reduce((sum,c)=>sum+c.approvedBudget,0),unallocated=main.unallocatedBudget??Math.max(0,main.approvedBudget-allocated),allocationRate=percent(allocated,main.approvedBudget);return <article className="parent-project-card" key={main.id}><header className="parent-project-header"><div className="parent-project-identity"><span className="parent-folder"><Folder size={22}/></span><div><small>Main project</small><h3>{main.name}</h3><p>{main.manager} · {cs.length} sub-project{cs.length===1?"":"s"}</p></div></div><Link className="text-button" href={`/project-dashboard?project=${encodeURIComponent(main.name)}`}>Open parent <ChevronRight size={14}/></Link></header><div className="parent-budget-row"><div><span>Approved budget <strong>{money.format(main.approvedBudget)}</strong></span><span>Allocated <strong>{money.format(allocated)}</strong></span><span>Still unallocated <strong className="available-value">{money.format(unallocated)}</strong></span></div><div className="allocation-track"><i style={{width:`${allocationRate}%`}}/></div><small>{allocationRate}% of the parent budget is assigned to sub-projects</small></div><div className="hierarchy-connector"><ArrowDown size={14}/><span>Budget and results roll up to {main.name}</span></div>
    {cs.length?<div className="child-project-grid">{cs.map(child=>{const used=percent(child.spent,child.approvedBudget);return <Link className="child-project-card" href={`/project-dashboard?project=${encodeURIComponent(child.name)}`} key={child.id}><div className="child-card-top"><span className="child-icon"><FolderTree size={18}/></span><span className={`rag-badge ${child.status==="Closed"?"healthy":"blue"}`}>{child.status}</span></div><div className="child-title"><small>Sub-project {child.projectCode?`· ${child.projectCode}`:""}</small><h4>{child.name}</h4><p>Managed by {child.manager}</p></div><div className="child-finances"><span><small>Allocation</small><strong>{money.format(child.approvedBudget)}</strong></span><span><small>Committed</small><strong>{money.format(child.committed)}</strong></span><span><small>Spent</small><strong>{money.format(child.spent)}</strong></span></div><div className="child-spend-line"><div><span>Budget used</span><strong>{used}%</strong></div><i><b style={{width:`${used}%`}}/></i></div><footer>Open sub-project control <ChevronRight size={14}/></footer></Link>})}</div>:<div className="subproject-empty"><FolderTree size={24}/><div><strong>No sub-projects yet</strong><p>Create a work package and allocate part of {main.name}’s available budget.</p></div>{can("projects","create")&&<button className="button secondary" onClick={()=>setOpen(true)}><Plus size={15}/> Add sub-project</button>}</div>}
   </article>})}
   {!mains.length&&!error&&<div className="empty-state"><FolderTree size={30}/><h2>No main projects available</h2><p>Create a main project first, then return here to divide it into controlled sub-projects.</p></div>}
  </section>
  {open&&<div className="modal-layer drawer-layer"><button className="modal-backdrop" onClick={()=>setOpen(false)} aria-label="Close create sub-project form"/><section className="issue-drawer"><div className="drawer-header"><div><p className="eyebrow">Controlled work package</p><h2>Create sub-project</h2></div><button className="modal-close inline" onClick={()=>setOpen(false)} aria-label="Close"><X/></button></div><div className="drawer-context"><FolderTree size={18}/><p>The allocation is taken from the selected parent’s unallocated budget. Spending and progress will still roll up to that parent.</p></div><form action={create}><label>Parent project<select name="parentProjectId" required defaultValue=""><option value="">Choose parent</option>{mains.filter(p=>p.status!=="Closed").map(p=><option key={p.id} value={p.id}>{p.name} · {money.format(p.unallocatedBudget??p.approvedBudget)} available</option>)}</select></label><label>Sub-project name<input name="name" required placeholder="e.g. Phase 1 – Site preparation"/></label><div className="form-grid"><label>Code<input name="projectCode" placeholder="Optional"/></label><label>Manager<input name="manager" defaultValue="Projects Office" required/></label></div><label>Budget allocation (QAR)<input name="approvedBudget" type="number" min="0" step="0.01" required/></label><button className="button primary full"><FolderTree size={16}/> Create sub-project</button></form></section></div>}
 </main>
}
