"use client";
import {FolderTree,Plus,ChevronRight} from "lucide-react";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {useSmartCareAuth} from "../components/auth-provider";
type Project={id:string;name:string;manager:string;approvedBudget:number;committed:number;spent:number;availableBudget?:number;unallocatedBudget?:number;status:string;parentProjectId?:string|null;parentProjectName?:string};
const money=new Intl.NumberFormat("en-QA",{style:"currency",currency:"QAR",maximumFractionDigits:0});
export default function SubProjectsPage(){
 const{can}=useSmartCareAuth(),[projects,setProjects]=useState<Project[]>([]),[open,setOpen]=useState(false),[error,setError]=useState("");
 async function refresh(){const r=await fetch("/api/projects",{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load projects");setProjects(d.projects||[])}
 useEffect(()=>{refresh().catch(e=>setError(e.message))},[]);
 const mains=useMemo(()=>projects.filter(p=>!p.parentProjectId),[projects]),children=useMemo(()=>projects.filter(p=>p.parentProjectId),[projects]);
 async function create(fd:FormData){const r=await fetch("/api/projects",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:String(fd.get("name")),manager:String(fd.get("manager")),approvedBudget:Number(fd.get("approvedBudget")),parentProjectId:String(fd.get("parentProjectId")),projectCode:String(fd.get("projectCode"))})}),d=await r.json();if(!r.ok){setError(d.error||"Unable to create sub-project");return}setOpen(false);await refresh()}
 return <main className="dashboard-main section-page"><section className="page-heading"><div><p className="eyebrow">Project hierarchy</p><h1>Sub-project Control</h1><p className="page-subtitle">Control budget, expenses, tasks, activities and KPIs independently while rolling results into the parent project.</p></div>{can("projects","create")&&<button className="button primary" onClick={()=>setOpen(true)}><Plus size={17}/> New sub-project</button>}</section>{error&&<p className="form-error">{error}</p>}
 <section className="budget-table-card"><div className="responsive-table"><table><thead><tr><th>Main project</th><th>Sub-project</th><th>Allocation</th><th>Committed</th><th>Spent</th><th>Status</th><th></th></tr></thead><tbody>{mains.flatMap(main=>{const cs=children.filter(c=>c.parentProjectId===main.id);return cs.length?cs.map(c=><tr key={c.id}><td><strong>{main.name}</strong></td><td>{c.name}<small>{c.manager}</small></td><td>{money.format(c.approvedBudget)}</td><td>{money.format(c.committed)}</td><td>{money.format(c.spent)}</td><td><span className={`rag-badge ${c.status==="Closed"?"healthy":"blue"}`}>{c.status}</span></td><td><Link className="text-button" href={`/project-dashboard?project=${encodeURIComponent(c.name)}`}>Control <ChevronRight size={14}/></Link></td></tr>):[<tr key={`${main.id}-empty`}><td><strong>{main.name}</strong></td><td colSpan={6}>No sub-projects yet · {money.format(main.unallocatedBudget??main.approvedBudget)} unallocated</td></tr>]})}</tbody></table></div></section>
 {open&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setOpen(false)}/><section className="modal-card activity-modal"><p className="eyebrow">Controlled work package</p><h2>Create sub-project</h2><form action={create}><label>Parent project<select name="parentProjectId" required defaultValue=""><option value="">Choose parent</option>{mains.filter(p=>p.status!=="Closed").map(p=><option key={p.id} value={p.id}>{p.name} · {money.format(p.unallocatedBudget??p.approvedBudget)} unallocated</option>)}</select></label><label>Sub-project name<input name="name" required/></label><div className="form-grid"><label>Code<input name="projectCode"/></label><label>Manager<input name="manager" defaultValue="Projects Office" required/></label></div><label>Budget allocation (QAR)<input name="approvedBudget" type="number" min="0" step="0.01" required/></label><button className="button primary full"><FolderTree size={16}/> Create sub-project</button></form></section></div>}</main>
}
