"use client";

import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState } from "react";
import type { ModuleAction, ModuleRecord, UserPermissionRecord, UserRecord } from "../lib/database";
import { createClient } from "../lib/supabase/client";
import { PasswordInput } from "./password-input";

type AuthState = {
  user: UserRecord | null; modules: ModuleRecord[]; permissions: UserPermissionRecord[];
  loading: boolean; error: string; isLocalPreview: boolean; firstLoginRequired: boolean; completeFirstLogin: (currentPassword: string, newPassword: string) => Promise<void>;
  login: (email: string, password: string) => Promise<void>; logout: () => Promise<void>;
  switchUser: (email: string) => Promise<void>; can: (moduleKey: string, action?: ModuleAction) => boolean;
};
const AuthContext = createContext<AuthState | null>(null);
export function useSmartCareAuth(){const value=useContext(AuthContext);if(!value)throw new Error("useSmartCareAuth must be used inside SmartCareAuthProvider");return value;}

export function SmartCareAuthProvider({children}:{children:React.ReactNode}){
  const [user,setUser]=useState<UserRecord|null>(null),[modules,setModules]=useState<ModuleRecord[]>([]),[permissions,setPermissions]=useState<UserPermissionRecord[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(""),[firstLoginRequired,setFirstLoginRequired]=useState(false);
  const profileRequest=useRef<Promise<void>|null>(null),profileUserId=useRef("");
  const isLocalPreview=false;
  const loadProfile=useCallback(async(expectedUserId="")=>{if(expectedUserId&&profileUserId.current===expectedUserId)return;if(profileRequest.current)return profileRequest.current;const task=(async()=>{const response=await fetch("/api/users/profile",{cache:"no-store",credentials:"same-origin"});if(!response.ok){profileUserId.current="";setUser(null);setModules([]);setPermissions([]);const body=await response.json().catch(()=>null) as {error?:string}|null;throw new Error(body?.error||"SmartCare could not load your user profile.");}const data=await response.json() as {user:UserRecord;modules:ModuleRecord[];permissions:UserPermissionRecord[]};profileUserId.current=data.user.id;setUser(data.user);setModules(data.modules);setPermissions(data.permissions);})();profileRequest.current=task;try{await task}finally{if(profileRequest.current===task)profileRequest.current=null}},[]);
  useEffect(()=>{let active=true;let unsubscribe=()=>{};try{const supabase=createClient();setLoading(true);const timeout=window.setTimeout(()=>{if(active){setError("Authentication is taking too long. Check the Supabase connection and try again.");setLoading(false);}},10000);supabase.auth.getSession().then(async({data,error:sessionError})=>{if(sessionError)throw sessionError;if(data.session){setFirstLoginRequired(data.session.user.user_metadata?.first_login_required===true);await loadProfile(data.session.user.id);}}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:"Authentication unavailable");}).finally(()=>{window.clearTimeout(timeout);if(active)setLoading(false);});const{data}=supabase.auth.onAuthStateChange((event,session)=>{if(!active)return;if(event==="SIGNED_OUT"){profileUserId.current="";setUser(null);setModules([]);setPermissions([]);setFirstLoginRequired(false);return;}if(!session||event==="INITIAL_SESSION")return;setFirstLoginRequired(session.user.user_metadata?.first_login_required===true);window.setTimeout(()=>{if(!active)return;void loadProfile(session.user.id).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:"Access denied");});},0);});unsubscribe=()=>data.subscription.unsubscribe();}catch(reason){if(active){setError(reason instanceof Error?reason.message:"Authentication unavailable");setLoading(false);}}return()=>{active=false;unsubscribe();};},[loadProfile]);
  const login=useCallback(async(email:string,password:string)=>{setLoading(true);setError("");try{const{data,error:authError}=await createClient().auth.signInWithPassword({email:email.trim().toLowerCase(),password});if(authError)throw authError;setFirstLoginRequired(data.user.user_metadata?.first_login_required===true);await loadProfile(data.user.id);await fetch("/api/audit-logs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({actionType:"SIGN_IN",metadata:{method:"password"}})}).catch(()=>{});}catch(reason){const message=reason instanceof Error?reason.message:"Login failed";setError(message);throw reason;}finally{setLoading(false);}},[loadProfile]);
  const completeFirstLogin=useCallback(async(currentPassword:string,newPassword:string)=>{if(!user?.email)throw new Error("Your account email is unavailable.");const supabase=createClient();const{error:verifyError}=await supabase.auth.signInWithPassword({email:user.email,password:currentPassword});if(verifyError)throw new Error("The current password is incorrect.");const{error:updateError}=await supabase.auth.updateUser({password:newPassword,data:{first_login_required:false}});if(updateError)throw updateError;setFirstLoginRequired(false);},[user]);
  const logout=useCallback(async()=>{await createClient().auth.signOut();profileUserId.current="";setUser(null);setModules([]);setPermissions([]);setFirstLoginRequired(false);setError("");},[]);
  async function switchUser(){throw new Error("Switch User is disabled with Supabase Auth. Sign out and use the other account so RLS remains enforceable.");}
  const can=useCallback((moduleKey:string,action:ModuleAction="view")=>{if(user?.role==="CEO"||user?.role==="ADMIN")return true;const permission=permissions.find(item=>item.moduleKey===moduleKey);const field={view:"canView",create:"canCreate",edit:"canEdit",delete:"canDelete",approve:"canApprove"}[action] as keyof UserPermissionRecord;return Boolean(permission?.[field]);},[permissions,user]);
  const value=useMemo(()=>({user,modules,permissions,loading,error,isLocalPreview,firstLoginRequired,completeFirstLogin,login,logout,switchUser,can}),[user,modules,permissions,loading,error,isLocalPreview,firstLoginRequired,completeFirstLogin,login,logout,can]);return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;
}

function FirstLoginPasswordModal(){const{firstLoginRequired,completeFirstLogin}=useSmartCareAuth();const[currentPassword,setCurrentPassword]=useState(""),[newPassword,setNewPassword]=useState(""),[confirm,setConfirm]=useState(""),[modalError,setModalError]=useState(""),[saving,setSaving]=useState(false);if(!firstLoginRequired)return null;async function submit(event:React.FormEvent){event.preventDefault();setModalError("");if(!currentPassword){setModalError("Enter your current password.");return;}if(newPassword.length<12){setModalError("Use at least 12 characters for your new password.");return;}if(!/[A-Z]/.test(newPassword)||!/[a-z]/.test(newPassword)||!/[0-9]/.test(newPassword)||!/[^A-Za-z0-9]/.test(newPassword)){setModalError("Include uppercase, lowercase, a number, and a symbol.");return;}if(currentPassword===newPassword){setModalError("Your new password must be different from your current password.");return;}if(newPassword!==confirm){setModalError("New passwords do not match.");return;}setSaving(true);try{await completeFirstLogin(currentPassword,newPassword);}catch(reason){setModalError(reason instanceof Error?reason.message:"Unable to update your password.");}finally{setSaving(false);}}return <div className="first-login-overlay"><section className="first-login-modal" role="dialog" aria-modal="true" aria-labelledby="first-login-title"><img src="/ibtechar-main-logo.png" alt="Ibtechar"/><p className="eyebrow">First sign-in security</p><h2 id="first-login-title">Set your personal password</h2><p>Confirm your current password, then create the private password you will use for SmartCare.</p><form onSubmit={submit}><label>Current password<PasswordInput autoFocus required autoComplete="current-password" value={currentPassword} onChange={event=>setCurrentPassword(event.target.value)}/></label><label>New password<PasswordInput required minLength={12} autoComplete="new-password" value={newPassword} onChange={event=>setNewPassword(event.target.value)}/></label><label>Confirm new password<PasswordInput required minLength={12} autoComplete="new-password" value={confirm} onChange={event=>setConfirm(event.target.value)}/></label>{modalError&&<p className="form-error">{modalError}</p>}<button className="button primary full" disabled={saving}>{saving?"Updating password…":"Set password and continue"}</button></form></section></div>}
export function AuthGate({children}:{children:React.ReactNode}){const{user,loading,error,login,firstLoginRequired}=useSmartCareAuth();const[email,setEmail]=useState(""),[password,setPassword]=useState("");if(loading)return <div className="auth-screen"><img src="/ibtechar-main-logo.png" alt="Ibtechar"/><p>Loading SmartCare V5_01_31826…</p></div>;if(!user)return <main className="auth-screen"><section className="auth-card"><img src="/ibtechar-main-logo.png" alt="Ibtechar"/><p className="eyebrow">Secure access · V5_01_31826</p><h1>SmartCare Login</h1><p>Sign in with your approved company account. Supabase Auth verifies your identity and SmartCare RLS applies your project permissions.</p><form onSubmit={async event=>{event.preventDefault();try{await login(email,password);}catch{}}}><label>Email<input type="email" required autoComplete="email" value={email} onChange={event=>setEmail(event.target.value)}/></label><label>Password<PasswordInput required autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)}/></label>{error&&<p className="form-error">{error}</p>}<button className="button primary full" type="submit">Sign in</button></form><button className="text-button" type="button" onClick={async()=>{if(!email){window.alert("Enter your email address first.");return;}const callback=`${window.location.origin}/auth/callback?next=/auth/reset-password`;const{error:resetError}=await createClient().auth.resetPasswordForEmail(email,{redirectTo:callback});window.alert(resetError?resetError.message:"Password reset email sent. Open the latest email link to choose a new password.");}}>Forgot password?</button><small>Ibtechar SmartCare V5_01_31826 · Developed by Seif Khlif</small></section></main>;return <><div className={firstLoginRequired?"app-content-locked":""}>{children}</div><FirstLoginPasswordModal/></>;}
