"use client";
import {ArrowRight,Box,CalendarDays,CheckCircle2,Clock3,Handshake,PackageCheck,Plus,RotateCcw,ShoppingCart,X,XCircle} from "lucide-react";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {useSmartCareAuth} from "../components/auth-provider";

type Event={id:number;eventType:string;fromStatus:string;toStatus:string;note:string;actorName:string;createdAt:string};
type Loan={id:string;requesterUserId:string;requesterName:string;requesterDepartment:string;project:string;itemName:string;purpose:string;neededFrom:string;expectedReturnDate:string;fulfillmentSource:string;assetId:string|null;assetName:string;purchaseRequestId:string|null;status:string;reviewNote:string;issuedAt:string|null;returnedAt:string|null;returnCondition:string;createdAt:string;events:Event[]};
type Asset={id:string;name:string;category:string;location:string;status:string};
const activeStatuses=["Submitted","Awaiting purchase","Ready for delivery","On loan"];
const tone=(status:string)=>status==="Returned"?"healthy":status==="Rejected"||status==="Cancelled"?"warning":status==="On loan"?"due":"blue";

export default function AssetLoansPage(){
 const{user}=useSmartCareAuth();const[loans,setLoans]=useState<Loan[]>([]),[projects,setProjects]=useState<{id:string;name:string}[]>([]),[assets,setAssets]=useState<Asset[]>([]),[canManage,setCanManage]=useState(false),[open,setOpen]=useState(false),[selected,setSelected]=useState<Loan|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[filter,setFilter]=useState("Active");
 async function refresh(){const r=await fetch("/api/asset-loans",{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load asset loans");setLoans(d.loans||[]);setProjects(d.projects||[]);setAssets(d.assets||[]);setCanManage(Boolean(d.canManage));setSelected(current=>current?(d.loans||[]).find((x:Loan)=>x.id===current.id)||null:null)}
 useEffect(()=>{refresh().catch(e=>setError(e.message))},[]);
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get("open");if(id&&loans.length)setSelected(loans.find(x=>x.id===id)||null)},[loans]);
 const visible=useMemo(()=>loans.filter(x=>filter==="All"||(filter==="Active"?activeStatuses.includes(x.status):x.status===filter)),[loans,filter]);
 const summary={submitted:loans.filter(x=>x.status==="Submitted").length,purchase:loans.filter(x=>x.status==="Awaiting purchase").length,ready:loans.filter(x=>x.status==="Ready for delivery").length,onLoan:loans.filter(x=>x.status==="On loan").length};
 async function create(fd:FormData){setBusy(true);setError("");try{const r=await fetch("/api/asset-loans",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({project:fd.get("project"),itemName:fd.get("itemName"),purpose:fd.get("purpose"),neededFrom:fd.get("neededFrom"),expectedReturnDate:fd.get("expectedReturnDate")})}),d=await r.json();if(!r.ok)throw new Error(d.error);setOpen(false);await refresh();setSelected(d.loan)}catch(e){setError(e instanceof Error?e.message:"Unable to submit request")}finally{setBusy(false)}}
 async function act(fd:FormData){if(!selected)return;setBusy(true);setError("");try{const payload=Object.fromEntries(fd.entries()),r=await fetch("/api/asset-loans",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:selected.id,...payload})}),d=await r.json();if(!r.ok)throw new Error(d.error);await refresh();setSelected(d.loan)}catch(e){setError(e instanceof Error?e.message:"Unable to update request")}finally{setBusy(false)}}
 return <main className="dashboard-main section-page asset-loans-page"><section className="page-heading"><div><p className="eyebrow">Asset custody</p><h1>Asset Loans</h1><p className="page-subtitle">Request equipment, fulfill it from available assets or purchasing, and record delivery and return.</p></div><button className="button primary" onClick={()=>setOpen(true)}><Plus size={17}/> Request asset loan</button></section>{error&&<p className="form-error">{error}</p>}
  <section className="loan-flow"><span><Handshake/> Employee request</span><ArrowRight/><span><CheckCircle2/> Manager review</span><ArrowRight/><span><Box/> Stock <b>or</b> <ShoppingCart/> purchase</span><ArrowRight/><span><PackageCheck/> Deliver</span><ArrowRight/><span><RotateCcw/> Return</span></section>
  <section className="subproject-summary"><article><small>Waiting for review</small><strong>{summary.submitted}</strong><span>New employee requests</span></article><article><small>Purchase required</small><strong>{summary.purchase}</strong><span>Following procurement</span></article><article><small>Ready to deliver</small><strong>{summary.ready}</strong><span>Asset allocated</span></article><article><small>Currently on loan</small><strong>{summary.onLoan}</strong><span>Assets in employee custody</span></article></section>
  <section className="toolbar-card"><label className="filter-select">Status<select value={filter} onChange={e=>setFilter(e.target.value)}><option>Active</option><option>All</option><option>Submitted</option><option>Awaiting purchase</option><option>Ready for delivery</option><option>On loan</option><option>Returned</option><option>Rejected</option></select></label></section>
  <section className="budget-table-card"><div className="responsive-table"><table><thead><tr><th>Request / employee</th><th>Needed item</th><th>Loan period</th><th>Fulfillment</th><th>Status</th><th/></tr></thead><tbody>{visible.map(x=><tr key={x.id}><td><strong>{x.requesterName}</strong><small>{x.id} · {x.requesterDepartment||x.project}</small></td><td><strong>{x.itemName}</strong><small>{x.assetName||x.purpose}</small></td><td>{x.neededFrom}<small>Return by {x.expectedReturnDate}</small></td><td>{x.fulfillmentSource||"Not decided"}{x.purchaseRequestId&&<small>{x.purchaseRequestId}</small>}</td><td><span className={`rag-badge ${tone(x.status)}`}>{x.status}</span></td><td><button className="text-button" onClick={()=>setSelected(x)}>Open</button></td></tr>)}{!visible.length&&<tr><td className="empty-row" colSpan={6}>No asset loan requests match this status.</td></tr>}</tbody></table></div></section>
  {open&&<div className="modal-layer drawer-layer"><button className="modal-backdrop" onClick={()=>setOpen(false)}/><section className="issue-drawer"><div className="drawer-header"><div><p className="eyebrow">Employee request</p><h2>Request an asset loan</h2></div><button className="modal-close inline" onClick={()=>setOpen(false)}><X/></button></div><div className="drawer-context"><Handshake size={18}/><p>Request the equipment you need. The asset team will check stock first and start a purchase when no suitable asset is available.</p></div><form action={create}><label>Project / cost owner<select name="project" required>{projects.map(p=><option key={p.id}>{p.name}</option>)}</select></label><label>Asset or equipment needed<input name="itemName" required placeholder="e.g. Laptop, camera, testing device"/></label><label>Business purpose<textarea name="purpose" rows={4} required placeholder="Explain why you need it and where it will be used."/></label><div className="form-grid"><label>Needed from<input name="neededFrom" type="date" required/></label><label>Expected return<input name="expectedReturnDate" type="date" required/></label></div><button className="button primary full" disabled={busy}><Handshake size={16}/> Submit loan request</button></form></section></div>}
  {selected&&<div className="modal-layer drawer-layer"><button className="modal-backdrop" onClick={()=>setSelected(null)}/><section className="issue-drawer loan-detail"><div className="drawer-header"><div><p className="eyebrow">{selected.id}</p><h2>{selected.itemName}</h2></div><button className="modal-close inline" onClick={()=>setSelected(null)}><X/></button></div><div className="loan-requester"><span><Handshake/></span><div><strong>{selected.requesterName}</strong><small>{selected.requesterDepartment||selected.project}</small></div><span className={`rag-badge ${tone(selected.status)}`}>{selected.status}</span></div><dl className="loan-details"><div><dt>Purpose</dt><dd>{selected.purpose}</dd></div><div><dt>Loan period</dt><dd>{selected.neededFrom} → {selected.expectedReturnDate}</dd></div><div><dt>Fulfillment</dt><dd>{selected.fulfillmentSource||"Awaiting decision"}</dd></div>{selected.assetId&&<div><dt>Allocated asset</dt><dd><Link href={`/assets/${selected.assetId}`}>{selected.assetName} · {selected.assetId}</Link></dd></div>}{selected.purchaseRequestId&&<div><dt>Purchase request</dt><dd><Link href={`/purchase-requests?open=${selected.purchaseRequestId}`}>{selected.purchaseRequestId}</Link></dd></div>}</dl>
   {canManage&&selected.status==="Submitted"&&<><form action={act} className="loan-action"><h3>Fulfill from stock</h3><input type="hidden" name="action" value="assign_stock"/><label>Available asset<select name="assetId" required><option value="">Choose asset</option>{assets.map(a=><option value={a.id} key={a.id}>{a.name} · {a.id} · {a.location}</option>)}</select></label><label>Review note<input name="note" placeholder="Optional"/></label><button className="button primary full"><Box size={16}/> Allocate stock asset</button></form><form action={act} className="loan-action purchase"><h3>Not in stock? Start purchase</h3><input type="hidden" name="action" value="purchase"/><label>Estimated value (QAR)<input name="amount" type="number" min="1" required/></label><label>Review note<input name="note" placeholder="Why purchasing is required"/></label><button className="button secondary full"><ShoppingCart size={16}/> Create purchase request</button></form><form action={act}><input type="hidden" name="action" value="reject"/><label>Rejection reason<input name="note" required/></label><button className="button danger full"><XCircle size={16}/> Reject request</button></form></>}
   {canManage&&selected.status==="Awaiting purchase"&&<form action={act} className="loan-action"><h3>Purchased asset received</h3><p>Select the newly registered asset when procurement and receiving are complete.</p><input type="hidden" name="action" value="ready"/><label>Registered asset<select name="assetId" required><option value="">Choose asset</option>{assets.map(a=><option value={a.id} key={a.id}>{a.name} · {a.id}</option>)}</select></label><button className="button primary full"><PackageCheck size={16}/> Mark ready for delivery</button></form>}
   {canManage&&selected.status==="Ready for delivery"&&<form action={act} className="loan-action"><input type="hidden" name="action" value="issue"/><label>Handover note<input name="note" placeholder="Accessories, condition, or handover reference"/></label><button className="button primary full"><PackageCheck size={16}/> Confirm delivery to employee</button></form>}
   {canManage&&selected.status==="On loan"&&<form action={act} className="loan-action"><input type="hidden" name="action" value="return"/><label>Condition on return<textarea name="returnCondition" required rows={3} placeholder="Record condition, damage, and missing accessories"/></label><button className="button primary full"><RotateCcw size={16}/> Confirm asset returned</button></form>}
   {selected.requesterUserId===user?.id&&selected.status==="Submitted"&&<form action={act}><input type="hidden" name="action" value="cancel"/><button className="button secondary full">Cancel my request</button></form>}
   <section className="loan-timeline"><h3>Request history</h3>{selected.events?.map(e=><article key={e.id}><i/><div><strong>{e.eventType}</strong><p>{e.note||`${e.fromStatus||"Start"} → ${e.toStatus}`}</p><small>{e.actorName} · {new Date(e.createdAt).toLocaleString()}</small></div></article>)}{!selected.events?.length&&<p>No history recorded yet.</p>}</section>
  </section></div>}
 </main>
}
