"use client";
import { ArrowRight, Building2, FileUp, Filter, Pencil, Plus, ShieldCheck, Trash2, UserRound, UsersRound, UserX, UserCheck, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { UserRecord, UserRole } from "../lib/database";
import * as XLSX from "xlsx";
import { PasswordInput } from "../components/password-input";

const blank={name:"",email:"",role:"VIEWER" as UserRole,department:"",jobTitle:"",phone:"",active:true};
type ProjectOption={id:string;name:string};

export default function UsersPage(){
  const [users,setUsers]=useState<UserRecord[]>([]),[roles,setRoles]=useState<UserRole[]>([]),[projects,setProjects]=useState<ProjectOption[]>([]),[open,setOpen]=useState(false),[editing,setEditing]=useState<UserRecord|null>(null),[error,setError]=useState("");
  const [actorRole,setActorRole]=useState<UserRole|null>(null);
  const [userView,setUserView]=useState<"all"|"active"|"disabled">("all"),[rolesOpen,setRolesOpen]=useState(false);
  const [roleFilter,setRoleFilter]=useState<"all"|UserRole>("all"),[groupByDepartment,setGroupByDepartment]=useState(false);
  const active=useMemo(()=>users.filter(u=>u.active).length,[users]);
  const disabled=useMemo(()=>users.filter(u=>!u.active).length,[users]);
  const visibleUsers=useMemo(()=>userView==="active"?users.filter(u=>u.active):userView==="disabled"?users.filter(u=>!u.active):users,[users,userView]);
  const filteredUsers=useMemo(()=>roleFilter==="all"?visibleUsers:visibleUsers.filter(u=>u.role===roleFilter),[visibleUsers,roleFilter]);
  const userGroups=useMemo(()=>{if(!groupByDepartment)return [{department:"",users:filteredUsers}];const grouped=new Map<string,UserRecord[]>();for(const user of filteredUsers){const department=user.department.trim()||"No department";grouped.set(department,[...(grouped.get(department)||[]),user])}return [...grouped.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([department,departmentUsers])=>({department,users:departmentUsers}))},[filteredUsers,groupByDepartment]);
  const roleSummary=useMemo(()=>Array.from(new Set(users.map(u=>u.role))).map(role=>({role,count:users.filter(u=>u.role===role).length,users:users.filter(u=>u.role===role)})).sort((a,b)=>b.count-a.count),[users]);
  async function refresh(){const r=await fetch("/api/users",{cache:"no-store"});const d=await r.json() as {users:UserRecord[];roles:UserRole[];projects:ProjectOption[];actorRole?:UserRole;error?:string};if(!r.ok)throw new Error(d.error||"Unable to load users");setUsers(d.users||[]);setRoles(d.roles||[]);setProjects(d.projects||[]);setActorRole(d.actorRole||null)}
  useEffect(()=>{refresh().catch(()=>setError("Unable to load users"))},[]);
  function startCreate(){setEditing(null);setError("");setOpen(true)}
  function startEdit(user:UserRecord){setEditing(user);setError("");setOpen(true)}
  async function save(fd:FormData){setError("");const payload={name:String(fd.get("name")),email:String(fd.get("email")),role:String(fd.get("role")),department:String(fd.get("department")),jobTitle:String(fd.get("jobTitle")),phone:String(fd.get("phone")),...(editing?{}:{active:fd.get("active")==="on"}),projectIds:fd.getAll("projectIds").map(String)};const newPassword=String(fd.get("newPassword")||"");if(newPassword&&newPassword.length<8){setError("Password must contain at least 8 characters.");return}if(!["CEO","ADMIN"].includes(payload.role)&&!payload.projectIds.length){setError("Choose at least one project for this position.");return}const r=await fetch(editing?`/api/users/${editing.id}`:"/api/users",{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(!r.ok){const d=await r.json() as {error?:string};setError(d.error||"Unable to save user");return}if(editing&&newPassword){const passwordResponse=await fetch(`/api/users/${editing.id}/password`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({password:newPassword})});if(!passwordResponse.ok){const d=await passwordResponse.json() as {error?:string};setError(d.error||"Unable to set new password");return}}await refresh();setOpen(false)}
  async function remove(user:UserRecord){if(!window.confirm(`Delete ${user.name}?`))return;const r=await fetch(`/api/users/${user.id}`,{method:"DELETE"});if(r.ok)await refresh()}
  async function setStatus(user:UserRecord){setError("");const action=user.active?"deactivate":"activate";if(!window.confirm(`${action[0].toUpperCase()+action.slice(1)} ${user.name}?`))return;const r=await fetch(`/api/users/${user.id}/status`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({active:!user.active})});const d=await r.json().catch(()=>({})) as {error?:string};if(!r.ok){setError(d.error||`Unable to ${action} user`);return}await refresh()}
  async function importContacts(file:File){setError("");try{const workbook=XLSX.read(await file.arrayBuffer(),{type:"array"}),sheet=workbook.Sheets[workbook.SheetNames[0]],rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:""});const r=await fetch("/api/users/import",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({rows})});const d=await r.json() as {created?:number;updated?:number;skipped?:number;error?:string};if(!r.ok)throw new Error(d.error||"Import failed");await refresh();window.alert(`Import complete: ${d.created||0} created, ${d.updated||0} updated, ${d.skipped||0} skipped.`)}catch(e){setError(e instanceof Error?e.message:"Unable to import contacts")}}
  const initial=editing?{name:editing.name,email:editing.email,role:editing.role,department:editing.department,jobTitle:editing.jobTitle,phone:editing.phone,active:editing.active}:blank;
  return <main className="dashboard-main section-page"><section className="page-heading"><div><p className="eyebrow">Access foundation</p><h1>User Management</h1><p className="page-subtitle">Accounts are matched to the signed-in Supabase Auth email, then SmartCare roles and project permissions decide access.</p></div><div className="table-actions"><label className="button secondary file-button"><FileUp size={18}/> Import Google / Excel<input type="file" hidden accept=".csv,.xlsx,.xls,text/csv" onChange={e=>{const f=e.target.files?.[0];if(f)importContacts(f);e.currentTarget.value=""}}/></label><button className="button primary" onClick={startCreate}><Plus size={18}/> Add user</button></div></section>
  <section className="finance-kpis compact user-summary-kpis">
    <button type="button" className={`user-summary-card ${userView==="all"&&!rolesOpen?"selected":""}`} onClick={()=>{setUserView("all");setRolesOpen(false)}} aria-pressed={userView==="all"&&!rolesOpen}>
      <span className="finance-icon blue"><UsersRound size={22}/></span><div><small>Total users</small><strong>{users.length}</strong><span>View all company users</span></div><ArrowRight className="summary-card-arrow" size={18}/>
    </button>
    <button type="button" className={`user-summary-card ${userView==="active"&&!rolesOpen?"selected":""}`} onClick={()=>{setUserView("active");setRolesOpen(false)}} aria-pressed={userView==="active"&&!rolesOpen}>
      <span className="finance-icon teal"><UserRound size={22}/></span><div><small>Active users</small><strong>{active}</strong><span>View active users</span></div><ArrowRight className="summary-card-arrow" size={18}/>
    </button>
    <button type="button" className={`user-summary-card ${userView==="disabled"&&!rolesOpen?"selected":""}`} onClick={()=>{setUserView("disabled");setRolesOpen(false)}} aria-pressed={userView==="disabled"&&!rolesOpen}>
      <span className="finance-icon coral"><UserX size={22}/></span><div><small>Disabled users</small><strong>{disabled}</strong><span>View disabled users</span></div><ArrowRight className="summary-card-arrow" size={18}/>
    </button>
    <button type="button" className={`user-summary-card ${rolesOpen?"selected":""}`} onClick={()=>setRolesOpen(true)} aria-expanded={rolesOpen}>
      <span className="finance-icon amber"><ShieldCheck size={22}/></span><div><small>Roles configured</small><strong>{roleSummary.length}</strong><span>View roles and users</span></div><ArrowRight className="summary-card-arrow" size={18}/>
    </button>
  </section>
  <section className="budget-table-card"><div className="panel-heading"><div><h2>{userView==="active"?"Active users":userView==="disabled"?"Disabled users":"Company users"}</h2><p>{filteredUsers.length} {filteredUsers.length===1?"user":"users"} shown{roleFilter!=="all"?` with the ${roleFilter.replaceAll("_"," ")} role`:""}.</p></div><div className="users-table-controls"><label className="filter-select"><Filter size={15}/><select value={roleFilter} onChange={event=>setRoleFilter(event.target.value as "all"|UserRole)} aria-label="Filter users by role"><option value="all">All roles</option>{roles.map(role=><option key={role} value={role}>{role.replaceAll("_"," ")}</option>)}</select></label><button type="button" className={`button secondary ${groupByDepartment?"active":""}`} onClick={()=>setGroupByDepartment(value=>!value)} aria-pressed={groupByDepartment}><Building2 size={16}/> {groupByDepartment?"Grouped by department":"Group by department"}</button>{userView!=="all"&&<button className="text-button" onClick={()=>setUserView("all")}>Show all users</button>}</div></div><div className="responsive-table"><table><thead><tr><th>User</th><th>Position</th><th>Projects</th><th>Contact</th><th>Department</th><th>Status</th><th>Actions</th></tr></thead><tbody>{userGroups.flatMap(group=>[...(groupByDepartment?[<tr className="department-group-row" key={`department-${group.department}`}><td colSpan={7}><Building2 size={15}/><strong>{group.department}</strong><span>{group.users.length} {group.users.length===1?"user":"users"}</span></td></tr>]:[]),...group.users.map(u=><tr key={u.id}><td><strong>{u.name}</strong><small>{u.email}</small></td><td><span className="table-status healthy">{u.role.replaceAll("_"," ")}</span><small>{u.jobTitle||"—"}</small></td><td>{u.projectNames.length?u.projectNames.join(", "):["CEO","ADMIN"].includes(u.role)?"All projects":"No project assigned"}</td><td>{u.phone||"—"}</td><td>{u.department||"—"}</td><td><span className={`table-status ${u.active?"healthy":"warning"}`}>{u.active?"Active":"Disabled"}</span></td><td><div className="user-actions"><button className="text-button" onClick={()=>startEdit(u)}><Pencil size={15}/> Edit</button><button className={`text-button ${u.active?"danger-text":""}`} onClick={()=>setStatus(u)}>{u.active?<><UserX size={15}/> Deactivate</>:<><UserCheck size={15}/> Activate</>}</button><button className="text-button danger-text" onClick={()=>remove(u)}><Trash2 size={15}/> Delete</button></div></td></tr>)])}{!filteredUsers.length&&<tr><td colSpan={7} className="empty-row">No users match the selected filters.</td></tr>}</tbody></table></div></section>

  {rolesOpen&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setRolesOpen(false)} aria-label="Close roles overview"/><section className="roles-overview-modal" role="dialog" aria-modal="true" aria-labelledby="roles-overview-title"><div className="drawer-header"><div><p className="eyebrow">Access overview</p><h2 id="roles-overview-title">Configured roles</h2><p className="roles-overview-subtitle">See how company users are distributed across SmartCare roles.</p></div><button className="modal-close inline" onClick={()=>setRolesOpen(false)} aria-label="Close"><X/></button></div><div className="roles-overview-list">{roleSummary.map(item=><article key={item.role} className="role-summary-row"><div><strong>{item.role.replaceAll("_"," ")}</strong><small>{item.count} {item.count===1?"user":"users"}</small></div><div className="role-user-chips">{item.users.slice(0,4).map(user=><span key={user.id}>{user.name}</span>)}{item.users.length>4&&<span>+{item.users.length-4}</span>}</div><button type="button" className="text-button" onClick={()=>{setRolesOpen(false);setUserView("all")}}>View users</button></article>)}</div></section></div>}
  {open&&<div className="modal-layer drawer-layer"><button className="modal-backdrop" onClick={()=>setOpen(false)}/><section className="issue-drawer"><div className="drawer-header"><div><p className="eyebrow">{editing?"Update access":"New account"}</p><h2>{editing?"Edit user":"Add user"}</h2></div><button className="modal-close inline" onClick={()=>setOpen(false)}><X/></button></div><form action={save}><label>Full name<input name="name" required defaultValue={initial.name}/></label><label>Login email<input name="email" type="email" required defaultValue={initial.email}/>{editing&&<small>Changing this also changes the Supabase Auth login identity and requires server Auth-admin configuration.</small>}</label>{editing&&actorRole==="ADMIN"&&<label>Set new password<PasswordInput name="newPassword" minLength={8} autoComplete="new-password" placeholder="Leave blank to keep current password"/><small>At least 8 characters. The user can sign in with this password immediately.</small></label>}<label>Contact number<input name="phone" type="tel" defaultValue={initial.phone} placeholder="+974 ..."/></label><div className="form-grid"><label>Position / Role<select name="role" defaultValue={initial.role}>{roles.map(r=><option key={r} value={r}>{r.replaceAll("_"," ")}</option>)}</select></label><label>Department<input name="department" defaultValue={initial.department}/></label></div><label>Job title<input name="jobTitle" defaultValue={initial.jobTitle}/></label><fieldset className="project-assignment"><legend>Assigned projects</legend><p>CEO and Admin automatically access every project. All other positions require at least one selection.</p>{projects.map(project=><label className="check-filter" key={project.id}><input name="projectIds" value={project.id} type="checkbox" defaultChecked={editing?.projectIds.includes(project.id)}/>{project.name}</label>)}</fieldset>{!editing&&<label className="check-filter"><input name="active" type="checkbox" defaultChecked/> Activate account after invitation</label>}{error&&<p className="form-error">{error}</p>}<button className="button primary full">{editing?"Save changes":"Create user"}</button></form></section></div>}</main>
}
