"use client";
import { FileUp, Pencil, Plus, ShieldCheck, Trash2, UserRound, UsersRound, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { UserRecord, UserRole } from "../lib/database";
import * as XLSX from "xlsx";

const blank={name:"",email:"",role:"VIEWER" as UserRole,department:"",jobTitle:"",phone:"",active:true};
type ProjectOption={id:string;name:string};

export default function UsersPage(){
  const [users,setUsers]=useState<UserRecord[]>([]),[roles,setRoles]=useState<UserRole[]>([]),[projects,setProjects]=useState<ProjectOption[]>([]),[open,setOpen]=useState(false),[editing,setEditing]=useState<UserRecord|null>(null),[error,setError]=useState("");
  const active=useMemo(()=>users.filter(u=>u.active).length,[users]);
  async function refresh(){const r=await fetch("/api/users",{cache:"no-store"});const d=await r.json() as {users:UserRecord[];roles:UserRole[];projects:ProjectOption[];error?:string};if(!r.ok)throw new Error(d.error||"Unable to load users");setUsers(d.users||[]);setRoles(d.roles||[]);setProjects(d.projects||[])}
  useEffect(()=>{refresh().catch(()=>setError("Unable to load users"))},[]);
  function startCreate(){setEditing(null);setError("");setOpen(true)}
  function startEdit(user:UserRecord){setEditing(user);setError("");setOpen(true)}
  async function save(fd:FormData){setError("");const payload={name:String(fd.get("name")),email:String(fd.get("email")),role:String(fd.get("role")),department:String(fd.get("department")),jobTitle:String(fd.get("jobTitle")),phone:String(fd.get("phone")),active:fd.get("active")==="on",projectIds:fd.getAll("projectIds").map(String)};if(!["CEO","ADMIN"].includes(payload.role)&&!payload.projectIds.length){setError("Choose at least one project for this position.");return}const r=await fetch(editing?`/api/users/${editing.id}`:"/api/users",{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(!r.ok){const d=await r.json() as {error?:string};setError(d.error||"Unable to save user");return}await refresh();setOpen(false)}
  async function remove(user:UserRecord){if(!window.confirm(`Delete ${user.name}?`))return;const r=await fetch(`/api/users/${user.id}`,{method:"DELETE"});if(r.ok)await refresh()}
  async function importContacts(file:File){setError("");try{const workbook=XLSX.read(await file.arrayBuffer(),{type:"array"}),sheet=workbook.Sheets[workbook.SheetNames[0]],rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:""});const r=await fetch("/api/users/import",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({rows})});const d=await r.json() as {created?:number;updated?:number;skipped?:number;error?:string};if(!r.ok)throw new Error(d.error||"Import failed");await refresh();window.alert(`Import complete: ${d.created||0} created, ${d.updated||0} updated, ${d.skipped||0} skipped.`)}catch(e){setError(e instanceof Error?e.message:"Unable to import contacts")}}
  const initial=editing?{name:editing.name,email:editing.email,role:editing.role,department:editing.department,jobTitle:editing.jobTitle,phone:editing.phone,active:editing.active}:blank;
  return <main className="dashboard-main section-page"><section className="page-heading"><div><p className="eyebrow">Access foundation</p><h1>User Management</h1><p className="page-subtitle">Accounts are matched to the signed-in Supabase Auth email, then SmartCare roles and project permissions decide access.</p></div><div className="table-actions"><label className="button secondary file-button"><FileUp size={18}/> Import Google / Excel<input type="file" hidden accept=".csv,.xlsx,.xls,text/csv" onChange={e=>{const f=e.target.files?.[0];if(f)importContacts(f);e.currentTarget.value=""}}/></label><button className="button primary" onClick={startCreate}><Plus size={18}/> Add user</button></div></section>
  <section className="finance-kpis compact"><article><span className="finance-icon blue"><UsersRound size={22}/></span><div><small>Total users</small><strong>{users.length}</strong></div></article><article><span className="finance-icon teal"><UserRound size={22}/></span><div><small>Active users</small><strong>{active}</strong></div></article><article><span className="finance-icon amber"><ShieldCheck size={22}/></span><div><small>Roles configured</small><strong>{new Set(users.map(u=>u.role)).size}</strong></div></article></section>
  <section className="budget-table-card"><div className="panel-heading"><div><h2>Company users</h2><p>Each position is limited by both module permissions and assigned projects.</p></div></div><div className="responsive-table"><table><thead><tr><th>User</th><th>Position</th><th>Projects</th><th>Contact</th><th>Department</th><th>Status</th><th>Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.name}</strong><small>{u.email}</small></td><td><span className="table-status healthy">{u.role.replaceAll("_"," ")}</span><small>{u.jobTitle||"—"}</small></td><td>{u.projectNames.length?u.projectNames.join(", "):["CEO","ADMIN"].includes(u.role)?"All projects":"No project assigned"}</td><td>{u.phone||"—"}</td><td>{u.department||"—"}</td><td>{u.active?"Active":"Disabled"}</td><td><div className="user-actions"><button className="text-button" onClick={()=>startEdit(u)}><Pencil size={15}/> Edit</button><button className="text-button danger-text" onClick={()=>remove(u)}><Trash2 size={15}/> Delete</button></div></td></tr>)}</tbody></table></div></section>
  {open&&<div className="modal-layer drawer-layer"><button className="modal-backdrop" onClick={()=>setOpen(false)}/><section className="issue-drawer"><div className="drawer-header"><div><p className="eyebrow">{editing?"Update access":"New account"}</p><h2>{editing?"Edit user":"Add user"}</h2></div><button className="modal-close inline" onClick={()=>setOpen(false)}><X/></button></div><form action={save}><label>Full name<input name="name" required defaultValue={initial.name}/></label><label>Email<input name="email" type="email" required defaultValue={initial.email}/></label><label>Contact number<input name="phone" type="tel" defaultValue={initial.phone} placeholder="+974 ..."/></label><div className="form-grid"><label>Position / Role<select name="role" defaultValue={initial.role}>{roles.map(r=><option key={r} value={r}>{r.replaceAll("_"," ")}</option>)}</select></label><label>Department<input name="department" defaultValue={initial.department}/></label></div><label>Job title<input name="jobTitle" defaultValue={initial.jobTitle}/></label><fieldset className="project-assignment"><legend>Assigned projects</legend><p>CEO and Admin automatically access every project. All other positions require at least one selection.</p>{projects.map(project=><label className="check-filter" key={project.id}><input name="projectIds" value={project.id} type="checkbox" defaultChecked={editing?.projectIds.includes(project.id)}/>{project.name}</label>)}</fieldset><label className="check-filter"><input name="active" type="checkbox" defaultChecked={initial.active}/> Active user</label>{error&&<p className="form-error">{error}</p>}<button className="button primary full">{editing?"Save changes":"Create user"}</button></form></section></div>}</main>
}
