import { findAsset } from "../../lib/database";
import { createClient } from "../../lib/supabase/server";

type Cause = { cause:string; probability:number; why:string; solution:string };
type Diagnosis = { title:string; urgency:"Low"|"Medium"|"High"; confidence:number; possibleCauses:Cause[]; checks:string[]; safety:string; recommendedAction:string; parts:string[]; sourceLabel:string; sourceUrl:string; mode?:string };
const safety = "Do not bypass guards, interlocks or emergency systems. Isolate energy before inspection and escalate any laser, CNC, electrical, fume-extraction or fire-risk condition to a qualified technician.";

function ruleFallback(name:string, model:string, symptom:string):Diagnosis {
 const s=symptom.toLowerCase(); const laser=/laser|bolt|co₂|co2/.test(`${name} ${model}`.toLowerCase()); const cnc=/cnc|sr20|spindle/.test(`${name} ${model}`.toLowerCase()); const printer=/bambu|printer|3d/.test(`${name} ${model}`.toLowerCase());
 const causes:Cause[] = laser&&/smoke|exhaust|fume|airflow/.test(s)?[{cause:"Restricted exhaust path or dirty fan",probability:55,why:"The symptom points to reduced extraction.",solution:"Stop processing; inspect and clean only approved service points."},{cause:"Loose or damaged duct connection",probability:30,why:"Air leaks reduce measured airflow.",solution:"Inspect ducting and clamps; replace only confirmed damaged parts."},{cause:"Airflow sensor or baseline issue",probability:15,why:"A sensor can alert despite normal mechanical flow.",solution:"Compare with the commissioned baseline after safe airflow verification."}]:cnc?[{cause:"Tool, collet or workholding condition",probability:45,why:"These are common causes of vibration or poor cutting results.",solution:"Lock out; inspect, clean and verify correct clamping."},{cause:"Motion, limit-switch or cable condition",probability:35,why:"Axis symptoms commonly involve motion hardware or wiring.",solution:"Inspect with power isolated and record controller messages."},{cause:"Parameters or material setup",probability:20,why:"The job setup can mimic mechanical defects.",solution:"Run a low-risk dry test after inspection."}]:printer?[{cause:"Nozzle or filament-path restriction",probability:50,why:"Inconsistent extrusion commonly starts in the feed path.",solution:"Allow cooling; inspect and clean using the model manual."},{cause:"Filament condition or calibration",probability:30,why:"Moisture and calibration cause repeatable quality changes.",solution:"Use known-good material and run approved calibration."},{cause:"Connection or configuration issue",probability:20,why:"Network and profile settings can affect monitoring or job start.",solution:"Verify local settings without weakening network security."}]:[{cause:"Operating condition or consumable",probability:45,why:"The symptom is not yet specific enough to isolate a part.",solution:"Record the exact error, recent changes and operating condition."},{cause:"Connection or configuration issue",probability:30,why:"Power, cabling and configuration faults are common first checks.",solution:"Inspect external connections and manufacturer settings."},{cause:"Mechanical component requiring inspection",probability:25,why:"Wear or obstruction needs physical confirmation.",solution:"Create a technician work order with photos and a short video."}];
 return {title:`${name} · ${model} assessment`,urgency:laser||cnc?"High":"Medium",confidence:68,possibleCauses:causes,checks:["Stop the current task safely and record any error code.","Check external power, cables, environment and visible obstructions.","Use the exact manufacturer manual before opening covers or replacing parts.","Attach photos/video and service history to the work order."],safety,recommendedAction:"Use the ranked checks to confirm the fault, then create a work order for any repair or part replacement.",parts:["No part should be issued until the inspection confirms the failed component"],sourceLabel:"AI-ready fallback — add OPENAI_API_KEY to enable live AI",sourceUrl:"",mode:"Safe rules fallback"};
}

async function liveDiagnosis(apiKey:string, input:{name:string;model:string;symptom:string;assetContext:string;imageDataUrl?:string}):Promise<Diagnosis>{
 const schema={type:"object",additionalProperties:false,required:["title","urgency","confidence","possibleCauses","checks","safety","recommendedAction","parts"],properties:{title:{type:"string"},urgency:{type:"string",enum:["Low","Medium","High"]},confidence:{type:"integer",minimum:0,maximum:100},possibleCauses:{type:"array",minItems:2,maxItems:4,items:{type:"object",additionalProperties:false,required:["cause","probability","why","solution"],properties:{cause:{type:"string"},probability:{type:"integer",minimum:0,maximum:100},why:{type:"string"},solution:{type:"string"}}}},checks:{type:"array",items:{type:"string"}},safety:{type:"string"},recommendedAction:{type:"string"},parts:{type:"array",items:{type:"string"}}}};
 const instructions=`You are Ibtechar SmartCare's technical maintenance diagnostic assistant. Analyze the equipment name, exact model, observed symptom, asset context and attached photo when supplied. First identify only what is visibly supported by the image; distinguish visible evidence from inference. Reply in clear Arabic. Give 2-4 ranked probable causes; probabilities total 100. Treat them as diagnostic likelihoods, not certainty. State safe checks and a solution for each cause. Never infer hidden internal damage from a photo alone, invent manufacturer procedures, or claim a part is definitely failed. Never advise bypassing guards, interlocks, emergency stops, laser enclosures, or electrical protection. For CNC, laser, electrical, extraction, fire or injury risk: stop use and escalate to a qualified technician. Do not instruct opening powered equipment.`;
 const content:Array<Record<string,unknown>>=[{type:"input_text",text:`Equipment name: ${input.name}\nModel: ${input.model}\nObserved symptom: ${input.symptom||"No written symptom; analyze the image carefully."}\nAsset context: ${input.assetContext}`}];if(input.imageDataUrl)content.push({type:"input_image",image_url:input.imageDataUrl,detail:"high"});
 const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-5.4-nano",instructions,input:[{role:"user",content}],text:{format:{type:"json_schema",name:"equipment_diagnosis",strict:true,schema}}})});
 if(!response.ok) throw new Error("AI service unavailable"); const data=await response.json() as {output_text?:string}; if(!data.output_text) throw new Error("AI returned no diagnostic"); const parsed=JSON.parse(data.output_text) as Omit<Diagnosis,"sourceLabel"|"sourceUrl"|"mode">;
 return {...parsed,sourceLabel:"AI diagnostic — verify against the manufacturer manual",sourceUrl:"",mode:"Live AI"};
}

export async function POST(request:Request){try{const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return Response.json({error:"Unauthorized"},{status:401});const p=await request.json() as {assetId?:string;equipmentName?:string;equipmentModel?:string;symptom?:string;imageDataUrl?:string;imagePath?:string};const selected=p.assetId?await findAsset(p.assetId):undefined;const name=(p.equipmentName?.trim()||selected?.name||"");const model=(p.equipmentModel?.trim()||selected?.model||"");const symptom=p.symptom?.trim()||"";if(!name||!model||(!symptom&&!p.imageDataUrl))return Response.json({error:"Equipment name, model and a symptom or image are required"},{status:400});const assetContext=selected?`${selected.id}; ${selected.category}; ${selected.status}; location ${selected.location}; project ${selected.project}; health ${selected.health}%`:"No registered asset selected.";const apiKey=process.env.OPENAI_API_KEY;const diagnosis=apiKey?await liveDiagnosis(apiKey,{name,model,symptom,assetContext,imageDataUrl:p.imageDataUrl}):ruleFallback(name,model,symptom||"Image supplied");if(!apiKey&&p.imageDataUrl){diagnosis.sourceLabel="Photo saved — live visual analysis starts after OPENAI_API_KEY is configured"}const {data:session,error:sessionError}=await supabase.from("diagnostic_sessions").insert({asset_id:selected?.id||null,equipment_name:name,model,observed_symptom:symptom||"Image-only diagnostic",image_path:p.imagePath||null,result_json:diagnosis,created_by:user.id}).select("id").single();if(sessionError)throw new Error(sessionError.message);return Response.json({diagnosis,diagnosticSessionId:session.id,generatedAt:new Date().toISOString()});}catch(error){return Response.json({error:error instanceof Error?error.message:"Unable to analyze the symptom"},{status:500});}}
