"use client";

import { AlertTriangle, CheckCircle2, ExternalLink, ImageIcon, LoaderCircle, PackageSearch, ShieldCheck, Sparkles, UploadCloud, Wrench, X } from "lucide-react";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import type { AssetRecord } from "../lib/demo-data";

type Cause = { cause:string; probability:number; why:string; solution:string };
type Diagnosis = { title:string; urgency:string; confidence:number; possibleCauses:Cause[]; checks:string[]; safety:string; recommendedAction:string; parts:string[]; sourceLabel:string; sourceUrl:string; mode?:string };

const samples:Record<string,string[]>={"3DP-00123":["Print quality is rough and extrusion looks inconsistent","Printer is offline and Bambu Studio cannot see it"],"CNC-00078":["Spindle makes more noise and vibration increased","X axis stops during homing"],"LAS-00055":["Exhaust airflow is weak and smoke clears slowly","Engraving power is weaker and the result is inconsistent"],"FUR-IBT-004":["Workbench caster is loose and the surface is unstable","Damage found during the condition inspection"],"ST5-3DP-011":["Print quality is inconsistent and the machine needs assessment","Material is not feeding correctly"],"ST5-LAS-021":["Cutting is inconsistent and optics may need inspection","Exhaust extraction seems weaker than normal"]};

export default function AiAssistantPage(){
  const router=useRouter();
  const [assets,setAssets]=useState<AssetRecord[]>([]);const [assetId,setAssetId]=useState("");const [equipmentName,setEquipmentName]=useState("");const [equipmentModel,setEquipmentModel]=useState("");const [symptom,setSymptom]=useState("");const [imageData,setImageData]=useState("");const [imagePath,setImagePath]=useState("");const [uploading,setUploading]=useState(false);const [result,setResult]=useState<Diagnosis|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [diagnosticSessionId,setDiagnosticSessionId]=useState<number|null>(null);
  useEffect(()=>{fetch("/api/assets").then(async response=>{if(!response.ok)throw new Error("Unable to load registered assets");return response.json()}).then((data:{assets:AssetRecord[]})=>{const rows=data.assets||[];setAssets(rows);const requested=new URLSearchParams(window.location.search).get("asset");const asset=rows.find(a=>a.id===requested);if(asset){setAssetId(asset.id);setEquipmentName(asset.name);setEquipmentModel(asset.model);setSymptom(samples[asset.id]?.[0]??"")}}).catch(()=>setAssets([]))},[]);
  async function attach(file?:File){if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)){setError("Please upload a JPG, PNG or WebP image.");return}if(file.size>4*1024*1024){setError("Image must be smaller than 4 MB.");return}setUploading(true);setError("");try{const body=new FormData();body.set("file",file);body.set("bucket","diagnostic-images");const response=await fetch("/api/storage/upload",{method:"POST",body});const data=await response.json() as {path?:string;signedUrl?:string;error?:string};if(!response.ok||!data.path||!data.signedUrl)throw new Error(data.error||"Image upload failed");setImagePath(data.path);setImageData(data.signedUrl)}catch(e){setError(e instanceof Error?e.message:"Image upload failed")}finally{setUploading(false)}}
  async function analyze(){setLoading(true);setError("");setResult(null);try{const response=await fetch("/api/diagnose",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({assetId,equipmentName,equipmentModel,symptom,imageDataUrl:imageData,imagePath})});const data=await response.json() as {diagnosis?:Diagnosis;diagnosticSessionId?:number;error?:string};if(!response.ok||!data.diagnosis)throw new Error(data.error||"Unable to analyze this symptom.");setResult(data.diagnosis);setDiagnosticSessionId(data.diagnosticSessionId||null)}catch(e){setError(e instanceof Error?e.message:"Unable to analyze") }finally{setLoading(false)}}
  return <main className="dashboard-main section-page"><section className="page-heading"><div><p className="eyebrow">Technical decision support</p><h1>AI Diagnostic Assistant</h1><p className="page-subtitle">Type the equipment name, model and observed symptom. The bot ranks likely causes and safe solutions for the technician.</p></div><span className="pilot-badge"><Sparkles size={16}/> AI diagnostic mode</span></section>
    <section className="assistant-layout"><article className="diagnostic-form-card"><div className="assistant-header"><span><Sparkles size={24}/></span><div><h2>Describe the equipment problem</h2><p>Use the exact symptom, error code and add a clear photo of the equipment, damaged part or display.</p></div></div><label>Registered asset (optional)<select value={assetId} onChange={e=>{const id=e.target.value;const asset=assets.find(a=>a.id===id);setAssetId(id);if(asset){setEquipmentName(asset.name);setEquipmentModel(asset.model)}setSymptom(samples[id]?.[0]??"");setResult(null)}}><option value="">Custom equipment — type details below</option>{assets.map(a=><option value={a.id} key={a.id}>{a.name} · {a.id}</option>)}</select></label><div className="form-grid"><label>Equipment name<input value={equipmentName} onChange={e=>setEquipmentName(e.target.value)} placeholder="Example: Bambu Lab 3D Printer"/></label><label>Model<input value={equipmentModel} onChange={e=>setEquipmentModel(e.target.value)} placeholder="Example: X1 Carbon"/></label></div><label>Observed symptom<textarea rows={6} value={symptom} onChange={e=>setSymptom(e.target.value)} placeholder="Example: powers on, but extrusion is inconsistent and I hear clicking from the feeder…"/></label><label className="vision-upload"><input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={e=>attach(e.target.files?.[0])}/>{imageData?<span className="vision-preview"><img src={imageData} alt="Equipment issue preview"/><button type="button" onClick={()=>{setImageData("");setImagePath("")}} aria-label="Remove image"><X size={16}/></button><strong>Photo securely uploaded for AI vision</strong></span>:<span>{uploading?<LoaderCircle className="spin" size={25}/>:<UploadCloud size={25}/>}<strong>{uploading?"Uploading photo…":"Upload equipment / problem photo"}</strong><small>JPG, PNG or WebP · maximum 4 MB</small></span>}</label><div className="sample-prompts"><span>Try an example:</span>{(samples[assetId]??[]).map(text=><button type="button" key={text} onClick={()=>setSymptom(text)}>{text}</button>)}</div><button className="button primary full diagnose-button" type="button" onClick={analyze} disabled={!equipmentName.trim()||!equipmentModel.trim()||(!symptom.trim()&&!imageData)||loading||uploading}>{loading?<><LoaderCircle className="spin" size={18}/>Analyzing text and image…</>:<><ImageIcon size={18}/>Analyze with AI Vision</>}</button>{error&&<p className="form-error">{error}</p>}<div className="assistant-scope"><ShieldCheck size={18}/><p><strong>Safe diagnostic scope</strong><span>A photo supports visual assessment but does not replace physical inspection. Never bypass guards, interlocks or emergency systems.</span></p></div></article>
      <div className="diagnosis-area">{!result&&!loading&&<article className="assistant-empty"><Sparkles size={38}/><h2>Ready for a symptom</h2><p>Enter the equipment name, model and what you see. The assistant will rank probable causes with a confidence percentage, safe checks, likely parts and the recommended solution.</p><div><span><CheckCircle2/>Model context</span><span><CheckCircle2/>Service history</span><span><CheckCircle2/>Safety gate</span></div></article>}{loading&&<article className="assistant-loading"><LoaderCircle className="spin" size={36}/><h2>Building the diagnostic path</h2><p>Comparing the symptom with the model and its maintenance context.</p></article>}{result&&<div className="diagnosis-result"><article className="diagnosis-summary"><div><span className={`urgency ${result.urgency.toLowerCase()}`}>{result.urgency} priority</span><small>{result.confidence}% diagnostic confidence · {result.mode??"AI"}</small></div><h2>{result.title}</h2><div className="confidence-bar"><i style={{width:`${result.confidence}%`}}/></div></article><div className="diagnosis-grid"><article><div className="diagnosis-card-title"><AlertTriangle/><h3>Probable causes & solutions</h3></div><ol>{result.possibleCauses.map(item=><li key={item.cause}><strong>{item.probability}% · {item.cause}</strong><span>{item.why}</span><em>Solution: {item.solution}</em></li>)}</ol></article><article><div className="diagnosis-card-title"><Wrench/><h3>Safe diagnostic sequence</h3></div><ol className="numbered">{result.checks.map(item=><li key={item}>{item}</li>)}</ol></article></div><article className="safety-result"><ShieldCheck/><div><h3>Safety gate</h3><p>{result.safety}</p></div></article><div className="diagnosis-grid"><article><div className="diagnosis-card-title"><CheckCircle2/><h3>Recommended action</h3></div><p>{result.recommendedAction}</p><button className="button primary" type="button" disabled={!assetId} onClick={()=>{if(!assetId)return;const priority=result.urgency==="High"?"High":result.urgency==="Low"?"Normal":"High";const title=`Inspect ${symptom.slice(0,55) || equipmentName}`;const description=`Observed symptom: ${symptom}\n\nAI recommended action: ${result.recommendedAction}`;const q=new URLSearchParams({new:"1",asset:assetId,title,description,priority,diagnosticSessionId:String(diagnosticSessionId||"")});router.push(`/work-orders?${q.toString()}`)}}>Create work order</button></article><article><div className="diagnosis-card-title"><PackageSearch/><h3>Parts prediction</h3></div><ul>{result.parts.map(item=><li key={item}>{item}</li>)}</ul>{result.sourceUrl?<a className="source-link" href={result.sourceUrl} target="_blank" rel="noreferrer">{result.sourceLabel}<ExternalLink size={14}/></a>:<span className="source-link muted">{result.sourceLabel}</span>}</article></div></div>}</div>
    </section>
  </main>;
}

