import { Activity, Bot, Cable, CheckCircle2, Cloud, Cpu, Drill, Gauge, Mail, MessageSquare, Network, Printer, Radiation, RadioTower, ShieldCheck, Sparkles, Thermometer, Users, Wind } from "lucide-react";

const deviceKits=[
  {name:"Bambu Lab 3D Printer",icon:Printer,color:"teal",sources:["LAN status and approved printer telemetry","Non-invasive power monitoring","Ambient temperature and humidity"],triggers:["Repeated offline events","Abnormal idle or job power profile","Maintenance forecast by usage"]},
  {name:"Monolab SR20 CNC",icon:Drill,color:"amber",sources:["Spindle vibration sensor","Spindle surface temperature","Three-phase / VFD power monitoring","Dust-extraction run signal"],triggers:["Vibration above commissioned baseline","Temperature rise at comparable load","Lubrication hours reached","Extraction not running with spindle"]},
  {name:"Thunder Laser Bolt",icon:Radiation,color:"coral",sources:["Exhaust airflow proxy","Enclosure temperature","Air-assist pressure where supported","Power and operating-hour monitoring"],triggers:["Airflow below safe commissioned threshold","Repeated temperature warning","Optics inspection due","Abnormal power-to-output trend"]},
];

export default function IntegrationsPage(){return <main className="dashboard-main section-page"><section className="page-heading"><div><p className="eyebrow">Edge & IoT architecture</p><h1>Machine Monitoring Integrations</h1><p className="page-subtitle">A practical, non-invasive hardware layer that turns the three machines into maintainable connected assets.</p></div><button className="button primary" type="button"><RadioTower size={18}/> Start commissioning</button></section>
  <section className="business-integrations"><article><span className="google"><Mail/></span><div><small>Email & identity</small><h2>Google Workspace</h2><p>Company users, Gmail notifications, Drive manuals and Sheets exports.</p></div><button>Configure</button></article><article><span className="teams"><Users/></span><div><small>Collaboration</small><h2>Microsoft Teams</h2><p>Maintenance alerts, approvals and technician team channels.</p></div><button>Configure</button></article><article><span className="claude"><Bot/></span><div><small>AI provider</small><h2>Claude AI</h2><p>Optional secondary review for reports and technical documents.</p></div><button>Configure</button></article><article><span className="chatgpt"><Sparkles/></span><div><small>AI diagnostics</small><h2>ChatGPT / OpenAI</h2><p>Text and image diagnosis, structured causes and safe solutions.</p></div><button>Configure</button></article></section>
  <section className="architecture-flow"><article><span><Activity/></span><h3>Machine & sensors</h3><p>Power, temperature, vibration, airflow and approved network status.</p></article><i/><article><span><Cpu/></span><h3>Edge gateway</h3><p>Local collection, buffering and rules even if internet is unavailable.</p></article><i/><article><span><Cloud/></span><h3>SmartCare platform</h3><p>Asset records, alerts, work orders, trends and reports.</p></article></section>
  <section className="integration-kits">{deviceKits.map(({name,icon:Icon,color,sources,triggers})=><article className="integration-card" key={name}><div className="integration-card-head"><span className={color}><Icon size={27}/></span><div><small>Pilot integration kit</small><h2>{name}</h2></div></div><div className="integration-columns"><div><h3><Cable size={16}/>Data sources</h3><ul>{sources.map(x=><li key={x}><CheckCircle2/>{x}</li>)}</ul></div><div><h3><Gauge size={16}/>Maintenance triggers</h3><ul>{triggers.map(x=><li key={x}><CheckCircle2/>{x}</li>)}</ul></div></div></article>)}</section>
  <section className="integration-bottom"><article className="detail-section"><div className="section-title"><h2>Recommended pilot hardware</h2><span>One lab · three machines</span></div><div className="hardware-list">{[[Network,"Industrial edge gateway","Ethernet + Wi-Fi, local buffering, secure outbound connection","1"],[Activity,"Spindle vibration sensor","Industrial accelerometer with magnetic or approved fixed mount","1"],[Thermometer,"Temperature & humidity sensors","Printer environment, CNC spindle surface and laser enclosure","3–4"],[Gauge,"Power monitoring","Model-appropriate smart meter / CT; installed by a qualified electrician","3"],[Wind,"Airflow / pressure monitoring","Laser exhaust airflow and optional air-assist verification","1–2"],[Cable,"QR labels","Durable printed QR/Asset ID labels","3"]].map(([Icon,name,spec,qty])=>{const ItemIcon=Icon as typeof Network;return <div key={String(name)}><ItemIcon size={19}/><span><strong>{String(name)}</strong><small>{String(spec)}</small></span><em>Qty {String(qty)}</em></div>})}</div></article><aside className="commissioning-card"><ShieldCheck size={28}/><h2>Commissioning rules</h2><ol><li>Confirm exact machine model, electrical rating and manufacturer constraints.</li><li>Install sensors without defeating guards, covers, interlocks or warranties.</li><li>Record a healthy baseline under repeatable operating conditions.</li><li>Run alerts in observation mode before enabling customer notifications.</li><li>Approve thresholds with the responsible technical and HSE teams.</li></ol></aside></section>
  </main>}
