"use client";

import { Download, Filter, Printer, Search, ShieldCheck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { AssetRecord } from "../lib/demo-data";
import { exportReport, type ReportFormat } from "../lib/report-export";

type WorkOrder={id:string;assetId:string;assetName:string;title:string;description:string;status:string;priority:string;assignee:string;dueDate:string;startedAt?:string;completedAt?:string;createdAt:string;resolution?:string};
type MaintenanceTask={id:string;assetId:string;assetName:string;title:string;cadence:string;nextDue:string;status:string;source:string;workOrderId?:string};
type HistoryRow={assetId:string;equipment:string;project:string;location:string;assetStatus:string;health:string;date:string;type:string;reference:string;status:string;technician:string;details:string};
const today=()=>new Date().toISOString().slice(0,10);
function workState(order:WorkOrder){const status=order.status.toLowerCase();if(status==="completed")return"Completed";if(status==="cancelled")return"Cancelled";if(order.startedAt||status==="in progress")return"In progress";if(order.dueDate&&order.dueDate<today())return"Overdue";return"Scheduled"}

export default function ReportsPage(){
 const[assets,setAssets]=useState<AssetRecord[]>([]),[orders,setOrders]=useState<WorkOrder[]>([]),[tasks,setTasks]=useState<MaintenanceTask[]>([]),[format,setFormat]=useState<ReportFormat>("pdf"),[query,setQuery]=useState(""),[project,setProject]=useState("all"),[status,setStatus]=useState("all"),[workStatus,setWorkStatus]=useState("all"),[location,setLocation]=useState("all");
 useEffect(()=>{Promise.all([fetch("/api/assets?images=0",{cache:"no-store"}),fetch("/api/work-orders",{cache:"no-store"}),fetch("/api/maintenance",{cache:"no-store"})]).then(async([a,w,m])=>{const ad=await a.json(),wd=await w.json(),md=await m.json();setAssets(ad.assets||[]);setOrders(wd.workOrders||[]);setTasks(md.maintenanceTasks||[])}).catch(()=>{})},[]);
 const projects=useMemo(()=>Array.from(new Set(assets.map(a=>a.project))).sort(),[assets]),locations=useMemo(()=>Array.from(new Set(assets.map(a=>a.location))).sort(),[assets]),statuses=useMemo(()=>Array.from(new Set(assets.map(a=>a.status))).sort(),[assets]);
 const matching=useMemo(()=>assets.filter(a=>{const text=`${a.name} ${a.id} ${a.model} ${a.serialNumber}`.toLowerCase();const ownOrders=orders.filter(o=>o.assetId===a.id);return(!query||text.includes(query.toLowerCase()))&&(project==="all"||a.project===project)&&(status==="all"||a.status===status)&&(location==="all"||a.location===location)&&(workStatus==="all"||ownOrders.some(o=>workState(o)===workStatus))}),[assets,orders,query,project,status,location,workStatus]);
 const matchingIds=useMemo(()=>new Set(matching.map(a=>a.id)),[matching]);
 const history=useMemo<HistoryRow[]>(()=>{const rows:HistoryRow[]=[];const byId=new Map(matching.map(a=>[a.id,a] as const));for(const t of tasks){if(!matchingIds.has(t.assetId))continue;const a=byId.get(t.assetId);if(!a)continue;rows.push({assetId:a.id,equipment:a.name,project:a.project,location:a.location,assetStatus:a.status,health:`${a.health}%`,date:t.nextDue||"",type:"Maintenance task",reference:t.workOrderId||t.id,status:t.status||"Planned",technician:"",details:`${t.title}${t.cadence?` · ${t.cadence}`:""}${t.source?` · ${t.source}`:""}`})}for(const o of orders){if(!matchingIds.has(o.assetId))continue;const a=byId.get(o.assetId);if(!a)continue;rows.push({assetId:a.id,equipment:a.name,project:a.project,location:a.location,assetStatus:a.status,health:`${a.health}%`,date:o.completedAt||o.startedAt||o.createdAt||o.dueDate,type:"Work order",reference:o.id,status:workState(o),technician:o.assignee||"",details:`${o.title}${o.resolution?` · Resolution: ${o.resolution}`:o.description?` · ${o.description}`:""}`})}return rows.sort((a,b)=>new Date(b.date||0).getTime()-new Date(a.date||0).getTime())},[matching,matchingIds,tasks,orders]);
 const openOrders=useMemo(()=>orders.filter(o=>matchingIds.has(o.assetId)&&!["Completed","Cancelled"].includes(o.status)).length,[orders,matchingIds]);
 async function download(){await exportReport({title:"SmartCare Filtered Maintenance & Asset History",format,columns:[{key:"assetId",label:"Asset ID"},{key:"equipment",label:"Equipment"},{key:"project",label:"Project"},{key:"location",label:"Location"},{key:"assetStatus",label:"Asset status"},{key:"health",label:"Health"},{key:"date",label:"Date"},{key:"type",label:"History type"},{key:"reference",label:"Reference"},{key:"status",label:"Work / maintenance status"},{key:"technician",label:"Technician"},{key:"details",label:"Maintenance / repair details"}],rows:history as unknown as Record<string,unknown>[],meta:{details:{"Matching assets":matching.length,"Open work orders":openOrders,"History records":history.length},filters:{Project:project,"Asset status":status,"Work order":workStatus,Location:location,Search:query||"None"}}})}
 return <main className="dashboard-main section-page report-page"><section className="page-heading no-print"><div><p className="eyebrow">Maintenance & asset history</p><h1>Asset Reports</h1><p className="page-subtitle">Filter equipment by project, condition, work-order state and location, then export one consolidated maintenance-history report for all matching assets without financial values.</p></div><div className="heading-actions"><label>Format<select value={format} onChange={e=>setFormat(e.target.value as ReportFormat)}><option value="pdf">PDF</option><option value="xlsx">Excel</option><option value="csv">CSV</option><option value="html">HTML</option></select></label><button className="button secondary" onClick={()=>window.print()}><Printer size={18}/> Print</button><button className="button primary" onClick={download} disabled={!matching.length}><Download size={18}/> Export history</button></div></section>
 <section className="toolbar-card no-print"><label className="page-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search machine, Asset ID, model or serial"/></label><label className="filter-select"><Filter size={16}/>Project<select value={project} onChange={e=>setProject(e.target.value)}><option value="all">All projects</option>{projects.map(v=><option key={v}>{v}</option>)}</select></label><label className="filter-select">Asset status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{statuses.map(v=><option key={v}>{v}</option>)}</select></label><label className="filter-select">Work order<select value={workStatus} onChange={e=>setWorkStatus(e.target.value)}><option value="all">All work orders</option><option>Scheduled</option><option>In progress</option><option>Overdue</option></select></label><label className="filter-select">Location<select value={location} onChange={e=>setLocation(e.target.value)}><option value="all">All locations</option>{locations.map(v=><option key={v}>{v}</option>)}</select></label></section>
 <section className="report-controls no-print"><span className="result-count"><strong>{matching.length}</strong> matching assets · <strong>{history.length}</strong> maintenance/history records</span></section>
 {matching.length?<article className="report-sheet"><header className="report-header"><div className="report-logo image"><img src="/ibtechar-main-logo.png" alt="Ibtechar" width={190} height={80}/></div><div><span>FILTERED MAINTENANCE HISTORY REPORT</span><strong>{matching.length} ASSETS</strong><small>{new Date().toLocaleString()}</small></div></header><section className="report-metrics interactive-report-metrics"><button type="button" onClick={()=>document.getElementById("report-asset-register")?.scrollIntoView({behavior:"smooth"})}><strong>{matching.length}</strong><span>Matching assets</span></button><button type="button" onClick={()=>document.getElementById("report-history")?.scrollIntoView({behavior:"smooth"})}><strong>{openOrders}</strong><span>Open work orders</span></button><button type="button" onClick={()=>document.getElementById("report-history")?.scrollIntoView({behavior:"smooth"})}><strong>{history.length}</strong><span>History records</span></button><button type="button" onClick={()=>document.getElementById("report-asset-register")?.scrollIntoView({behavior:"smooth"})}><strong>{new Set(matching.map(a=>a.location)).size}</strong><span>Locations</span></button></section><section className="report-section" id="report-asset-register"><h2>Filtered asset register</h2><div className="responsive-table"><table><thead><tr><th>Asset</th><th>Project</th><th>Location</th><th>Status</th><th>Health</th><th>Model / Serial</th></tr></thead><tbody>{matching.map(a=><tr key={a.id}><td><strong>{a.name}</strong><small>{a.id}</small></td><td>{a.project}</td><td>{a.location}</td><td><span className={`table-status ${a.tone}`}>{a.status}</span></td><td>{a.health}%</td><td>{a.model||"—"}<small>{a.serialNumber||"Serial not recorded"}</small></td></tr>)}</tbody></table></div></section><section className="report-section" id="report-history"><h2>Complete maintenance history</h2><div className="responsive-table"><table><thead><tr><th>Asset</th><th>Date</th><th>Type</th><th>Reference</th><th>Status</th><th>Technician</th><th>Details</th></tr></thead><tbody>{history.map((r,i)=><tr key={`${r.assetId}-${r.reference}-${i}`}><td><strong>{r.equipment}</strong><small>{r.assetId}</small></td><td>{r.date?new Date(r.date).toLocaleString():"—"}</td><td>{r.type}</td><td>{r.reference}</td><td>{r.status}</td><td>{r.technician||"—"}</td><td>{r.details}</td></tr>)}{!history.length&&<tr><td colSpan={7} className="empty-row">No maintenance history recorded for the matching assets.</td></tr>}</tbody></table></div></section><section className="safety-result"><ShieldCheck/><div><h3>Operational report</h3><p>This consolidated report intentionally excludes purchase cost, depreciation and current-value information.</p></div></section></article>:<section className="empty-state"><h2>No matching equipment</h2><p>Change the filters or search terms to include assets in this report.</p></section>}
 </main>
}
