"use client";

import { Building2, CircleDollarSign, Edit3, Factory, FolderKanban, Plus, ReceiptText, School, ShieldCheck, X } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useSmartCareAuth } from "../components/auth-provider";

type Project={id:string;name:string;manager:string;approvedBudget:number;committed:number;spent:number;status:string;assets:number;imageData?:string;financialVisible?:boolean};
const money=new Intl.NumberFormat("en-QA",{style:"currency",currency:"QAR",maximumFractionDigits:0});
const projectMeta:Record<string,{icon:typeof Building2;tone:string;caption:string}>={Ibtechar:{icon:Building2,tone:"blue",caption:"Corporate assets, workplace and technical services"},Sanea:{icon:Factory,tone:"amber",caption:"Sanea fabrication equipment portfolio"},"Studio 5":{icon:School,tone:"teal",caption:"MCIT Studio 5 and school FabLab assets"},DIC:{icon:FolderKanban,tone:"coral",caption:"DIC equipment, activities and project operations"}};

export default function ProjectsPage(){
  const {user,can}=useSmartCareAuth();
  const [projects,setProjects]=useState<Project[]>([]),[open,setOpen]=useState(false),[editOpen,setEditOpen]=useState(false),[editingId,setEditingId]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState("");
  const canEditBudget=["CEO","ADMIN","FINANCE","PROJECT_MANAGER"].includes(user?.role||"");
  const editingProject=useMemo(()=>projects.find(project=>project.id===editingId),[projects,editingId]);

  async function refresh(){const r=await fetch("/api/projects",{cache:"no-store"});const d=await r.json() as {projects?:Project[]};if(!r.ok)throw new Error("Unable to load project budgets.");setProjects(d.projects||[])}
  useEffect(()=>{refresh().catch(()=>setError("Unable to load project budgets."))},[]);
  async function add(fd:FormData){setError("");setMessage("");const r=await fetch("/api/projects",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:String(fd.get("name")),manager:String(fd.get("manager")),approvedBudget:Number(fd.get("budget"))})});if(!r.ok){const d=await r.json();setError(d.error||"Unable to create project");return}await refresh();setOpen(false);setMessage("Project budget created successfully.")}
  function beginEdit(){if(!canEditBudget||!projects.length)return;setEditingId(current=>current||projects[0].id);setError("");setMessage("");setEditOpen(true)}
  async function updateBudget(fd:FormData){if(!canEditBudget||!editingProject)return;setError("");setMessage("");const approvedBudget=Number(fd.get("approvedBudget"));const r=await fetch(`/api/projects/${encodeURIComponent(editingProject.id)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({approvedBudget})});const d=await r.json();if(!r.ok){setError(d.error||"Unable to update project budget.");return}await refresh();setEditOpen(false);setMessage(`${editingProject.name} approved budget updated successfully.`)}

  const approved=projects.reduce((s,p)=>s+p.approvedBudget,0),committed=projects.reduce((s,p)=>s+p.committed,0),spent=projects.reduce((s,p)=>s+p.spent,0);
  return <main className="dashboard-main section-page">
    <section className="page-heading"><div><p className="eyebrow">Financial control</p><h1>Project Budgets</h1><p className="page-subtitle">Click any project to open its customizable control dashboard. Financial values appear only to authorized roles.</p></div><div className="heading-actions">{canEditBudget&&<button className="button secondary" onClick={beginEdit}><Edit3 size={18}/> Edit project budget</button>}{can("projects","create")&&<button className="button primary" onClick={()=>setOpen(true)}><Plus size={18}/> Add project budget</button>}</div></section>
    <section className="finance-kpis" hidden={!projects.some(p=>p.financialVisible)}><article><span className="finance-icon blue"><CircleDollarSign size={22}/></span><div><small>Approved portfolio budget</small><strong>{money.format(approved)}</strong></div></article><article><span className="finance-icon amber"><ReceiptText size={22}/></span><div><small>Committed</small><strong>{money.format(committed)}</strong></div></article><article><span className="finance-icon teal"><FolderKanban size={22}/></span><div><small>Actual spend</small><strong>{money.format(spent)}</strong></div></article></section>
    {error&&<p className="form-error">{error}</p>}{message&&<p className="import-message success">{message}</p>}
    <section className="project-portrait-grid">{projects.map(p=>{const meta=projectMeta[p.name]||projectMeta.DIC,Icon=meta.icon,available=p.approvedBudget-p.committed-p.spent,used=p.financialVisible&&p.approvedBudget?Math.min(100,Math.round(p.committed/p.approvedBudget*100)):0;return <Link href={`/project-dashboard?project=${encodeURIComponent(p.name)}`} className={`project-portrait ${meta.tone} project-link`} key={p.id}><div className="project-art">{p.imageData?<img className="project-card-image" src={p.imageData} alt={p.name}/>:<Icon size={40}/>}<span>{p.name}</span></div><div className="project-body"><small>{meta.caption}</small><h2>{p.name}</h2>{p.financialVisible?<><div className="budget-progress large"><i style={{width:`${used}%`}}/></div><div className="project-numbers"><span><small>Approved</small><strong>{money.format(p.approvedBudget)}</strong></span><span><small>Available</small><strong>{money.format(available)}</strong></span></div><footer><span>{used}% committed</span><span>{p.assets} assets</span></footer></>:<div className="financial-restricted"><ShieldCheck size={18}/><div><strong>Financial values restricted</strong><p>{p.assets} assigned assets</p></div></div>}</div></Link>})}</section>
    {open&&<div className="modal-layer drawer-layer"><button className="modal-backdrop" onClick={()=>setOpen(false)}/><section className="issue-drawer"><div className="drawer-header"><div><p className="eyebrow">Manual budget entry</p><h2>New project budget</h2></div><button className="modal-close inline" onClick={()=>setOpen(false)}><X/></button></div><form action={add}><label>Project name<input name="name" required/></label><label>Budget owner<input name="manager" required defaultValue="Projects Office"/></label><label>Approved budget (QAR)<input name="budget" type="number" min="0" step="0.01" required/></label><button className="button primary full">Save project budget</button></form></section></div>}
    {editOpen&&editingProject&&<div className="modal-layer drawer-layer"><button className="modal-backdrop" onClick={()=>setEditOpen(false)}/><section className="issue-drawer"><div className="drawer-header"><div><p className="eyebrow">Admin & Finance control</p><h2>Edit approved budget</h2></div><button className="modal-close inline" onClick={()=>setEditOpen(false)}><X/></button></div><form action={updateBudget}><label>Project<select value={editingId} onChange={event=>setEditingId(event.target.value)}>{projects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label>Current approved budget<input value={money.format(editingProject.approvedBudget)} disabled/></label><label>New approved budget (QAR)<input name="approvedBudget" type="number" min="0" step="0.01" defaultValue={editingProject.approvedBudget} key={editingProject.id} required/></label><small className="field-note">Committed and actual spend are calculated from purchasing and expense transactions and cannot be edited here.</small><button className="button primary full"><Edit3 size={16}/> Save approved budget</button></form></section></div>}
  </main>
}
