"use client";
import { AlertTriangle,CalendarDays,CheckCircle2,ClipboardList,Clock3,Flag,Play,Plus,Search,UserRound,X,XCircle } from "lucide-react";
import { useEffect,useMemo,useState } from "react";
type WorkOrder={id:string;assetId:string;assetName:string;assetModel:string;maintenanceTaskId?:string;diagnosticSessionId?:number|null;title:string;description:string;status:string;priority:string;assignee:string;dueDate:string;scheduledStart?:string;startedAt?:string;cancelledAt?:string;completedAt?:string;completionWork?:string;resolution?:string;completionTechnician?:string;completionPartNote?:string;createdAt:string;updatedAt?:string};
type Asset={id:string;name:string};type User={id:string;name:string;role:string;active:boolean};
const today=()=>new Date().toISOString().slice(0,10);

export default function WorkOrdersPage(){
 const[orders,setOrders]=useState<WorkOrder[]>([]),[assets,setAssets]=useState<Asset[]>([]),[users,setUsers]=useState<User[]>([]),[query,setQuery]=useState("") ,[queueFilter,setQueueFilter]=useState<string>(""),[open,setOpen]=useState(false),[detail,setDetail]=useState<WorkOrder|null>(null),[completeOpen,setCompleteOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const params=typeof window!=="undefined"?new URLSearchParams(window.location.search):new URLSearchParams();
 async function refresh(){const[o,a,u]=await Promise.all([fetch("/api/work-orders",{cache:"no-store"}),fetch("/api/assets?images=0",{cache:"no-store"}),fetch("/api/users?compact=1")]);const[od,ad,ud]=await Promise.all([o.json(),a.json(),u.json()]);const loaded=od.workOrders||[];setOrders(loaded);setAssets(ad.assets||[]);setUsers((ud.users||[]).filter((x:User)=>x.active&&["TECHNICIAN","MANAGER","ADMIN"].includes(x.role)));const requested=params.get("open");if(requested)setDetail(loaded.find((x:WorkOrder)=>x.id===requested)||null);if(params.get("new")==="1")setOpen(true)}
 useEffect(()=>{const requested=params.get("queue");if(requested==="open")setQueueFilter("open");else if(["Overdue","In progress","Scheduled","Completed"].includes(requested||""))setQueueFilter(requested!);refresh().catch(()=>setError("Unable to load work orders."))},[]);
 const baseFiltered=useMemo(()=>orders.filter(o=>`${o.id} ${o.title} ${o.assetName} ${o.assetId} ${o.assignee}`.toLowerCase().includes(query.toLowerCase())&&!o.cancelledAt&&o.status.toLowerCase()!=="cancelled"),[orders,query]);
 function column(o:WorkOrder){if(o.status.toLowerCase()==="completed"||o.completedAt)return "Completed";if(o.startedAt||o.status.toLowerCase()==="in progress")return "In progress";if(o.dueDate<today())return "Overdue";return "Scheduled"}
 const columns=["Overdue","In progress","Scheduled","Completed"] as const;
 const filtered=useMemo(()=>baseFiltered.filter(o=>!queueFilter ? true : queueFilter==="open" ? column(o)!=="Completed" : column(o)===queueFilter),[baseFiltered,queueFilter]);
 const visibleColumns=queueFilter&&queueFilter!=="open"?columns.filter(c=>c===queueFilter):columns;
 const late=(o:WorkOrder)=>Boolean(o.startedAt&&o.scheduledStart&&new Date(o.startedAt)>new Date(o.scheduledStart));
 async function createOrder(fd:FormData){setSaving(true);setError("");const dueDate=String(fd.get("dueDate")),payload={assetId:String(fd.get("assetId")),title:String(fd.get("title")),description:String(fd.get("description")),priority:String(fd.get("priority")),assignee:String(fd.get("assignee")),dueDate,scheduledStart:`${dueDate}T${String(fd.get("time")||"09:00")}`,cadence:String(fd.get("cadence")||"One-off"),diagnosticSessionId:String(fd.get("diagnosticSessionId")||"")};try{const r=await fetch("/api/maintenance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to create work order");setOpen(false);await refresh();setDetail(d.workOrder);window.history.replaceState({},"",`/work-orders?open=${encodeURIComponent(d.workOrder.id)}`)}catch(e){setError(e instanceof Error?e.message:"Unable to create work order")}finally{setSaving(false)}}
 async function updateDetail(fd:FormData){if(!detail)return;const dueDate=String(fd.get("dueDate")),payload={title:String(fd.get("title")),description:String(fd.get("description")),priority:String(fd.get("priority")),assignee:String(fd.get("assignee")),dueDate,scheduledStart:`${dueDate}T${String(fd.get("time")||"09:00")}`,status:detail.status};const r=await fetch(`/api/work-orders/${encodeURIComponent(detail.id)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();if(r.ok){setDetail(d.workOrder);await refresh()}else setError(d.error||"Unable to update work order")}
 async function action(kind:"start"|"cancel"){if(!detail)return;const r=await fetch(`/api/work-orders/${encodeURIComponent(detail.id)}`,kind==="cancel"?{method:"DELETE"}:{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status:"In progress",start:true})}),d=await r.json();if(r.ok){setDetail(kind==="cancel"?null:d.workOrder);await refresh()}else setError(d.error||"Unable to update work order")}
 async function complete(fd:FormData){if(!detail)return;const payload={status:"Completed",complete:true,completionWork:String(fd.get("completionWork")),resolution:String(fd.get("resolution")),completionTechnician:String(fd.get("completionTechnician")),completionPartNote:String(fd.get("completionPartNote"))};const r=await fetch(`/api/work-orders/${encodeURIComponent(detail.id)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();if(r.ok){setCompleteOpen(false);setDetail(d.workOrder);await refresh()}else setError(d.error||"Unable to complete work order")}
 return <main className="dashboard-main section-page"><section className="page-heading"><div><p className="eyebrow">Service operations</p><h1>Work Order Control</h1><p className="page-subtitle">Search by asset, work-order number or technician. Work orders move from Scheduled to In Progress to Completed.</p></div><button className="button primary" onClick={()=>setOpen(true)}><Plus size={18}/> New work order</button></section>{error&&<p className="form-error">{error}</p>}
 <section className="toolbar-card"><label className="page-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Asset, work order, assignee / technician"/></label><div className="queue-stats interactive-queue-stats"><button type="button" className={queueFilter==="Overdue"?"selected":""} onClick={()=>setQueueFilter(queueFilter==="Overdue"?"":"Overdue")}><strong>{baseFiltered.filter(o=>column(o)==="Overdue").length}</strong> Overdue</button><button type="button" className={queueFilter==="In progress"?"selected":""} onClick={()=>setQueueFilter(queueFilter==="In progress"?"":"In progress")}><strong>{baseFiltered.filter(o=>column(o)==="In progress").length}</strong> In progress</button><button type="button" className={queueFilter==="Scheduled"?"selected":""} onClick={()=>setQueueFilter(queueFilter==="Scheduled"?"":"Scheduled")}><strong>{baseFiltered.filter(o=>column(o)==="Scheduled").length}</strong> Scheduled</button><button type="button" className={queueFilter==="Completed"?"selected":""} onClick={()=>setQueueFilter(queueFilter==="Completed"?"":"Completed")}><strong>{baseFiltered.filter(o=>column(o)==="Completed").length}</strong> Completed</button></div></section>
 <section className="kanban-board">{visibleColumns.map(c=><article className="kanban-column" key={c}><div className="kanban-title"><span className={c.toLowerCase().replace(" ","")}/><h2>{c}</h2><em>{filtered.filter(o=>column(o)===c).length}</em></div><div className="kanban-list">{filtered.filter(o=>column(o)===c).map(o=><button className={`work-order-card ${c==="Overdue"?"wo-overdue":late(o)?"wo-late":""}`} onClick={()=>setDetail(o)} key={o.id}><div><span>{o.id}</span><em className={o.priority.toLowerCase()}>{o.priority}</em></div><h3>{c==="Overdue"&&<Flag size={15}/>} {c==="Completed"&&<CheckCircle2 size={15}/>} {o.title}</h3><p>{o.assetName||o.assetId} · {o.assetId}</p><div><span><UserRound size={14}/>{o.assignee}</span><time>{c==="Completed"?`Completed ${o.completedAt?.slice(0,10)||""}`:`Due ${o.dueDate}`}</time></div></button>)}{c!=="Completed"&&<button className="kanban-add" onClick={()=>setOpen(true)}><Plus size={16}/> Add maintenance task</button>}</div></article>)}</section>
 {open&&<div className="modal-layer drawer-layer"><button className="modal-backdrop" onClick={()=>setOpen(false)}/><section className="issue-drawer"><div className="drawer-header"><div><p className="eyebrow">Linked maintenance workflow</p><h2>Review & create work order</h2></div><button className="modal-close inline" onClick={()=>setOpen(false)}><X/></button></div><form action={createOrder}><label>Asset<select name="assetId" required defaultValue={params.get("asset")||undefined}>{assets.map(a=><option value={a.id} key={a.id}>{a.name} · {a.id}</option>)}</select></label><label>Work required<input name="title" required defaultValue={params.get("title")||""} placeholder="Inspect equipment and verify normal operation"/></label><label>Description<textarea name="description" rows={5} defaultValue={params.get("description")||""}/></label><input type="hidden" name="diagnosticSessionId" value={params.get("diagnosticSessionId")||""}/><div className="form-grid"><label>Schedule date<input name="dueDate" type="date" min={today()} defaultValue={today()}/></label><label>Start time<input name="time" type="time" defaultValue="09:00"/></label></div><div className="form-grid"><label>Priority<select name="priority" defaultValue={params.get("priority")||"Normal"}><option>Normal</option><option>High</option><option>Critical</option></select></label><label>Cadence<select name="cadence"><option>One-off</option><option>Weekly</option><option>Monthly</option><option>Quarterly</option><option>Annual</option></select></label></div><label>Assignee<select name="assignee"><option>Unassigned</option>{users.map(u=><option key={u.id}>{u.name}</option>)}</select></label>{params.get("diagnosticSessionId")&&<small className="field-note">AI diagnostic session #{params.get("diagnosticSessionId")} is linked to this work order.</small>}<button className="button primary full" disabled={saving}><ClipboardList size={18}/>{saving?"Creating…":"Create & schedule"}</button></form></section></div>}
 {detail&&<div className="modal-layer drawer-layer"><button className="modal-backdrop" onClick={()=>setDetail(null)}/><section className="issue-drawer work-order-detail"><div className="drawer-header"><div><p className="eyebrow">{detail.id} · {detail.assetName}</p><h2>Work Order Dashboard</h2></div><button className="modal-close inline" onClick={()=>setDetail(null)}><X/></button></div><div className="wo-detail-flags">{column(detail)==="Overdue"&&<span className="red-flag"><AlertTriangle size={15}/> Overdue</span>}{late(detail)&&<span className="orange-flag"><Flag size={15}/> Started late</span>}{column(detail)==="Completed"&&<span><CheckCircle2 size={15}/> Completed</span>}<span><CalendarDays size={15}/> {detail.scheduledStart?.replace("T"," ")||detail.dueDate}</span></div><form action={updateDetail}><label>Work required<input name="title" defaultValue={detail.title} required disabled={detail.status==="Completed"}/></label><label>Description<textarea name="description" rows={4} defaultValue={detail.description} disabled={detail.status==="Completed"}/></label><div className="form-grid"><label>Schedule date<input name="dueDate" type="date" defaultValue={detail.dueDate} disabled={detail.status==="Completed"}/></label><label>Start time<input name="time" type="time" defaultValue={detail.scheduledStart?.split("T")[1]?.slice(0,5)||"09:00"} disabled={detail.status==="Completed"}/></label></div><div className="form-grid"><label>Priority<select name="priority" defaultValue={detail.priority} disabled={detail.status==="Completed"}><option>Normal</option><option>High</option><option>Critical</option></select></label><label>Assignee<select name="assignee" defaultValue={detail.assignee} disabled={detail.status==="Completed"}><option>Unassigned</option>{users.map(u=><option key={u.id}>{u.name}</option>)}</select></label></div>{detail.status!=="Completed"&&<button className="button secondary full">Save edits</button>}</form>{detail.status==="Completed"&&<div className="safety-result"><CheckCircle2/><div><h3>Resolution</h3><p>{detail.resolution||"Completed"}</p>{detail.completionPartNote&&<small>{detail.completionPartNote}</small>}</div></div>}<div className="drawer-actions">{detail.status!=="Completed"&&!detail.startedAt&&<button className="button primary" onClick={()=>action("start")}><Play size={16}/> Start work</button>}{detail.status!=="Completed"&&detail.startedAt&&<button className="button primary" onClick={()=>setCompleteOpen(true)}><CheckCircle2 size={16}/> Complete work order</button>}{detail.status!=="Completed"&&<button className="button secondary danger-text" onClick={()=>action("cancel")}><XCircle size={16}/> Cancel work order</button>}</div><small className="field-note"><Clock3 size={13}/> Completion updates the asset to Operational · Health 100% and writes a repair event to its history.</small></section></div>}
 {completeOpen&&detail&&<div className="modal-layer drawer-layer"><button className="modal-backdrop" onClick={()=>setCompleteOpen(false)}/><section className="issue-drawer"><div className="drawer-header"><div><p className="eyebrow">{detail.id}</p><h2>Complete work order</h2></div><button className="modal-close inline" onClick={()=>setCompleteOpen(false)}><X/></button></div><form action={complete}><label>Work performed<textarea name="completionWork" rows={3} defaultValue="Filament path and nozzle inspected and cleaned." required/></label><label>Resolution<textarea name="resolution" rows={4} defaultValue="Filament path and nozzle inspected and cleaned. Test print completed successfully and normal extrusion restored." required/></label><label>Technician<input name="completionTechnician" defaultValue={detail.assignee}/></label><label>Optional part used / note<input name="completionPartNote" placeholder="No replacement part required"/></label><button className="button primary full"><CheckCircle2 size={18}/> Complete & restore asset</button></form></section></div>}
 </main>
}
