"use client";
import { Calculator,FileDown,Landmark,RefreshCw,ShieldCheck } from "lucide-react";
import { useEffect,useMemo,useState } from "react";
import { depreciationFor,type AssetRecord } from "../lib/demo-data";
import { exportReport,type ReportFormat } from "../lib/report-export";
const money=new Intl.NumberFormat("en-QA",{style:"currency",currency:"QAR",maximumFractionDigits:0});
export default function DepreciationPage(){
 const[assets,setAssets]=useState<AssetRecord[]>([]),[project,setProject]=useState("all"),[sort,setSort]=useState("life-desc"),[format,setFormat]=useState<ReportFormat>("pdf");
 async function refresh(){const r=await fetch("/api/assets",{cache:"no-store"}),d=await r.json() as {assets?:AssetRecord[]};setAssets(d.assets||[])}useEffect(()=>{refresh().catch(()=>{})},[]);
 const financialAssets=assets.filter(a=>a.financialVisible===true),restricted=assets.length>0&&!financialAssets.length,projects=useMemo(()=>Array.from(new Set(financialAssets.map(a=>a.project))).sort(),[financialAssets]);
 const rows=useMemo(()=>financialAssets.filter(a=>project==="all"||a.project===project).map(asset=>({asset,...depreciationFor(asset,new Date())})).sort((a,b)=>sort==="life-asc"?a.percent-b.percent:b.percent-a.percent),[financialAssets,project,sort]);
 const gross=rows.reduce((s,r)=>s+r.asset.acquisitionCost,0),acc=rows.reduce((s,r)=>s+r.accumulated,0),book=rows.reduce((s,r)=>s+r.netBookValue,0);
 async function report(){if(restricted)return;await exportReport({title:"Depreciation & Lifecycle Report",format,columns:[{key:"id",label:"Asset ID"},{key:"name",label:"Asset"},{key:"project",label:"Project"},{key:"cost",label:"Acquisition QAR"},{key:"net",label:"Net Book QAR"},{key:"life",label:"Lifecycle %"}],rows:rows.map(r=>({id:r.asset.id,name:r.asset.name,project:r.asset.project,cost:r.asset.acquisitionCost,net:Math.round(r.netBookValue),life:r.percent})),meta:{filters:{Project:project,Sort:sort},details:{"Gross acquisition value":money.format(gross),"Net book value":money.format(book)}}})}
 return <main className="dashboard-main section-page"><section className="page-heading"><div><p className="eyebrow">Asset lifecycle</p><h1>Depreciation & Replacement Planning</h1><p className="page-subtitle">Protected financial analysis for authorized project roles.</p></div><button className="button secondary" onClick={refresh}><RefreshCw size={17}/> Recalculate</button></section>
 {restricted?<section className="financial-restricted"><ShieldCheck/><div><strong>Financial access is restricted for your role</strong><p>Staff and technicians can review asset condition and maintenance from Assets and Reports, but cannot access purchase, book or depreciation values.</p></div></section>:<><section className="finance-kpis compact"><article><span className="finance-icon blue"><Landmark size={22}/></span><div><small>Total acquisition value</small><strong>{money.format(gross)}</strong></div></article><article><span className="finance-icon amber"><Calculator size={22}/></span><div><small>Accumulated depreciation</small><strong>{money.format(acc)}</strong></div></article><article><span className="finance-icon teal"><Landmark size={22}/></span><div><small>Net book value</small><strong>{money.format(book)}</strong></div></article></section><section className="toolbar-card"><label className="filter-select">Project<select value={project} onChange={e=>setProject(e.target.value)}><option value="all">All projects</option>{projects.map(p=><option key={p}>{p}</option>)}</select></label><label className="filter-select">Lifecycle<select value={sort} onChange={e=>setSort(e.target.value)}><option value="life-desc">Most depreciated first</option><option value="life-asc">Least depreciated first</option></select></label><label className="filter-select">Report<select value={format} onChange={e=>setFormat(e.target.value as ReportFormat)}><option value="pdf">PDF</option><option value="xlsx">Excel</option><option value="csv">CSV</option><option value="html">HTML</option></select></label><button className="button secondary" onClick={report}><FileDown size={16}/> Generate report</button></section><section className="budget-table-card"><div className="panel-heading"><div><h2>Depreciation register</h2><p>Method: straight-line · calculated at report time.</p></div></div><div className="responsive-table"><table><thead><tr><th>Asset</th><th>Project</th><th>Cost</th><th>Residual value</th><th>Useful life</th><th>Age</th><th>Accumulated depreciation</th><th>Net book value</th><th>Lifecycle</th></tr></thead><tbody>{rows.map(({asset,months,accumulated,netBookValue,percent})=><tr key={asset.id}><td><strong>{asset.name}</strong><small>{asset.id}</small></td><td>{asset.project}</td><td>{money.format(asset.acquisitionCost)}</td><td>{money.format(asset.residualValue)}</td><td>{asset.usefulLifeYears} years</td><td>{months} months</td><td>{money.format(accumulated)}</td><td><strong>{money.format(netBookValue)}</strong></td><td><div className="lifecycle-bar"><i className={percent>75?"warning":""} style={{width:`${percent}%`}}/></div><small>{percent}% depreciated</small></td></tr>)}</tbody></table></div></section></>}</main>}
