"use client";
import { BarChart3,Box,Eye,EyeOff,FileDown,ImagePlus,Plus,ReceiptText,Trash2,Wrench } from "lucide-react";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import type { AssetRecord } from "../lib/demo-data";
import { exportReport,type ReportFormat } from "../lib/report-export";
type Project={id:string;name:string;manager:string;approvedBudget:number;committed:number;spent:number;status:string;assets:number;imageData?:string};
type Activity={id:string;project:string;type:string;title:string;date:string;quantity:number;school?:string;status:string};
type Expense={id:string;description:string;amount:number;expenseType:string;budgetBranch:string;incurredOn:string;status:string;assetId?:string|null};
type ChartKey="spend"|"commitment"|"assetHealth"|"assetStatus"|"locations"|"activities";
const chartNames:Record<ChartKey,string>={spend:"Actual Spend",commitment:"Budget Commitment",assetHealth:"Asset Health",assetStatus:"Asset Status",locations:"Asset Locations",activities:"Project Activities"};
const money=new Intl.NumberFormat("en-QA",{style:"currency",currency:"QAR",maximumFractionDigits:0});
function Ring({value,label,tone="blue"}:{value:number;label:string;tone?:string}){const n=Math.max(0,Math.min(100,Number.isFinite(value)?value:0));return <div className={`project-ring ${tone}`} style={{"--ring":`${n*3.6}deg`} as React.CSSProperties}><div><strong>{n}%</strong><span>{label}</span></div></div>}
export default function ProjectDashboard(){
 const[projects,setProjects]=useState<Project[]>([]),[assets,setAssets]=useState<AssetRecord[]>([]),[activities,setActivities]=useState<Activity[]>([]),[expenses,setExpenses]=useState<Expense[]>([]),[selected,setSelected]=useState(""),[charts,setCharts]=useState<ChartKey[]>(["spend","commitment","assetHealth","activities"]),[showMoney,setShowMoney]=useState(true),[addChart,setAddChart]=useState<ChartKey>("assetStatus"),[format,setFormat]=useState<ReportFormat>("pdf"),[activityOpen,setActivityOpen]=useState(false),[expenseOpen,setExpenseOpen]=useState(false),[error,setError]=useState("");
 async function refresh(){const [pr,ar,ac]=await Promise.all([fetch("/api/projects",{cache:"no-store"}),fetch("/api/assets",{cache:"no-store"}),fetch("/api/project-activities",{cache:"no-store"})]);const [p,a,c]=await Promise.all([pr.json(),ar.json(),ac.json()]);const ps=(p.projects||[]) as Project[];setProjects(ps);setAssets(a.assets||[]);setActivities(c.activities||[]);if(!selected){const fromUrl=new URLSearchParams(window.location.search).get("project");setSelected(ps.find(x=>x.name===fromUrl)?.name||ps[0]?.name||"")}}
 useEffect(()=>{refresh().catch(()=>setError("Unable to load project dashboard."))},[]);
 useEffect(()=>{if(!selected)return;try{const saved=localStorage.getItem(`smartcare.dashboard.${selected}`);if(saved)setCharts(JSON.parse(saved));const moneyPref=localStorage.getItem(`smartcare.dashboard.money.${selected}`);if(moneyPref!==null)setShowMoney(moneyPref==="true")}catch{}},[selected]);
 useEffect(()=>{if(selected)localStorage.setItem(`smartcare.dashboard.${selected}`,JSON.stringify(charts))},[charts,selected]);
 useEffect(()=>{if(selected)localStorage.setItem(`smartcare.dashboard.money.${selected}`,String(showMoney))},[showMoney,selected]);
 const p=projects.find(x=>x.name===selected),ownAssets=useMemo(()=>assets.filter(a=>a.project===selected),[assets,selected]),ownActivities=useMemo(()=>activities.filter(a=>a.project===selected),[activities,selected]);
 useEffect(()=>{if(selected)fetch(`/api/expenses?project=${encodeURIComponent(selected)}`,{cache:"no-store"}).then(r=>r.json()).then(d=>setExpenses(d.expenses||[])).catch(()=>{})},[selected]);
 const avgHealth=ownAssets.length?Math.round(ownAssets.reduce((s,a)=>s+a.health,0)/ownAssets.length):0;
 const chartRows=(key:ChartKey):Record<string,unknown>[]=>{if(!p)return[];if(key==="spend")return[{metric:"Approved budget",value:p.approvedBudget},{metric:"Actual spend",value:p.spent},{metric:"Remaining",value:p.approvedBudget-p.spent}];if(key==="commitment")return[{metric:"Approved",value:p.approvedBudget},{metric:"Committed",value:p.committed},{metric:"Available",value:p.approvedBudget-p.committed-p.spent}];if(key==="assetHealth")return ownAssets.map(a=>({metric:a.name,value:a.health,status:a.status}));if(key==="assetStatus")return Object.entries(Object.groupBy(ownAssets,a=>a.status)).map(([metric,v])=>({metric,value:v?.length||0}));if(key==="locations")return Object.entries(Object.groupBy(ownAssets,a=>a.location)).map(([metric,v])=>({metric,value:v?.length||0}));return ownActivities.map(a=>({metric:a.title,value:a.quantity,status:a.status}));};
 function chartPercent(key:ChartKey){if(!p)return 0;if(key==="spend")return p.approvedBudget?Math.round(p.spent/p.approvedBudget*100):0;if(key==="commitment")return p.approvedBudget?Math.round(p.committed/p.approvedBudget*100):0;if(key==="assetHealth")return avgHealth;if(key==="activities")return Math.min(100,ownActivities.filter(a=>["Completed","Delivered"].includes(a.status)).length*10);return ownAssets.length?Math.round(Math.max(...chartRows(key).map(r=>Number(r.value||0)))/ownAssets.length*100):0}
 const displayMoney=(value:number)=>showMoney?money.format(value):"••••••";
 async function runExport(title:string,rows:Record<string,unknown>[]){if(!p)return;await exportReport({title,format,columns:[{key:"metric",label:"Metric"},{key:"value",label:"Value"},{key:"status",label:"Status"}],rows,meta:{project:p.name,projectImage:p.imageData,details:{Manager:p.manager,"Approved budget":showMoney?money.format(p.approvedBudget):"Hidden",Assets:ownAssets.length},filters:{Dashboard:"Custom project dashboard"}}})}
 async function exportDashboard(){const rows=charts.flatMap(key=>chartRows(key).map(r=>({metric:`${chartNames[key]} — ${r.metric}`,value:r.value,status:r.status||""})));await runExport(`${selected} Project Dashboard`,rows)}
 function addSelectedChart(){if(!charts.includes(addChart))setCharts(c=>[...c,addChart])}
 async function savePicture(file:File){if(!p)return;if(file.size>5_000_000){setError("Project picture must be 5 MB or less.");return}const upload=new FormData();upload.set("file",file);upload.set("bucket","asset-images");const uploaded=await fetch("/api/storage/upload",{method:"POST",body:upload}),result=await uploaded.json() as {path?:string;error?:string};if(!uploaded.ok||!result.path){setError(result.error||"Unable to upload project picture.");return}const res=await fetch(`/api/projects/${encodeURIComponent(p.id)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({imagePath:result.path})});if(!res.ok){setError("Unable to save project picture.");return}await refresh()}
 async function addActivity(fd:FormData){const res=await fetch("/api/project-activities",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({project:selected,type:String(fd.get("type")),title:String(fd.get("title")),date:String(fd.get("date")),quantity:Number(fd.get("quantity")),school:String(fd.get("school")),status:String(fd.get("status"))})});if(res.ok){setActivityOpen(false);await refresh()}else setError("Unable to save project activity.")}
 async function addExpense(fd:FormData){if(!p)return;const payload={projectId:p.id,budgetBranch:String(fd.get("budgetBranch")),expenseType:String(fd.get("expenseType")),description:String(fd.get("description")),amount:Number(fd.get("amount")),incurredOn:String(fd.get("incurredOn")),assetName:String(fd.get("assetName")),assetCategory:String(fd.get("assetCategory")),location:String(fd.get("location")),usefulLifeYears:Number(fd.get("usefulLifeYears")||5)};const res=await fetch("/api/expenses",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(res.ok){setExpenseOpen(false);await refresh();const d=await fetch(`/api/expenses?project=${encodeURIComponent(selected)}`).then(r=>r.json());setExpenses(d.expenses||[])}else{const d=await res.json();setError(d.error||"Unable to record expense.")}}
 return <main className="dashboard-main section-page"><section className="page-heading"><div><p className="eyebrow">Custom project control</p><h1>Project Dashboard</h1><p className="page-subtitle">Add or remove charts, control financial visibility and export the current project view.</p></div><div className="dashboard-actions"><label className="dashboard-select">Project<select value={selected} onChange={e=>setSelected(e.target.value)}>{projects.map(x=><option key={x.id}>{x.name}</option>)}</select></label><button className="button secondary" onClick={()=>setShowMoney(v=>!v)}>{showMoney?<EyeOff size={16}/>:<Eye size={16}/>} {showMoney?"Hide amounts":"Show amounts"}</button></div></section>{error&&<p className="form-error">{error}</p>}
 {p&&<><section className="project-hero dashboard-project-hero">{p.imageData?<img src={p.imageData} alt={p.name}/>:<div className="project-placeholder"><BarChart3 size={34}/></div>}<div><span>Project control</span><h2>{p.name}</h2><p>Owner: {p.manager} · {ownAssets.length} registered assets</p></div><label className="button secondary upload-project-image"><ImagePlus size={16}/> Project picture<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)savePicture(f)}}/></label><button className="button secondary" onClick={()=>setExpenseOpen(true)}><ReceiptText size={16}/> Actual spend</button><Link className="button secondary" href={`/tasks?project=${encodeURIComponent(p.name)}`}> <Plus size={16}/> Project task</Link><button className="button primary" onClick={()=>setActivityOpen(true)}><Plus size={16}/> Activity</button></section>
 <section className="dashboard-builder"><div><select value={addChart} onChange={e=>setAddChart(e.target.value as ChartKey)}>{(Object.keys(chartNames) as ChartKey[]).map(k=><option key={k} value={k}>{chartNames[k]}</option>)}</select><button className="button secondary" onClick={addSelectedChart}><Plus size={16}/> Add chart</button></div><div><select value={format} onChange={e=>setFormat(e.target.value as ReportFormat)}><option value="pdf">PDF</option><option value="xlsx">Excel</option><option value="csv">CSV</option><option value="html">HTML</option></select><button className="button primary" onClick={exportDashboard}><FileDown size={16}/> Export dashboard</button></div></section>
 <section className="custom-chart-grid">{charts.map(key=>{const rows=chartRows(key),percent=chartPercent(key);return <article className="dashboard-chart" key={key}><header><div><small>Custom chart</small><h2>{chartNames[key]}</h2></div><div><button title="Export chart" onClick={()=>runExport(`${selected} — ${chartNames[key]}`,rows)}><FileDown size={15}/></button><button title="Remove chart" onClick={()=>setCharts(c=>c.filter(x=>x!==key))}><Trash2 size={15}/></button></div></header><div className="chart-body"><Ring value={percent} label={chartNames[key]} tone={key==="commitment"?"amber":key==="assetHealth"?"teal":"blue"}/><div className="chart-list">{key==="spend"&&p&&<><span><small>Spent</small><strong>{displayMoney(p.spent)}</strong></span><span><small>Approved</small><strong>{displayMoney(p.approvedBudget)}</strong></span></>}{key==="commitment"&&p&&<><span><small>Committed</small><strong>{displayMoney(p.committed)}</strong></span><span><small>Available</small><strong>{displayMoney(p.approvedBudget-p.committed)}</strong></span></>}{!["spend","commitment"].includes(key)&&rows.slice(0,5).map((r,i)=><span key={i}><small>{String(r.metric)}</small><strong>{String(r.value)}{key==="assetHealth"?"%":""}</strong></span>)}</div></div></article>})}</section>
 <section className="budget-table-card"><div className="panel-heading"><div><h2>Project asset register</h2><p>Live assets under this project. Open an asset to change its status or location, or schedule a maintenance work order.</p></div></div><div className="responsive-table"><table><thead><tr><th>Asset</th><th>Location</th><th>Purchase value</th><th>Health</th><th>Action</th></tr></thead><tbody>{ownAssets.map(a=><tr key={a.id}><td><Link href={`/assets/${a.id}`}><strong>{a.name}</strong><small>{a.id}</small></Link></td><td>{a.location}</td><td>{displayMoney(a.acquisitionCost)}</td><td>{a.health}%</td><td><Link className="text-button" href={`/work-orders?new=1&asset=${a.id}`}><Wrench size={14}/> Maintenance</Link></td></tr>)}{!ownAssets.length&&<tr><td className="empty-row" colSpan={5}>No assets recorded under this project.</td></tr>}</tbody></table></div></section><section className="budget-table-card"><div className="panel-heading"><div><h2>Actual spend register</h2><p>Expenses are linked to the selected project and automatically refresh budget commitment and spend.</p></div></div><div className="responsive-table"><table><thead><tr><th>Date</th><th>Description</th><th>Type</th><th>Budget branch</th><th>Amount</th></tr></thead><tbody>{expenses.map(e=><tr key={e.id}><td>{e.incurredOn}</td><td>{e.description}</td><td>{e.expenseType}{e.assetId&&<small> · Asset created</small>}</td><td>{e.budgetBranch}</td><td>{displayMoney(e.amount)}</td></tr>)}{!expenses.length&&<tr><td colSpan={5} className="empty-row">No manual expenses recorded yet.</td></tr>}</tbody></table></div></section></>}
 {expenseOpen&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setExpenseOpen(false)}/><section className="modal-card activity-modal"><p className="eyebrow">{selected} · Actual spend</p><h2>Record project expense</h2><form action={addExpense}><label>Expense description<input name="description" required/></label><div className="form-grid"><label>Type<select name="expenseType"><option>Consumable</option><option>Intern wages</option><option>Freelancer wages</option><option>Asset</option></select></label><label>Budget branch<select name="budgetBranch"><option>Equipment</option><option>Consumables</option><option>Marketing</option><option>Call-off</option></select></label></div><div className="form-grid"><label>Amount (QAR)<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>Date<input name="incurredOn" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label></div><label>Asset name — only when type is Asset<input name="assetName"/></label><div className="form-grid"><label>Asset category<input name="assetCategory" placeholder="Procured Asset"/></label><label>Location<input name="location" placeholder="IBTECHAR_STORE"/></label></div><label>Useful life years<input name="usefulLifeYears" type="number" min="1" defaultValue="5"/></label><button className="button primary full">Record expense</button></form></section></div>}{activityOpen&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setActivityOpen(false)}/><section className="modal-card activity-modal"><p className="eyebrow">{selected}</p><h2>Add project activity</h2><form action={addActivity}><label>Activity type<select name="type"><option>Workshop</option><option>School delivery</option></select></label><label>Activity name<input name="title" required/></label><div className="form-grid"><label>School / venue<input name="school"/></label><label>Quantity<input name="quantity" type="number" min="1" defaultValue="1"/></label></div><div className="form-grid"><label>Date<input name="date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Status<select name="status"><option>Completed</option><option>Scheduled</option><option>Delivered</option></select></label></div><button className="button primary full">Save activity</button></form></section></div>}</main>
}

