"use client";
import { AlertTriangle,Boxes,Edit3,FileDown,PackagePlus,Search,Trash2,X } from "lucide-react";
import { useEffect,useMemo,useState } from "react";
import { exportReport,type ReportFormat } from "../lib/report-export";
type Part={sku:string;name:string;category:string;onHand:number;reorderPoint:number;unitCost:number;location:string;linkedAssets:string};
const money=new Intl.NumberFormat("en-QA",{style:"currency",currency:"QAR",maximumFractionDigits:0});
export default function InventoryPage(){
 const[parts,setParts]=useState<Part[]>([]),[q,setQ]=useState(""),[category,setCategory]=useState("all"),[storage,setStorage]=useState("all"),[sort,setSort]=useState("name-asc"),[lowOnly,setLowOnly]=useState(false),[editing,setEditing]=useState<Part|null>(null),[open,setOpen]=useState(false),[format,setFormat]=useState<ReportFormat>("pdf"),[scope,setScope]=useState("filtered"),[error,setError]=useState("");
 async function refresh(){const r=await fetch("/api/inventory",{cache:"no-store"}),d=await r.json() as {parts?:Part[]};setParts(d.parts||[])}useEffect(()=>{refresh().catch(()=>setError("Unable to load spare parts."))},[]);
 const categories=useMemo(()=>Array.from(new Set(parts.map(p=>p.category))).sort(),[parts]),storages=useMemo(()=>Array.from(new Set(parts.map(p=>p.location))).sort(),[parts]);
 const rows=useMemo(()=>parts.filter(p=>(!lowOnly||p.onHand<=p.reorderPoint)&&(category==="all"||p.category===category)&&(storage==="all"||p.location===storage)&&`${p.sku} ${p.name} ${p.linkedAssets}`.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>sort==="stock-asc"?a.onHand-b.onHand:sort==="stock-desc"?b.onHand-a.onHand:sort==="value-desc"?b.onHand*b.unitCost-a.onHand*a.unitCost:sort==="category"?a.category.localeCompare(b.category):a.name.localeCompare(b.name)),[parts,q,lowOnly,category,storage,sort]);
 const low=parts.filter(p=>p.onHand<=p.reorderPoint),value=parts.reduce((s,p)=>s+p.onHand*p.unitCost,0);
 async function save(fd:FormData){const payload={sku:String(fd.get("sku")),name:String(fd.get("name")),category:String(fd.get("category")),onHand:Number(fd.get("onHand")),reorderPoint:Number(fd.get("reorderPoint")),unitCost:Number(fd.get("unitCost")),location:String(fd.get("location")),linkedAssets:String(fd.get("linkedAssets"))};const url=editing?`/api/inventory/${encodeURIComponent(editing.sku)}`:"/api/inventory",method=editing?"PATCH":"POST";const r=await fetch(url,{method,headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok){setError(d.error||"Unable to save spare part");return}setOpen(false);setEditing(null);await refresh()}
 async function remove(sku:string){if(!window.confirm(`Delete spare part ${sku}?`))return;const r=await fetch(`/api/inventory/${encodeURIComponent(sku)}`,{method:"DELETE"});if(r.ok)await refresh();else setError("Unable to delete spare part")}
 function edit(p:Part){setEditing(p);setOpen(true)}function add(){setEditing(null);setOpen(true)}
 async function report(){const source=scope==="all"?parts:rows;await exportReport({title:"Spare Parts Inventory Report",format,columns:[{key:"sku",label:"SKU"},{key:"name",label:"Part"},{key:"category",label:"Category"},{key:"onHand",label:"On hand"},{key:"reorderPoint",label:"Reorder point"},{key:"unitCost",label:"Unit cost QAR"},{key:"location",label:"Storage"},{key:"linkedAssets",label:"Linked assets"}],rows:source as unknown as Record<string,unknown>[],meta:{filters:scope==="all"?{Scope:"All records"}:{Category:category,Storage:storage,"Low stock":String(lowOnly),Search:q||"None",Sort:sort}}})}
 return <main className="dashboard-main section-page"><section className="page-heading"><div><p className="eyebrow">Technical stores</p><h1>Spare Parts Inventory</h1><p className="page-subtitle">Full insert, edit, update and delete control with filtered reporting.</p></div><button className="button primary" onClick={add}><PackagePlus size={18}/> Add spare part</button></section>{error&&<p className="form-error">{error}</p>}
 <section className="finance-kpis compact interactive-finance-kpis"><button type="button" className={`finance-kpi-button ${!lowOnly&&sort!=="value-desc"?"selected":""}`} onClick={()=>{setLowOnly(false);setCategory("all");setStorage("all");setQ("");setSort("name-asc")}}><span className="finance-icon blue"><Boxes size={22}/></span><div><small>Parts SKUs tracked</small><strong>{parts.length}</strong><span>View all inventory</span></div></button><button type="button" className={`finance-kpi-button ${lowOnly?"selected":""}`} onClick={()=>{setLowOnly(true);setSort("stock-asc")}}><span className="finance-icon coral"><AlertTriangle size={22}/></span><div><small>Below reorder point</small><strong>{low.length}</strong><span>Show low-stock items</span></div></button><button type="button" className={`finance-kpi-button ${sort==="value-desc"&&!lowOnly?"selected":""}`} onClick={()=>{setLowOnly(false);setSort("value-desc")}}><span className="finance-icon teal"><Boxes size={22}/></span><div><small>On-hand value</small><strong>{money.format(value)}</strong><span>Rank by stock value</span></div></button></section>
 <section className="toolbar-card"><label className="page-search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search SKU, part or linked equipment"/></label><label className="filter-select">Category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="filter-select">Storage<select value={storage} onChange={e=>setStorage(e.target.value)}><option value="all">All storage</option>{storages.map(s=><option key={s}>{s}</option>)}</select></label><label className="filter-select">Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="name-asc">Name A–Z</option><option value="category">Category</option><option value="stock-asc">Stock low–high</option><option value="stock-desc">Stock high–low</option><option value="value-desc">Stock value high–low</option></select></label><label className="check-filter"><input type="checkbox" checked={lowOnly} onChange={e=>setLowOnly(e.target.checked)}/> Low stock</label></section>
 <section className="report-strip"><label>Report scope<select value={scope} onChange={e=>setScope(e.target.value)}><option value="filtered">Current filter + sort</option><option value="all">All spare parts</option></select></label><label>Format<select value={format} onChange={e=>setFormat(e.target.value as ReportFormat)}><option value="pdf">PDF</option><option value="xlsx">Excel</option><option value="csv">CSV</option><option value="html">HTML</option></select></label><button className="button secondary" onClick={report}><FileDown size={16}/> Generate report</button><span>{rows.length} items visible</span></section>
 <section className="budget-table-card"><div className="responsive-table"><table><thead><tr><th>Part / SKU</th><th>Category</th><th>On hand</th><th>Reorder</th><th>Unit cost</th><th>Stock value</th><th>Storage</th><th>Linked assets</th><th>Actions</th></tr></thead><tbody>{rows.map(p=>{const lowStock=p.onHand<=p.reorderPoint;return <tr key={p.sku}><td><strong>{p.name}</strong><small>{p.sku}</small></td><td>{p.category}</td><td><span className={lowStock?"stock-low":"stock-ok"}>{p.onHand}</span></td><td>{p.reorderPoint}</td><td>{money.format(p.unitCost)}</td><td>{money.format(p.onHand*p.unitCost)}</td><td>{p.location}</td><td>{p.linkedAssets}</td><td><div className="table-actions"><button onClick={()=>edit(p)}><Edit3 size={15}/> Edit</button><button className="danger" onClick={()=>remove(p.sku)}><Trash2 size={15}/> Delete</button></div></td></tr>})}</tbody></table></div></section>
 {open&&<div className="modal-layer drawer-layer"><button className="modal-backdrop" onClick={()=>setOpen(false)}/><section className="issue-drawer"><div className="drawer-header"><div><p className="eyebrow">Spare part</p><h2>{editing?"Edit spare part":"Add spare part"}</h2></div><button className="modal-close inline" onClick={()=>setOpen(false)}><X/></button></div><form action={save}><label>SKU<input name="sku" required defaultValue={editing?.sku||""} readOnly={Boolean(editing)}/></label><label>Part name<input name="name" required defaultValue={editing?.name||""}/></label><div className="form-grid"><label>Category<input name="category" required defaultValue={editing?.category||""}/></label><label>Storage location<input name="location" required defaultValue={editing?.location||""}/></label></div><div className="form-grid"><label>On hand<input name="onHand" type="number" min="0" defaultValue={editing?.onHand||0}/></label><label>Reorder point<input name="reorderPoint" type="number" min="0" defaultValue={editing?.reorderPoint||0}/></label></div><label>Unit cost (QAR)<input name="unitCost" type="number" min="0" step=".01" defaultValue={editing?.unitCost||0}/></label><label>Linked assets<input name="linkedAssets" defaultValue={editing?.linkedAssets||""}/></label><button className="button primary full">{editing?"Update spare part":"Insert spare part"}</button></form></section></div>}</main>
}
