"use client";
import {Banknote,CheckCircle2,Clock3,Plus,ReceiptText,X} from "lucide-react";
import {useEffect,useMemo,useState} from "react";
type Project={id:string;name:string;status:string;parentProjectName?:string};
type Payment={id:string;requestNumber:string;projectId:string;projectName:string;requesterName:string;payeeName:string;amount:number;currency:string;purpose:string;dueDate?:string;currentStatus:string;paymentReference?:string;workflow?:{id:string;status:string;current_step_order?:number;approval_steps?:any[]}|null};
type Perms={canPaymentRequest:boolean;canPaymentReview:boolean;canPaymentFinalApprove:boolean;canPaymentMarkPaid:boolean;canViewAllFinance:boolean};
const money=new Intl.NumberFormat("en-QA",{style:"currency",currency:"QAR"});
export default function PaymentsPage(){
 const[payments,setPayments]=useState<Payment[]>([]),[projects,setProjects]=useState<Project[]>([]),[perms,setPerms]=useState<Perms|null>(null),[open,setOpen]=useState(false),[paid,setPaid]=useState<Payment|null>(null),[error,setError]=useState("");
 async function refresh(){const[pr,rr,fr]=await Promise.all([fetch("/api/payment-requests",{cache:"no-store"}),fetch("/api/projects?compact=1",{cache:"no-store"}),fetch("/api/finance-permissions",{cache:"no-store"})]);const[p,r,f]=await Promise.all([pr.json(),rr.json(),fr.json()]);if(!pr.ok)throw new Error(p.error||"Unable to load payments");setPayments(p.payments||[]);setProjects(r.projects||[]);setPerms(f.permissions||null)}
 useEffect(()=>{refresh().catch(e=>setError(e.message))},[]);
 const pending=payments.filter(p=>["FINANCE_REVIEW","CEO_REVIEW"].includes(p.currentStatus)).length,ready=payments.filter(p=>p.currentStatus==="APPROVED_FOR_PAYMENT").length,paidCount=payments.filter(p=>p.currentStatus==="PAID").length;
 async function create(fd:FormData){const body={projectId:String(fd.get("projectId")),payeeName:String(fd.get("payeeName")),amount:Number(fd.get("amount")),purpose:String(fd.get("purpose")),details:String(fd.get("details")),dueDate:String(fd.get("dueDate")),invoiceReference:String(fd.get("invoiceReference"))};const r=await fetch("/api/payment-requests",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(!r.ok){setError(d.error||"Unable to create payment");return}setOpen(false);await refresh()}
 async function submit(p:Payment){const r=await fetch("/api/approvals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({entityType:"PAYMENT_REQUEST",entityId:p.id})}),d=await r.json();if(!r.ok){setError(d.error||"Unable to submit");return}await refresh()}
 async function decide(p:Payment,action:"APPROVE"|"REJECT"|"REQUEST_MODIFICATION"){if(!p.workflow?.id)return;const comment=action==="APPROVE"?"Approved":window.prompt(action==="REJECT"?"Reason for rejection":"Required modification")||"";const r=await fetch(`/api/approvals/${p.workflow.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action,comment})}),d=await r.json();if(!r.ok){setError(d.error||"Unable to process approval");return}await refresh()}
 async function markPaid(fd:FormData){if(!paid)return;const r=await fetch(`/api/payment-requests/${paid.id}/paid`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({paymentReference:String(fd.get("paymentReference"))})}),d=await r.json();if(!r.ok){setError(d.error||"Unable to mark paid");return}setPaid(null);await refresh()}
 return <main className="dashboard-main section-page"><section className="page-heading"><div><p className="eyebrow">Finance control</p><h1>Payment Requests</h1><p className="page-subtitle">Requester → Finance review → CEO approval → Ready for Payment → Paid.</p></div>{perms?.canPaymentRequest&&<button className="button primary" onClick={()=>setOpen(true)}><Plus size={16}/> New payment request</button>}</section>{error&&<p className="form-error">{error}</p>}
 <section className="finance-kpis"><button className="finance-kpi-button"><span className="finance-icon amber"><Clock3/></span><div><small>Awaiting approval</small><strong>{pending}</strong></div></button><button className="finance-kpi-button"><span className="finance-icon blue"><ReceiptText/></span><div><small>Ready for payment</small><strong>{ready}</strong></div></button><button className="finance-kpi-button"><span className="finance-icon teal"><CheckCircle2/></span><div><small>Paid</small><strong>{paidCount}</strong></div></button></section>
 <section className="budget-table-card"><div className="responsive-table"><table><thead><tr><th>Request</th><th>Project</th><th>Payee</th><th>Purpose</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{payments.map(p=><tr key={p.id}><td><strong>{p.requestNumber}</strong><small>{p.requesterName}</small></td><td>{p.projectName}</td><td>{p.payeeName}</td><td>{p.purpose}</td><td>{money.format(p.amount)}</td><td><span className="rag-badge blue">{p.currentStatus.replaceAll("_"," ")}</span></td><td><div className="table-actions">{p.currentStatus==="DRAFT"&&<button className="text-button" onClick={()=>submit(p)}>Submit</button>}{p.currentStatus==="FINANCE_REVIEW"&&perms?.canPaymentReview&&<><button className="text-button" onClick={()=>decide(p,"APPROVE")}>Approve</button><button className="text-button" onClick={()=>decide(p,"REQUEST_MODIFICATION")}>Modify</button><button className="text-button danger" onClick={()=>decide(p,"REJECT")}>Reject</button></>}{p.currentStatus==="CEO_REVIEW"&&perms?.canPaymentFinalApprove&&<><button className="text-button" onClick={()=>decide(p,"APPROVE")}>Final approve</button><button className="text-button danger" onClick={()=>decide(p,"REJECT")}>Reject</button></>}{p.currentStatus==="APPROVED_FOR_PAYMENT"&&perms?.canPaymentMarkPaid&&<button className="text-button" onClick={()=>setPaid(p)}>Mark paid</button>}</div></td></tr>)}{!payments.length&&<tr><td colSpan={7} className="empty-row">No payment requests yet.</td></tr>}</tbody></table></div></section>
 {open&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setOpen(false)}/><section className="modal-card activity-modal"><button className="modal-close inline" onClick={()=>setOpen(false)}><X/></button><h2>New payment request</h2><form action={create}><label>Project / sub-project<select name="projectId" required defaultValue=""><option value="">Choose</option>{projects.filter(p=>p.status!=="Closed").map(p=><option key={p.id} value={p.id}>{p.parentProjectName?`${p.parentProjectName} → `:""}{p.name}</option>)}</select></label><label>Payee / supplier<input name="payeeName" required/></label><div className="form-grid"><label>Amount QAR<input name="amount" type="number" min=".01" step=".01" required/></label><label>Due date<input name="dueDate" type="date"/></label></div><label>Purpose<input name="purpose" required/></label><label>Invoice reference<input name="invoiceReference"/></label><label>Details<textarea name="details" rows={3}/></label><button className="button primary full">Save draft</button></form></section></div>}
 {paid&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setPaid(null)}/><section className="modal-card activity-modal"><h2>Confirm payment</h2><p>{paid.requestNumber} · {money.format(paid.amount)}</p><form action={markPaid}><label>Bank/payment reference<input name="paymentReference" required/></label><button className="button primary full"><Banknote size={16}/> Mark as paid</button></form></section></div>}</main>
}
