"use client";
import { Clock3, Construction, ShieldCheck } from "lucide-react";
import { useParams, usePathname } from "next/navigation";
import { useSmartCareAuth } from "../components/auth-provider";

export default function ModulePlaceholderPage(){
 const pathname=usePathname(),params=useParams<{module:string}>(),{modules}=useSmartCareAuth();
 const module=modules.find(item=>item.path?.toLowerCase()===pathname.toLowerCase());
 const fallback=decodeURIComponent(String(params.module||"SmartCare Module")).replace(/[-_]/g," ");
 const title=module?.title||fallback.replace(/\b\w/g,c=>c.toUpperCase());
 return <main style={{minHeight:"calc(100vh - 68px)",display:"grid",placeItems:"center",padding:32,background:"linear-gradient(145deg,#eef5ff,#fff)"}}><section style={{width:"min(620px,100%)",padding:34,boxSizing:"border-box",textAlign:"center",background:"#fff",border:"1px solid #dbe5f4",borderRadius:24,boxShadow:"0 24px 70px rgba(0,49,103,.12)"}}><img src="/ibtechar-main-logo.png" alt="Ibtechar" style={{display:"block",width:190,height:"auto",maxWidth:"100%",margin:"0 auto 22px"}}/><span style={{width:"max-content",maxWidth:"100%",margin:"0 auto 18px",padding:"8px 12px",display:"flex",alignItems:"center",justifyContent:"center",gap:7,color:"#7450a8",background:"#f2ecfb",border:"1px solid #e2d5f5",borderRadius:999,fontSize:10,fontWeight:750,textTransform:"uppercase",letterSpacing:".08em"}}><Construction size={16}/> Module in development</span><p style={{margin:"0 0 7px",color:"#0050c2",fontSize:10,fontWeight:800,textTransform:"uppercase",letterSpacing:".12em"}}>Ibtechar SmartCare workspace</p><h1 style={{margin:"0 0 14px",color:"#003167",fontSize:"clamp(30px,4vw,44px)",letterSpacing:"-1px"}}>{title}</h1><p style={{maxWidth:540,margin:"0 auto",color:"#587086",fontSize:13,lineHeight:1.8}}>This module has been created successfully and is currently under construction. Its workflow and access-controlled features will appear here when implementation is complete.</p><div style={{margin:"28px auto 24px",paddingTop:22,display:"flex",alignItems:"center",justifyContent:"center",flexWrap:"wrap",gap:22,borderTop:"1px solid #e7edf5",color:"#34536f",fontSize:10,fontWeight:650}}><span style={{display:"flex",alignItems:"center",gap:7}}><Clock3 size={16} color="#0050c2"/> Implementation in progress</span><span style={{display:"flex",alignItems:"center",gap:7}}><ShieldCheck size={16} color="#0050c2"/> SmartCare access controls active</span></div><small style={{color:"#8191a1",fontSize:9}}>Ibtechar SmartCare · Developed by Seif Khlif</small></section></main>
}
