import {createAssetLoan,listAssetLoans,listAssets,listProjectsForUser,updateAssetLoan} from "../../lib/database";
import {getSmartCareActor,hasSmartCarePermission} from "../../lib/auth-server";

const managers=["CEO","ADMIN","PROJECT_MANAGER","MANAGER","TECHNICIAN"];

export async function GET(request:Request){try{const actor=await getSmartCareActor(request);if(!actor)return Response.json({error:"Unauthorized"},{status:401});if(!await hasSmartCarePermission(request,"asset_loans","view"))return Response.json({error:"Asset-loan access required"},{status:403});const[loans,projects,assets]=await Promise.all([listAssetLoans(),listProjectsForUser(actor),managers.includes(actor.role)?listAssets(false):Promise.resolve([])]);return Response.json({loans,projects:projects.map(p=>({id:p.id,name:p.name})),assets:assets.filter(a=>!["On loan","Out of service","Archived"].includes(a.status)).map(a=>({id:a.id,name:a.name,category:a.category,location:a.location,status:a.status})),canManage:managers.includes(actor.role)});}catch(error){return Response.json({error:error instanceof Error?error.message:"Unable to load asset loans"},{status:500});}}

export async function POST(request:Request){try{const actor=await getSmartCareActor(request);if(!actor)return Response.json({error:"Unauthorized"},{status:401});if(!await hasSmartCarePermission(request,"asset_loans","create"))return Response.json({error:"Asset-loan create permission required"},{status:403});const loan=await createAssetLoan(await request.json(),actor);return Response.json({loan},{status:201});}catch(error){return Response.json({error:error instanceof Error?error.message:"Unable to create asset loan"},{status:400});}}

export async function PATCH(request:Request){try{const actor=await getSmartCareActor(request);if(!actor)return Response.json({error:"Unauthorized"},{status:401});const body=await request.json() as Record<string,unknown>,action=String(body.action||"");if(action!=="cancel"&&!managers.includes(actor.role))return Response.json({error:"A manager or asset custodian must complete this action"},{status:403});const loan=await updateAssetLoan(String(body.id||""),body,actor);return Response.json({loan});}catch(error){return Response.json({error:error instanceof Error?error.message:"Unable to update asset loan"},{status:400});}}
