"use client";

import { CalendarClock, ChevronRight, Clock3, PackageCheck, RefreshCw, Truck, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { OrderProgressRecord } from "../lib/database";

const statuses = ["Purchase Request Created", "Under Review", "Approved", "Rejected", "PO Pending", "PO Issued", "Supplier Confirmed", "In Preparation", "In Production", "Ready for Shipment", "Shipped", "In Transit", "Customs Clearance", "Local Delivery", "Partially Delivered", "Delivered", "Received", "Delayed", "On Hold", "Cancelled", "Issue / Problem"];
const activeStatuses = new Set(statuses.filter(status => !["Rejected", "Cancelled", "Received", "Delivered"].includes(status)));

export default function OrderProgressPage() {
  const [items, setItems] = useState<OrderProgressRecord[]>([]);
  const [selected, setSelected] = useState<OrderProgressRecord | null>(null);
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("all");
  const [summaryFilter, setSummaryFilter] = useState("all");
  const [message, setMessage] = useState("");
  const [saving, setSaving] = useState(false);

  async function refresh() { const response = await fetch("/api/order-progress", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to load Order Progress"); setItems(data.items || []); }
  useEffect(() => { refresh().catch(error => setMessage(error.message)); }, []);
  useEffect(() => { const requested = new URLSearchParams(window.location.search).get("open"); if (requested) fetch(`/api/order-progress/${requested}`).then(response => response.json()).then(data => { if (data.item) setSelected(data.item); }).catch(() => {}); }, []);

  const filtered = useMemo(() => items.filter(item => {
    const haystack = `${item.itemName} ${item.purchaseRequestId} ${item.purchaseOrderId || ""} ${item.project} ${item.supplier} ${item.requestedByName}`.toLowerCase();
    const summaryMatches = summaryFilter === "all" || (summaryFilter === "active" && activeStatuses.has(item.status)) || (summaryFilter === "approved" && item.status === "Approved") || (summaryFilter === "production" && ["In Preparation", "In Production"].includes(item.status)) || (summaryFilter === "shipping" && ["Shipped", "In Transit"].includes(item.status)) || (summaryFilter === "delayed" && item.status === "Delayed") || (summaryFilter === "delivered" && ["Delivered", "Received"].includes(item.status));
    return (!query || haystack.includes(query.toLowerCase())) && (status === "all" || item.status === status) && summaryMatches;
  }), [items, query, status, summaryFilter]);
  const active = items.filter(item => activeStatuses.has(item.status));
  const average = active.length ? Math.round(active.reduce((sum, item) => sum + item.progressPercentage, 0) / active.length) : 0;
  const count = (predicate: (item: OrderProgressRecord) => boolean) => items.filter(predicate).length;

  async function saveProgress(formData: FormData) {
    if (!selected) return;
    setSaving(true); setMessage("");
    try {
      const response = await fetch(`/api/order-progress/${selected.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ progressPercentage: Number(formData.get("progressPercentage")), status: String(formData.get("status")), expectedDeliveryDate: String(formData.get("expectedDeliveryDate") || ""), actualDeliveryDate: String(formData.get("actualDeliveryDate") || ""), supplier: String(formData.get("supplier") || ""), trackingReference: String(formData.get("trackingReference") || ""), responsibleUserId: String(formData.get("responsibleUserId") || ""), note: String(formData.get("note") || "") }) });
      const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to update progress");
      setSelected(data.item); await refresh();
    } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to update progress"); } finally { setSaving(false); }
  }

  return <main className="dashboard-main section-page order-progress-page">
    <section className="page-heading"><div><p className="eyebrow">Procurement visibility</p><h1>Order Progress</h1><p className="page-subtitle">Track every purchase request from approval through supplier preparation, shipping, receiving and asset registration.</p></div><button className="button secondary" type="button" onClick={() => refresh()}><RefreshCw size={16}/> Refresh</button></section>
    {message && <p className="form-error">{message}</p>}
    <section className="summary-strip order-progress-summary interactive-summary-strip"><button type="button" className={`summary-card-button ${summaryFilter==="active"?"selected":""}`} onClick={()=>{setSummaryFilter("active");setStatus("all")}}><span className="summary-icon blue"><PackageCheck size={20}/></span><div><strong>{active.length}</strong><small>Active items</small></div></button><button type="button" className={`summary-card-button ${summaryFilter==="approved"?"selected":""}`} onClick={()=>{setSummaryFilter("approved");setStatus("all")}}><span className="summary-icon teal"><Clock3 size={20}/></span><div><strong>{count(item => item.status === "Approved")}</strong><small>Approved</small></div></button><button type="button" className={`summary-card-button ${summaryFilter==="production"?"selected":""}`} onClick={()=>{setSummaryFilter("production");setStatus("all")}}><span className="summary-icon amber"><Clock3 size={20}/></span><div><strong>{count(item => ["In Preparation", "In Production"].includes(item.status))}</strong><small>Preparation / production</small></div></button><button type="button" className={`summary-card-button ${summaryFilter==="shipping"?"selected":""}`} onClick={()=>{setSummaryFilter("shipping");setStatus("all")}}><span className="summary-icon blue"><Truck size={20}/></span><div><strong>{count(item => ["Shipped", "In Transit"].includes(item.status))}</strong><small>Shipped / in transit</small></div></button><button type="button" className={`summary-card-button ${summaryFilter==="delayed"?"selected":""}`} onClick={()=>{setSummaryFilter("delayed");setStatus("all")}}><span className="summary-icon coral"><CalendarClock size={20}/></span><div><strong>{count(item => item.status === "Delayed")}</strong><small>Delayed</small></div></button><button type="button" className={`summary-card-button ${summaryFilter==="delivered"?"selected":""}`} onClick={()=>{setSummaryFilter("delivered");setStatus("all")}}><span className="summary-icon teal"><PackageCheck size={20}/></span><div><strong>{count(item => ["Delivered", "Received"].includes(item.status))}</strong><small>Delivered / received</small></div></button><button type="button" className={`summary-card-button ${summaryFilter==="active"?"selected":""}`} onClick={()=>{setSummaryFilter("active");setStatus("all")}} title="Show active items used in this average"><span className="summary-icon blue"><Clock3 size={20}/></span><div><strong>{average}%</strong><small>Average active progress</small></div></button></section>
    <section className="toolbar-card"><label className="page-search"><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search item, PR, PO, project, supplier or requester"/></label><label className="filter-select"><select value={status} onChange={event => {setStatus(event.target.value);setSummaryFilter("all")}}><option value="all">All statuses</option>{statuses.map(value => <option key={value}>{value}</option>)}</select></label><span className="result-count">{filtered.length} items</span></section>
    <section className="budget-table-card"><div className="responsive-table"><table className="order-progress-table"><thead><tr><th>Item</th><th>Request / project</th><th>Supplier</th><th>Progress</th><th>Status</th><th>Expected delivery</th><th>Updated</th><th/></tr></thead><tbody>{filtered.map(item => <tr key={item.id} className={item.status === "Delayed" || item.status === "Issue / Problem" ? "priority-row" : ""}><td><strong>{item.itemName}</strong><small>Qty {item.quantity}</small></td><td><strong>{item.purchaseRequestId}</strong><small>{item.project} · {item.requestedByName || "Requester not recorded"}</small></td><td>{item.supplier || "Not confirmed"}<small>{item.purchaseOrderId || "PO pending"}</small></td><td><div className="order-progress-value"><strong>{item.progressPercentage}%</strong><div className="progress-track"><i style={{ width: `${item.progressPercentage}%` }}/></div></div></td><td><span className={`status-pill ${item.status === "Delayed" || item.status === "Issue / Problem" ? "warning" : item.status === "Received" ? "healthy" : "due"}`}><i/>{item.status}</span></td><td>{item.expectedDeliveryDate || "Not set"}</td><td><small>{new Date(item.updatedAt).toLocaleDateString()}</small><small>{item.updatedByName || "System"}</small></td><td><button className="text-button" type="button" onClick={() => setSelected(item)}>View / update <ChevronRight size={15}/></button></td></tr>)}</tbody></table></div>{!filtered.length && <p className="empty-row">No Order Progress items match these filters.</p>}</section>
    {selected && <div className="modal-layer drawer-layer"><button className="modal-backdrop" type="button" onClick={() => setSelected(null)} aria-label="Close Order Progress details"/><section className="issue-drawer order-progress-drawer"><div className="drawer-header"><div><p className="eyebrow">Order Progress detail</p><h2>{selected.itemName}</h2><small>{selected.purchaseRequestId} · {selected.project}</small></div><button className="modal-close inline" type="button" onClick={() => setSelected(null)} aria-label="Close"><X size={20}/></button></div><form action={saveProgress}><label>Progress %<input name="progressPercentage" type="number" min="0" max="100" step="1" defaultValue={selected.progressPercentage} required/></label><label>Status<select name="status" defaultValue={selected.status}>{statuses.map(value => <option key={value}>{value}</option>)}</select></label><div className="form-grid"><label>Expected delivery<input name="expectedDeliveryDate" type="date" defaultValue={selected.expectedDeliveryDate || ""}/></label><label>Actual delivery<input name="actualDeliveryDate" type="date" defaultValue={selected.actualDeliveryDate || ""}/></label></div><label>Supplier<input name="supplier" defaultValue={selected.supplier}/></label><label>Tracking / reference<input name="trackingReference" defaultValue={selected.trackingReference}/></label><label>Responsible user ID<input name="responsibleUserId" defaultValue={selected.responsibleUserId || ""} placeholder="Optional user ID"/></label><label>Update note<textarea name="note" rows={4} placeholder="Describe the supplier or delivery update"/></label><button className="button primary full" disabled={saving}>{saving ? "Saving…" : "Save progress update"}</button></form><section className="order-progress-timeline"><h3>Progress timeline</h3>{selected.updates.map(update => <article key={update.id}><time>{new Date(update.createdAt).toLocaleString()}</time><strong>{update.newPercentage}% · {update.newStatus}</strong><small>Updated by {update.createdByName || "System"}</small>{update.note && <p>{update.note}</p>}</article>)}</section></section></div>}
  </main>;
}
