"use client";
import { ArrowDown, ArrowUp, LayoutPanelTop, Plus, ShieldCheck } from "lucide-react";
import { useEffect,useState } from "react";
import type { ModuleRecord,UserPermissionRecord,UserRecord } from "../lib/database";
import { useSmartCareAuth } from "../components/auth-provider";
const actions=["canView","canCreate","canEdit","canDelete","canApprove"] as const;
type Project={id:string;name:string};type FinancePermissionState={userId:string;canViewAllFinance:boolean;canBudgetRequest:boolean;canBudgetReview:boolean;canBudgetFinalApprove:boolean;canPaymentRequest:boolean;canPaymentReview:boolean;canPaymentFinalApprove:boolean;canPaymentMarkPaid:boolean;canInvoiceRequest:boolean;canInvoiceReview:boolean;canInvoiceIssue:boolean;canInvoiceMarkSent:boolean;canInvoiceMarkReceived:boolean};
const financePermissionFields=[
["canViewAllFinance","View all finance"],["canBudgetRequest","Request budget"],["canBudgetReview","Review budget"],["canBudgetFinalApprove","Final approve budget"],
["canPaymentRequest","Request payment"],["canPaymentReview","Review payment"],["canPaymentFinalApprove","Final approve payment"],["canPaymentMarkPaid","Mark payment paid"],
["canInvoiceRequest","Request invoice"],["canInvoiceReview","Review invoice"],["canInvoiceIssue","Issue invoice"],["canInvoiceMarkSent","Mark invoice sent"],["canInvoiceMarkReceived","Mark invoice received"]
] as const;type ProjectAccess={userId:string;projectId:string;projectName:string;canView:boolean;canCreate:boolean;canEdit:boolean;canApprove:boolean};
export default function AccessControlPage(){const{user}=useSmartCareAuth();const[users,setUsers]=useState<UserRecord[]>([]),[modules,setModules]=useState<ModuleRecord[]>([]),[permissions,setPermissions]=useState<UserPermissionRecord[]>([]),[projects,setProjects]=useState<Project[]>([]),[projectAccess,setProjectAccess]=useState<ProjectAccess[]>([]),[selected,setSelected]=useState<string>(""),[financePermissions,setFinancePermissions]=useState<FinancePermissionState|null>(null),[message,setMessage]=useState("");
 async function loadUsers(){const d=await fetch("/api/users",{cache:"no-store"}).then(r=>r.json());setUsers(d.users||[]);if(!selected&&d.users?.length)setSelected(d.users[0].id)}
 async function loadAccess(id:string){const d=await fetch(`/api/access-control?userId=${id}`,{cache:"no-store"}).then(r=>r.json());setModules(d.modules||[]);setPermissions(d.permissions||[]);setProjects(d.projects||[]);setProjectAccess(d.projectAccess||[]);const f=await fetch(`/api/finance-permissions?userId=${encodeURIComponent(id)}`,{cache:"no-store"}).then(r=>r.json());setFinancePermissions(f.permissions||null)}
 useEffect(()=>{loadUsers()},[]);useEffect(()=>{if(selected)loadAccess(selected)},[selected]);
 if(user&&!['ADMIN','MANAGER'].includes(user.role))return <main className="dashboard-main section-page"><h1>Access restricted</h1><p>Only Admin and Manager users can change interface permissions.</p></main>;
 function value(moduleKey:string,key:typeof actions[number]){return Boolean(permissions.find(p=>p.moduleKey===moduleKey)?.[key])}
 async function toggle(moduleKey:string,key:typeof actions[number],checked:boolean){const current=permissions.find(p=>p.moduleKey===moduleKey);const body={userId:selected,moduleKey,...current,[key]:checked};const r=await fetch("/api/access-control",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(r.ok)setPermissions(p=>[...p.filter(x=>x.moduleKey!==moduleKey),d.permission]);}
 async function toggleAll(moduleKey:string,checked:boolean){const current=permissions.find(p=>p.moduleKey===moduleKey);const body={userId:selected,moduleKey,...current,...Object.fromEntries(actions.map(action=>[action,checked]))};const r=await fetch("/api/access-control",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(r.ok)setPermissions(p=>[...p.filter(x=>x.moduleKey!==moduleKey),d.permission]);}
 async function moduleToggle(m:ModuleRecord){await fetch("/api/access-control",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({key:m.key,enabled:!m.enabled})});await loadAccess(selected)}
 async function moveModule(index:number,direction:-1|1){const target=index+direction;if(target<0||target>=modules.length)return;const current=modules[index],other=modules[target];await Promise.all([fetch("/api/access-control",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({key:current.key,sortOrder:other.sortOrder})}),fetch("/api/access-control",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({key:other.key,sortOrder:current.sortOrder})})]);await loadAccess(selected)}
 function projectValue(projectId:string,key:"canView"|"canCreate"|"canEdit"|"canApprove"){return Boolean(projectAccess.find(p=>p.projectId===projectId)?.[key])}
 async function toggleProject(projectId:string,key:"canView"|"canCreate"|"canEdit"|"canApprove",checked:boolean){const current=projectAccess.find(p=>p.projectId===projectId);const r=await fetch("/api/access-control",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"project_access",userId:selected,projectId,...current,[key]:checked})});if(r.ok)await loadAccess(selected)}
 async function toggleFinance(key:typeof financePermissionFields[number][0],checked:boolean){if(!financePermissions)return;const next={...financePermissions,[key]:checked,userId:selected};const r=await fetch("/api/finance-permissions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(next)});const d=await r.json();if(r.ok)setFinancePermissions(d.permissions);else setMessage(d.error||"Unable to save finance permission");}
 async function addModule(fd:FormData){const title=String(fd.get("title")||""),path=String(fd.get("path")||"");const key=title.toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"");const r=await fetch("/api/access-control",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"module",key,title,path,enabled:true,sortOrder:modules.length*10+20})});setMessage(r.ok?"Module added to the navigation catalog.":"Unable to add module.");await loadAccess(selected)}
 return <main className="dashboard-main section-page"><section className="page-heading"><div><p className="eyebrow">Admin / Manager control</p><h1>Interface & Access Management</h1><p className="page-subtitle">Enable or hide modules globally and assign view/create/edit/delete/approve permissions per SmartCare user.</p></div><span className="pilot-badge"><ShieldCheck size={16}/> RBAC</span></section>
 <section className="toolbar-card"><label className="filter-select">Configure user<select value={selected == null ? "" : String(selected)} onChange={e=>setSelected(e.target.value)}>{users.map(u=><option key={u.id} value={String(u.id)}>{u.name} · {u.role}</option>)}</select></label><span className="field-note">Admin/Manager keep full administrative access to avoid lockout.</span></section>
 <section className="budget-table-card"><div className="panel-heading"><div><h2>Module permission matrix</h2><p>Global Enabled controls navigation visibility. User permissions control allowed actions. Use All in a module row to grant or clear every action at once.</p></div></div><div className="responsive-table"><table><thead><tr><th>Module</th><th>Order</th><th>Enabled</th><th>All</th><th>View</th><th>Create</th><th>Edit</th><th>Delete</th><th>Approve</th></tr></thead><tbody>{modules.map((m,index)=>{const allChecked=actions.every(action=>value(m.key,action));return <tr key={m.key}><td><strong>{m.title}</strong><small>{m.path}</small></td><td><button className="text-button" onClick={()=>moveModule(index,-1)} disabled={!index}><ArrowUp size={14}/></button><button className="text-button" onClick={()=>moveModule(index,1)} disabled={index===modules.length-1}><ArrowDown size={14}/></button></td><td><input type="checkbox" checked={m.enabled} onChange={()=>moduleToggle(m)}/></td><td><input type="checkbox" checked={allChecked} onChange={event=>toggleAll(m.key,event.target.checked)} aria-label={`Select all permissions for ${m.title}`}/></td>{actions.map(a=><td key={a}><input type="checkbox" checked={value(m.key,a)} onChange={e=>toggle(m.key,a,e.target.checked)}/></td>)}</tr>})}</tbody></table></div></section>
 <section className="budget-table-card"><div className="panel-heading"><div><h2>Finance permission matrix</h2><p>Granular financial duties. Only Admin can change these permissions. Approval actions are also enforced server-side and users cannot approve their own requests.</p></div></div><div className="responsive-table"><table><thead><tr><th>Finance action</th><th>Allowed</th></tr></thead><tbody>{financePermissionFields.map(([key,label])=><tr key={key}><td><strong>{label}</strong></td><td><input type="checkbox" checked={Boolean(financePermissions?.[key])} disabled={user?.role!=="ADMIN"} onChange={e=>toggleFinance(key,e.target.checked)}/></td></tr>)}</tbody></table></div></section>
<section className="budget-table-card"><div className="panel-heading"><div><h2>Project-based access</h2><p>Assign projects independently from role. Data is filtered server-side for users without Admin or Manager access.</p></div></div><div className="responsive-table"><table><thead><tr><th>Project</th><th>View</th><th>Create</th><th>Edit</th><th>Approve</th></tr></thead><tbody>{projects.map(p=><tr key={p.id}><td><strong>{p.name}</strong></td>{(["canView","canCreate","canEdit","canApprove"] as const).map(key=><td key={key}><input type="checkbox" checked={projectValue(p.id,key)} onChange={e=>toggleProject(p.id,key,e.target.checked)}/></td>)}</tr>)}</tbody></table></div></section>
 <section className="diagnostic-form-card"><div className="assistant-header"><span><LayoutPanelTop/></span><div><h2>Add navigation module</h2><p>Use an existing SmartCare route when adding a menu entry.</p></div></div><form action={addModule}><div className="form-grid"><label>Module title<input name="title" required placeholder="Quality Checks"/></label><label>Route<input name="path" required placeholder="/reports"/></label></div><button className="button secondary"><Plus size={16}/> Add module</button>{message&&<small className="field-note">{message}</small>}</form></section></main>}

