"use client";
import { ArrowLeft, BrainCircuit, CheckCircle2, ClipboardList, MapPin, PackageCheck, Pencil, ReceiptText, ShieldCheck, Wrench } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useSmartCareAuth } from "../../components/auth-provider";
type Asset={id:string;name:string;manufacturer:string;model:string;serialNumber:string;category:string;location:string;project:string;status:string;tone:string;health:number;acquisitionCost:number;residualValue:number;usefulLifeYears:number;purchaseDate:string;installedOn:string;warrantyUntil:string;insured:boolean;openBox:boolean;damagePercent:number;purchaseOrderId?:string;notes?:string;owner?:string;imageData?:string};
type Project={id:string;name:string};
const toneForStatus=(status:string)=>status==="Operational"?"healthy":status==="Out of service"?"warning":"due";
type PurchaseOrder={id:string;po_date:string;supplier:string;equipment:string;total:number;status:string;received_at?:string;received_condition?:string;received_manufacturer?:string;received_model?:string;received_serial_number?:string;received_warranty_until?:string};
type Diagnostic={id:number;symptom:string;result?:{title?:string;recommendedAction?:string};createdAt:string};
type WorkOrder={id:string;title:string;status:string;createdAt:string;startedAt?:string;completedAt?:string;resolution?:string;assignee?:string};
type ServiceEvent={id:string;type:string;title:string;performedBy:string;performedAt:string;notes:string};
type Bundle={asset:Asset;purchaseOrder?:PurchaseOrder|null;diagnostics?:Diagnostic[];orders?:WorkOrder[];events?:ServiceEvent[]};
type TimelineItem={key:string;date:string;title:string;description:string;kind:"purchase"|"receive"|"asset"|"ai"|"wo"|"repair"|"complete"};
const iconFor=(kind:TimelineItem["kind"])=>kind==="purchase"?ReceiptText:kind==="receive"?PackageCheck:kind==="ai"?BrainCircuit:kind==="wo"?ClipboardList:kind==="complete"?CheckCircle2:Wrench;
export default function AssetDetailPage({params}:{params:Promise<{id:string}>}){
 const{user}=useSmartCareAuth();
 const[bundle,setBundle]=useState<Bundle|null>(null),[locations,setLocations]=useState<{name:string}[]>([]),[projects,setProjects]=useState<Project[]>([]),[editing,setEditing]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const isAdmin=user?.role==="ADMIN";
 async function refresh(){const{id}=await params;const[a,l,p]=await Promise.all([fetch(`/api/assets/${id}`,{cache:"no-store"}).then(r=>r.json()),fetch("/api/locations").then(r=>r.json()),fetch("/api/projects",{cache:"no-store"}).then(r=>r.json())]);setBundle(a);setLocations(l.locations||[]);setProjects(p.projects||[])}
 useEffect(()=>{refresh().catch(()=>setError("Unable to load asset."))},[params]);
 const asset=bundle?.asset;
 const timeline=useMemo(()=>{if(!bundle?.asset)return[];const rows:TimelineItem[]=[];const po=bundle.purchaseOrder;if(po){rows.push({key:`po-${po.id}`,date:po.po_date,title:`Purchase Order ${po.id}`,description:`${po.equipment} ordered from ${po.supplier} · QAR ${Number(po.total||0).toLocaleString()}.`,kind:"purchase"});if(po.received_at)rows.push({key:`recv-${po.id}`,date:po.received_at,title:"Equipment Received",description:`${po.received_condition||"Received"} · ${bundle.asset.location}${po.received_warranty_until?` · Warranty to ${po.received_warranty_until}`:""}.`,kind:"receive"});}
 for(const e of bundle.events||[])rows.push({key:e.id,date:e.performedAt,title:e.title,description:e.notes||e.performedBy||"Lifecycle event",kind:e.type==="Repair Started"?"repair":e.type==="Repair Completed"?"complete":"asset"});
 for(const d of bundle.diagnostics||[])rows.push({key:`diag-${d.id}`,date:d.createdAt,title:`AI Diagnostic #${d.id}`,description:`${d.symptom}${d.result?.recommendedAction?` · ${d.result.recommendedAction}`:""}`,kind:"ai"});
 for(const w of bundle.orders||[]){rows.push({key:`wo-${w.id}`,date:w.createdAt,title:`Work Order ${w.id} Created`,description:`${w.title} · ${w.status}.`,kind:"wo"});}
 return rows.sort((a,b)=>new Date(a.date).getTime()-new Date(b.date).getTime())},[bundle]);
 async function save(fd:FormData){if(!asset)return;setSaving(true);setError("");try{const nextStatus=String(fd.get("status")||asset.status);const payload:Record<string,unknown>={location:String(fd.get("location")||asset.location),status:nextStatus,tone:toneForStatus(nextStatus),health:Number(fd.get("health")||asset.health),warrantyUntil:String(fd.get("warrantyUntil")||""),insured:fd.get("insured")==="on",notes:String(fd.get("notes")||"")};
  if(isAdmin){Object.assign(payload,{name:String(fd.get("name")||asset.name),category:String(fd.get("category")||asset.category),manufacturer:String(fd.get("manufacturer")||""),model:String(fd.get("model")||""),serialNumber:String(fd.get("serialNumber")||""),installedOn:String(fd.get("installedOn")||""),project:String(fd.get("project")||asset.project),owner:String(fd.get("owner")||""),acquisitionCost:Number(fd.get("acquisitionCost")||0),residualValue:Number(fd.get("residualValue")||0),usefulLifeYears:Number(fd.get("usefulLifeYears")||5),purchaseDate:String(fd.get("purchaseDate")||"")});const image=fd.get("image") as File|null;if(image?.size){const upload=new FormData();upload.set("file",image);upload.set("bucket","asset-images");const response=await fetch("/api/storage/upload",{method:"POST",body:upload}),result=await response.json() as {path?:string;error?:string};if(!response.ok||!result.path)throw new Error(result.error||"Image upload failed");payload.imagePath=result.path;}}
  const r=await fetch(`/api/assets/${asset.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to update asset.");setEditing(false);await refresh()}catch(e){setError(e instanceof Error?e.message:"Unable to update asset.")}finally{setSaving(false)}}
 if(!asset)return <main className="dashboard-main section-page">Loading asset…</main>;
 const age=Math.max(0,(Date.now()-new Date(asset.purchaseDate||Date.now()).getTime())/(365.25*86400000));const current=Math.max(asset.residualValue,asset.acquisitionCost-(asset.acquisitionCost-asset.residualValue)*Math.min(1,age/Math.max(1,asset.usefulLifeYears)))*(1-Math.min(0.95,asset.damagePercent/100));
 return <main className="dashboard-main section-page"><Link className="back-link" href="/assets"><ArrowLeft size={16}/> Back to assets</Link><section className="detail-hero"><div><span className={`status-pill ${asset.tone}`}><i/>{asset.status}</span><h1>{asset.name}</h1><p>{asset.id} · {asset.manufacturer} · {asset.model}</p></div><div className="heading-actions"><Link className="button primary" href={`/ai-assistant?asset=${encodeURIComponent(asset.id)}`}><BrainCircuit size={17}/> Diagnose with AI</Link><Link className="button secondary" href={`/work-orders?new=1&asset=${asset.id}`}><Wrench size={17}/> Create work order</Link><button className="button secondary" onClick={()=>setEditing(true)}><Pencil size={16}/> Edit asset</button></div></section>{error&&<p className="form-error">{error}</p>}
 <section className="detail-kpis"><article><span><small>Health</small><strong>{asset.health}%</strong></span></article><article><span><small>Purchase value</small><strong>QAR {asset.acquisitionCost.toLocaleString()}</strong></span></article><article><span><small>Current value</small><strong>QAR {current.toLocaleString(undefined,{maximumFractionDigits:0})}</strong></span></article><article><span><small>Warranty</small><strong>{asset.warrantyUntil||"Not recorded"}</strong></span></article></section>
 <section className="detail-section"><div className="section-title"><h2>Operational asset record</h2></div><dl className="asset-data-grid"><div><dt>Project</dt><dd>{asset.project}</dd></div><div><dt>Original PO</dt><dd>{asset.purchaseOrderId||"Not linked"}</dd></div><div><dt>Location</dt><dd><MapPin size={14}/>{asset.location}</dd></div><div><dt>Insurance</dt><dd>{asset.insured?"Insured":"Not insured"}</dd></div><div><dt>Condition adjustment</dt><dd>{asset.damagePercent}% damage · {asset.openBox?"Open box":"Sealed at purchase"}</dd></div><div><dt>Serial</dt><dd>{asset.serialNumber}</dd></div><div><dt>Useful life</dt><dd>{asset.usefulLifeYears} years</dd></div><div><dt>Description</dt><dd>{asset.notes||"No description recorded"}</dd></div></dl></section>
 <section className="detail-section"><div className="section-title"><div><h2>Asset History / Timeline</h2><p>Purchase, receiving, AI diagnosis and repair stay with this equipment record.</p></div></div><div className="asset-timeline">{timeline.map((item,index)=>{const Icon=iconFor(item.kind);return <article className="asset-timeline-item" key={item.key}><div className="asset-timeline-marker"><span><Icon size={17}/></span>{index<timeline.length-1&&<i/>}</div><div><time>{item.date?new Date(item.date).toLocaleString("en-QA",{dateStyle:"medium",timeStyle:item.date.includes("T")?"short":undefined}):"Date not recorded"}</time><h3>{item.title}</h3><p>{item.description}</p></div></article>})}{!timeline.length&&<p className="empty-row">No lifecycle events recorded yet.</p>}</div></section>
 {editing&&<div className={`modal-layer ${isAdmin?"drawer-layer":""}`}><button className="modal-backdrop" onClick={()=>setEditing(false)}/>{isAdmin?<section className="issue-drawer"><div className="drawer-header"><div><p className="eyebrow">Admin asset control</p><h2>Edit full asset details</h2></div><button className="modal-close inline" type="button" onClick={()=>setEditing(false)}>×</button></div><form action={save}>
  <div className="form-grid"><label>Asset name<input name="name" required defaultValue={asset.name}/></label><label>Category<select name="category" defaultValue={asset.category}><option>FDM 3D Printer</option><option>CNC Router</option><option>RF CO₂ Laser Engraver</option><option>Laser Cutter</option><option>Technical Furniture</option><option>Other Equipment</option></select></label></div>
  <div className="form-grid"><label>Manufacturer<input name="manufacturer" defaultValue={asset.manufacturer}/></label><label>Model<input name="model" defaultValue={asset.model}/></label></div>
  <label>Replace equipment photo<input name="image" type="file" accept="image/jpeg,image/png,image/webp"/></label><label>Serial number<input name="serialNumber" defaultValue={asset.serialNumber}/></label>
  <div className="form-grid"><label>Location<select name="location" defaultValue={asset.location}>{locations.map(l=><option key={l.name}>{l.name}</option>)}</select></label><label>Status<select name="status" defaultValue={asset.status}><option>Operational</option><option>Awaiting commissioning</option><option>Maintenance due</option><option>Out of service</option></select></label></div>
  <div className="form-grid"><label>Installation date<input type="date" name="installedOn" defaultValue={asset.installedOn||""}/></label><label>Warranty until<input type="date" name="warrantyUntil" defaultValue={asset.warrantyUntil||""}/></label></div>
  <div className="form-grid"><label>Project<select name="project" defaultValue={asset.project}>{projects.map(p=><option key={p.id}>{p.name}</option>)}</select></label><label>Responsible team<input name="owner" defaultValue={asset.owner||"Technical Services"}/></label></div>
  <div className="form-grid"><label>Acquisition cost (QAR)<input type="number" min="0" step=".01" name="acquisitionCost" defaultValue={asset.acquisitionCost}/></label><label>Residual value (QAR)<input type="number" min="0" step=".01" name="residualValue" defaultValue={asset.residualValue}/></label></div>
  <div className="form-grid"><label>Useful life (years)<input type="number" min="1" name="usefulLifeYears" defaultValue={asset.usefulLifeYears}/></label><label>Purchase date<input type="date" name="purchaseDate" defaultValue={asset.purchaseDate||""}/></label></div>
  <label>Health %<input name="health" type="number" min="0" max="100" defaultValue={asset.health}/></label><label>Description<textarea name="notes" rows={4} defaultValue={asset.notes||""} placeholder="Equipment condition, usage note or important description"/></label><label className="check-filter"><input name="insured" type="checkbox" defaultChecked={asset.insured}/> Insured</label><button className="button primary full" disabled={saving}><ShieldCheck size={16}/> {saving?"Saving…":"Save full asset details"}</button></form></section>:<section className="modal-card activity-modal"><h2>Edit status and location</h2><form action={save}><label>Location<select name="location" defaultValue={asset.location}>{locations.map(l=><option key={l.name}>{l.name}</option>)}</select></label><label>Status<select name="status" defaultValue={asset.status}><option>Operational</option><option>Awaiting commissioning</option><option>Maintenance due</option><option>Out of service</option></select></label><label>Health %<input name="health" type="number" min="0" max="100" defaultValue={asset.health}/></label><label>Description<textarea name="notes" rows={4} defaultValue={asset.notes||""} placeholder="Equipment condition, usage note or important description"/></label><label>Warranty until<input name="warrantyUntil" type="date" defaultValue={asset.warrantyUntil}/></label><label className="check-filter"><input name="insured" type="checkbox" defaultChecked={asset.insured}/> Insured</label><button className="button primary full" disabled={saving}><ShieldCheck size={16}/> {saving?"Saving…":"Save asset update"}</button></form></section>}</div>}</main>
}
