begin;

create table if not exists public.order_progress (
  id uuid primary key default gen_random_uuid(),
  purchase_request_id text not null unique references public.purchase_requests(id) on delete restrict,
  purchase_request_item_id text,
  purchase_order_id text references public.purchase_orders(id) on delete set null,
  project_id uuid not null references public.projects(id) on delete restrict,
  requested_by uuid references public.profiles(id) on delete set null,
  responsible_user_id uuid references public.profiles(id) on delete set null,
  item_name text not null,
  description text not null default '',
  quantity integer not null default 1 check (quantity > 0),
  supplier text not null default '',
  progress_percentage integer not null default 0 check (progress_percentage between 0 and 100),
  status text not null default 'Purchase Request Created',
  expected_delivery_date date,
  actual_delivery_date date,
  tracking_reference text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id) on delete set null
);
create index if not exists order_progress_project_idx on public.order_progress(project_id, status);
create index if not exists order_progress_status_idx on public.order_progress(status, progress_percentage);
create index if not exists order_progress_expected_idx on public.order_progress(expected_delivery_date);

create table if not exists public.order_progress_updates (
  id bigint generated by default as identity primary key,
  order_progress_id uuid not null references public.order_progress(id) on delete cascade,
  previous_percentage integer not null,
  new_percentage integer not null,
  previous_status text not null,
  new_status text not null,
  previous_expected_delivery_date date,
  new_expected_delivery_date date,
  previous_actual_delivery_date date,
  new_actual_delivery_date date,
  previous_supplier text not null default '',
  new_supplier text not null default '',
  previous_tracking_reference text not null default '',
  new_tracking_reference text not null default '',
  note text not null default '',
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists order_progress_updates_item_idx on public.order_progress_updates(order_progress_id, created_at desc);

create table if not exists public.order_progress_users (
  id bigint generated by default as identity primary key,
  order_progress_id uuid not null references public.order_progress(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  relationship_type text not null,
  created_at timestamptz not null default now(),
  unique(order_progress_id, user_id, relationship_type)
);
create index if not exists order_progress_users_item_idx on public.order_progress_users(order_progress_id, user_id);

create or replace function public.set_order_progress_updated_at()
returns trigger language plpgsql set search_path = '' as $$ begin new.updated_at=now(); return new; end $$;
drop trigger if exists order_progress_set_updated_at on public.order_progress;
create trigger order_progress_set_updated_at before update on public.order_progress for each row execute function public.set_order_progress_updated_at();

alter table public.order_progress enable row level security;
alter table public.order_progress_updates enable row level security;
alter table public.order_progress_users enable row level security;

create policy order_progress_read on public.order_progress for select to authenticated using (app_private.can_project(project_id,'view') or requested_by=(select auth.uid()) or responsible_user_id=(select auth.uid()));
create policy order_progress_write on public.order_progress for all to authenticated using (app_private.can_project(project_id,'edit') or requested_by=(select auth.uid()) or responsible_user_id=(select auth.uid())) with check (app_private.can_project(project_id,'edit') or requested_by=(select auth.uid()) or responsible_user_id=(select auth.uid()));
create policy order_progress_updates_read on public.order_progress_updates for select to authenticated using (exists(select 1 from public.order_progress p where p.id=order_progress_id and (app_private.can_project(p.project_id,'view') or p.requested_by=(select auth.uid()) or p.responsible_user_id=(select auth.uid()))));
create policy order_progress_updates_write on public.order_progress_updates for insert to authenticated with check (exists(select 1 from public.order_progress p where p.id=order_progress_id and (app_private.can_project(p.project_id,'edit') or p.requested_by=(select auth.uid()) or p.responsible_user_id=(select auth.uid()))));
create policy order_progress_users_read on public.order_progress_users for select to authenticated using (exists(select 1 from public.order_progress p where p.id=order_progress_id and (app_private.can_project(p.project_id,'view') or p.requested_by=(select auth.uid()) or p.responsible_user_id=(select auth.uid()))));
create policy order_progress_users_write on public.order_progress_users for all to authenticated using (exists(select 1 from public.order_progress p where p.id=order_progress_id and app_private.can_project(p.project_id,'edit'))) with check (exists(select 1 from public.order_progress p where p.id=order_progress_id and app_private.can_project(p.project_id,'edit')));

commit;
