begin;

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  actor_user_id uuid references public.profiles(id) on delete set null,
  action_type text not null check (action_type in ('SIGN_IN','PAGE_VIEW','INSERT','UPDATE','DELETE')),
  table_name text,
  record_id text,
  page_path text,
  old_data jsonb,
  new_data jsonb,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists audit_logs_occurred_idx on public.audit_logs(occurred_at desc);
create index if not exists audit_logs_actor_idx on public.audit_logs(actor_user_id,occurred_at desc);
create index if not exists audit_logs_action_idx on public.audit_logs(action_type,occurred_at desc);
create index if not exists audit_logs_table_idx on public.audit_logs(table_name,occurred_at desc);

create table if not exists public.audit_old (
  id bigint primary key,
  occurred_at timestamptz not null,
  actor_user_id uuid references public.profiles(id) on delete set null,
  action_type text not null check (action_type in ('SIGN_IN','PAGE_VIEW','INSERT','UPDATE','DELETE')),
  table_name text,
  record_id text,
  page_path text,
  old_data jsonb,
  new_data jsonb,
  metadata jsonb not null default '{}'::jsonb,
  archived_at timestamptz not null default now()
);

create index if not exists audit_old_occurred_idx on public.audit_old(occurred_at desc);
create index if not exists audit_old_actor_idx on public.audit_old(actor_user_id,occurred_at desc);
create index if not exists audit_old_action_idx on public.audit_old(action_type,occurred_at desc);

alter table public.audit_logs enable row level security;
alter table public.audit_old enable row level security;

drop policy if exists audit_logs_admin_read on public.audit_logs;
create policy audit_logs_admin_read on public.audit_logs for select to authenticated
using (app_private.current_role() = 'ADMIN');

drop policy if exists audit_logs_self_event_insert on public.audit_logs;
create policy audit_logs_self_event_insert on public.audit_logs for insert to authenticated
with check (
  actor_user_id = (select auth.uid())
  and action_type in ('SIGN_IN','PAGE_VIEW')
  and table_name is null
  and old_data is null
  and new_data is null
);

grant select,insert on public.audit_logs to authenticated;
grant usage,select on sequence public.audit_logs_id_seq to authenticated;
revoke update,delete on public.audit_logs from authenticated,anon;

drop policy if exists audit_old_admin_read on public.audit_old;
create policy audit_old_admin_read on public.audit_old for select to authenticated
using (app_private.current_role() = 'ADMIN');

grant select on public.audit_old to authenticated;
revoke insert,update,delete on public.audit_old from authenticated,anon;

create or replace function app_private.archive_expired_audit_logs()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  with expired_logs as (
    delete from public.audit_logs
    where occurred_at < now() - interval '1 month'
    returning id,occurred_at,actor_user_id,action_type,table_name,record_id,page_path,old_data,new_data,metadata
  )
  insert into public.audit_old(id,occurred_at,actor_user_id,action_type,table_name,record_id,page_path,old_data,new_data,metadata)
  select id,occurred_at,actor_user_id,action_type,table_name,record_id,page_path,old_data,new_data,metadata
  from expired_logs
  on conflict (id) do nothing;

  return null;
end;
$$;

create or replace function app_private.delete_expired_audit_old()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.audit_old
  where occurred_at < now() - interval '2 months';

  return null;
end;
$$;

revoke all on function app_private.archive_expired_audit_logs() from public,anon,authenticated;
revoke all on function app_private.delete_expired_audit_old() from public,anon,authenticated;

drop trigger if exists archive_expired_audit_logs on public.audit_logs;
create trigger archive_expired_audit_logs
before insert on public.audit_logs
for each statement execute function app_private.archive_expired_audit_logs();

drop trigger if exists delete_expired_audit_old on public.audit_old;
create trigger delete_expired_audit_old
after insert on public.audit_old
for each statement execute function app_private.delete_expired_audit_old();

create or replace function app_private.capture_row_audit()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  old_row jsonb;
  new_row jsonb;
  row_id text;
begin
  if tg_table_schema <> 'public' or tg_table_name in ('audit_logs','audit_old') then
    if tg_op = 'DELETE' then return old; else return new; end if;
  end if;
  if tg_op <> 'INSERT' then old_row := to_jsonb(old); end if;
  if tg_op <> 'DELETE' then new_row := to_jsonb(new); end if;
  row_id := coalesce(new_row->>'id',old_row->>'id',new_row->>'sku',old_row->>'sku',new_row->>'module_key',old_row->>'module_key');
  insert into public.audit_logs(actor_user_id,action_type,table_name,record_id,old_data,new_data,metadata)
  values ((select auth.uid()),tg_op,tg_table_name,row_id,old_row,new_row,jsonb_build_object('schema',tg_table_schema));
  if tg_op = 'DELETE' then return old; else return new; end if;
end;
$$;

revoke all on function app_private.capture_row_audit() from public,anon,authenticated;

do $$
declare table_record record;
begin
  for table_record in
    select tablename from pg_tables
    where schemaname='public' and tablename not in ('audit_logs','audit_old')
  loop
    execute format('drop trigger if exists audit_row_changes on public.%I',table_record.tablename);
    execute format('create trigger audit_row_changes after insert or update or delete on public.%I for each row execute function app_private.capture_row_audit()',table_record.tablename);
  end loop;
end;
$$;

insert into public.app_modules(module_key,title,path,enabled,sort_order)
values ('audit_logs','Audit Log','/audit-logs',true,990)
on conflict(module_key) do update set title=excluded.title,path=excluded.path,enabled=true,sort_order=excluded.sort_order;

commit;
