-- Ibtechar SmartCare v1 — canonical Supabase schema
-- Safe for a new Supabase project. Run once from the SQL Editor or Supabase CLI.
begin;

create extension if not exists pgcrypto;
create schema if not exists app_private;
revoke all on schema app_private from public, anon;
grant usage on schema app_private to authenticated;

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  name text not null unique check (name in ('ADMIN','MANAGER','FINANCE','TECHNICIAN','VIEWER')),
  created_at timestamptz not null default now()
);
insert into public.roles(name) values ('ADMIN'),('MANAGER'),('FINANCE'),('TECHNICIAN'),('VIEWER')
on conflict (name) do nothing;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text not null default '',
  department text not null default '',
  job_title text not null default '',
  phone text not null default '',
  role_id bigint not null references public.roles(id),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists profiles_role_id_idx on public.profiles(role_id);

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  manager text not null default 'Projects Office',
  approved_budget numeric(14,2) not null default 0 check (approved_budget >= 0),
  committed numeric(14,2) not null default 0 check (committed >= 0),
  spent numeric(14,2) not null default 0 check (spent >= 0),
  status text not null default 'Active',
  image_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_project_access (
  user_id uuid not null references public.profiles(id) on delete cascade,
  project_id uuid not null references public.projects(id) on delete cascade,
  can_view boolean not null default true,
  can_create boolean not null default false,
  can_edit boolean not null default false,
  can_approve boolean not null default false,
  primary key(user_id, project_id)
);
create index if not exists user_project_access_project_idx on public.user_project_access(project_id,user_id);

create table if not exists public.budget_branches (
  id bigint generated by default as identity primary key,
  project_id uuid not null references public.projects(id) on delete cascade,
  name text not null,
  approved_amount numeric(14,2) not null default 0 check (approved_amount >= 0),
  committed_amount numeric(14,2) not null default 0 check (committed_amount >= 0),
  spent_amount numeric(14,2) not null default 0 check (spent_amount >= 0),
  unique(project_id,name)
);
create index if not exists budget_branches_project_idx on public.budget_branches(project_id);

create table if not exists public.app_modules (
  module_key text primary key,
  title text not null,
  path text not null,
  enabled boolean not null default true,
  sort_order integer not null default 0
);

create table if not exists public.user_permissions (
  user_id uuid not null references public.profiles(id) on delete cascade,
  module_key text not null references public.app_modules(module_key) on delete cascade,
  can_view boolean not null default false,
  can_create boolean not null default false,
  can_edit boolean not null default false,
  can_delete boolean not null default false,
  can_approve boolean not null default false,
  primary key(user_id,module_key)
);
create index if not exists user_permissions_module_idx on public.user_permissions(module_key,user_id);

create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  name text not null unique,
  project_id uuid references public.projects(id) on delete set null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists locations_project_idx on public.locations(project_id);

create table if not exists public.assets (
  id text primary key,
  project_id uuid not null references public.projects(id) on delete restrict,
  name text not null,
  manufacturer text not null default '',
  model text not null default '',
  serial_number text not null default '',
  category text not null,
  location text not null default '',
  installed_on date,
  warranty_until date,
  status text not null default 'Operational',
  tone text not null default 'healthy',
  health integer not null default 100 check (health between 0 and 100),
  uptime numeric(8,2) not null default 0,
  metric_label text,
  metric text,
  maintenance_label text,
  maintenance text,
  data_source text,
  connectivity text,
  last_seen timestamptz,
  owner text,
  acquisition_cost numeric(14,2) not null default 0 check (acquisition_cost >= 0),
  residual_value numeric(14,2) not null default 0 check (residual_value >= 0),
  useful_life_years integer not null default 5 check (useful_life_years > 0),
  purchase_date date,
  image_path text,
  insured boolean not null default false,
  open_box boolean not null default false,
  damage_percent integer not null default 0 check (damage_percent between 0 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists assets_project_id_idx on public.assets(project_id);
create index if not exists assets_location_idx on public.assets(location);

create table if not exists public.maintenance_tasks (
  id text primary key,
  asset_id text not null references public.assets(id) on delete cascade,
  title text not null,
  cadence text,
  next_due date,
  status text not null default 'Upcoming',
  source text,
  created_at timestamptz not null default now()
);
create index if not exists maintenance_tasks_asset_idx on public.maintenance_tasks(asset_id);
create index if not exists maintenance_tasks_due_idx on public.maintenance_tasks(next_due,status);

create table if not exists public.work_orders (
  id text primary key,
  asset_id text not null references public.assets(id) on delete cascade,
  maintenance_task_id text references public.maintenance_tasks(id) on delete set null,
  title text not null,
  description text,
  status text not null default 'Scheduled',
  priority text not null default 'Normal',
  assignee text,
  due_date date,
  scheduled_start timestamptz,
  started_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists work_orders_asset_idx on public.work_orders(asset_id);
create index if not exists work_orders_task_idx on public.work_orders(maintenance_task_id);
create index if not exists work_orders_due_idx on public.work_orders(due_date,status);

create table if not exists public.service_events (
  id text primary key,
  asset_id text not null references public.assets(id) on delete cascade,
  type text,
  title text not null,
  performed_by text,
  performed_at timestamptz,
  notes text
);
create index if not exists service_events_asset_idx on public.service_events(asset_id);

create table if not exists public.alerts (
  id text primary key,
  asset_id text not null references public.assets(id) on delete cascade,
  severity text not null,
  title text not null,
  message text,
  triggered_at timestamptz,
  resolved boolean not null default false
);
create index if not exists alerts_asset_idx on public.alerts(asset_id,resolved);

create table if not exists public.spare_parts (
  sku text primary key,
  name text not null,
  category text not null,
  on_hand integer not null default 0 check (on_hand >= 0),
  reorder_point integer not null default 0 check (reorder_point >= 0),
  unit_cost numeric(14,2) not null default 0 check (unit_cost >= 0),
  location text,
  linked_assets text
);

create table if not exists public.purchase_requests (
  id text primary key,
  project_id uuid not null references public.projects(id) on delete restrict,
  funding_project_id uuid not null references public.projects(id) on delete restrict,
  request_date date not null default current_date,
  reason text,
  budget_branch text,
  amount numeric(14,2) not null check (amount > 0),
  description text,
  requester text,
  requester_user_id uuid references public.profiles(id) on delete set null,
  status text not null default 'Submitted',
  purchase_order_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists purchase_requests_project_idx on public.purchase_requests(project_id);
create index if not exists purchase_requests_requester_idx on public.purchase_requests(requester_user_id);

create table if not exists public.purchase_orders (
  id text primary key,
  project_id uuid not null references public.projects(id) on delete restrict,
  po_date date not null default current_date,
  supplier text not null,
  equipment text not null,
  equipment_type text not null default 'Asset' check (equipment_type in ('Asset','Consumable')),
  budget_branch text not null default 'Equipment',
  location text,
  quantity integer not null default 1 check (quantity > 0),
  unit_price numeric(14,2) not null default 0 check (unit_price >= 0),
  total numeric(14,2) generated always as (quantity * unit_price) stored,
  status text not null default 'Review',
  asset_created boolean not null default false,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists purchase_orders_project_idx on public.purchase_orders(project_id);
create index if not exists purchase_orders_status_idx on public.purchase_orders(status);
alter table public.purchase_requests drop constraint if exists purchase_requests_purchase_order_id_fkey;
alter table public.purchase_requests add constraint purchase_requests_purchase_order_id_fkey
  foreign key (purchase_order_id) references public.purchase_orders(id) on delete set null;

create table if not exists public.project_activities (
  id text primary key,
  project_id uuid not null references public.projects(id) on delete cascade,
  type text not null,
  title text not null,
  activity_date date,
  quantity integer not null default 1,
  school text,
  status text not null,
  created_at timestamptz not null default now()
);
create index if not exists project_activities_project_idx on public.project_activities(project_id,activity_date);

create table if not exists public.project_expenses (
  id text primary key,
  project_id uuid not null references public.projects(id) on delete cascade,
  budget_branch text not null,
  expense_type text not null,
  description text not null,
  amount numeric(14,2) not null check (amount >= 0),
  incurred_on date not null,
  status text not null default 'Recorded',
  asset_id text references public.assets(id) on delete set null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists project_expenses_project_idx on public.project_expenses(project_id,incurred_on);

create table if not exists public.project_tasks (
  id text primary key,
  project_id uuid not null references public.projects(id) on delete cascade,
  title text not null,
  description text not null,
  priority text not null default 'Normal' check (priority in ('High','Medium','Normal')),
  assignee_user_id uuid not null references public.profiles(id) on delete restrict,
  assigned_by_user_id uuid references public.profiles(id) on delete set null,
  due_date date not null,
  status text not null default 'Pending' check (status in ('Pending','Accepted','Deferred','Completed','Cancelled')),
  defer_reason text,
  response_note text,
  responded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists project_tasks_project_idx on public.project_tasks(project_id);
create index if not exists project_tasks_assignee_idx on public.project_tasks(assignee_user_id,status,due_date);

create table if not exists public.project_task_updates (
  id bigint generated by default as identity primary key,
  task_id text not null references public.project_tasks(id) on delete cascade,
  actor_user_id uuid references public.profiles(id) on delete set null,
  event_type text not null,
  note text,
  created_at timestamptz not null default now()
);
create index if not exists project_task_updates_task_idx on public.project_task_updates(task_id,created_at);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  entity_type text not null,
  entity_id text not null,
  title text not null,
  message text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists notifications_user_idx on public.notifications(user_id,read_at,created_at desc);
create index if not exists notifications_entity_idx on public.notifications(entity_type,entity_id);

create table if not exists public.diagnostic_sessions (
  id bigint generated by default as identity primary key,
  asset_id text references public.assets(id) on delete set null,
  equipment_name text not null,
  model text,
  observed_symptom text not null,
  image_path text,
  result_json jsonb,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists diagnostic_sessions_asset_idx on public.diagnostic_sessions(asset_id,created_at desc);

create table if not exists public.asset_import_batches (
  id bigint generated by default as identity primary key,
  source_file_name text not null,
  total_rows integer not null,
  created_count integer not null default 0,
  updated_count integer not null default 0,
  rejected_count integer not null default 0,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create or replace function app_private.current_role()
returns text language sql stable security definer set search_path = ''
as $$ select r.name from public.profiles p join public.roles r on r.id=p.role_id where p.id=(select auth.uid()) and p.active $$;
revoke all on function app_private.current_role() from public, anon;
grant execute on function app_private.current_role() to authenticated;

create or replace function app_private.is_admin_or_manager()
returns boolean language sql stable security definer set search_path = ''
as $$ select coalesce(app_private.current_role() in ('ADMIN','MANAGER'),false) $$;
revoke all on function app_private.is_admin_or_manager() from public, anon;
grant execute on function app_private.is_admin_or_manager() to authenticated;

create or replace function app_private.can_project(target_project uuid, action_name text default 'view')
returns boolean language sql stable security definer set search_path = ''
as $$
  select app_private.is_admin_or_manager() or exists (
    select 1 from public.user_project_access a where a.user_id=(select auth.uid()) and a.project_id=target_project
    and case action_name when 'create' then a.can_create when 'edit' then a.can_edit when 'approve' then a.can_approve else a.can_view end
  )
$$;
revoke all on function app_private.can_project(uuid,text) from public, anon;
grant execute on function app_private.can_project(uuid,text) to authenticated;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles(id,email,full_name,role_id)
  values(new.id,lower(new.email),coalesce(new.raw_user_meta_data->>'full_name',''),(select id from public.roles where name='VIEWER'))
  on conflict(id) do nothing;
  return new;
end $$;
revoke all on function public.handle_new_user() from public, anon, authenticated;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = '' as $$ begin new.updated_at=now(); return new; end $$;
do $$ declare t text; begin
  foreach t in array array['profiles','projects','assets','work_orders','purchase_requests','purchase_orders','project_tasks'] loop
    execute format('drop trigger if exists %I_set_updated_at on public.%I',t,t);
    execute format('create trigger %I_set_updated_at before update on public.%I for each row execute function public.set_updated_at()',t,t);
  end loop;
end $$;

-- RLS is the authorization boundary. The browser only receives the publishable key.
do $$ declare t text; begin
  foreach t in array array['roles','profiles','projects','user_project_access','budget_branches','app_modules','user_permissions','locations','assets','maintenance_tasks','work_orders','service_events','alerts','spare_parts','purchase_requests','purchase_orders','project_activities','project_expenses','project_tasks','project_task_updates','notifications','diagnostic_sessions','asset_import_batches'] loop
    execute format('alter table public.%I enable row level security',t);
  end loop;
end $$;

create policy profiles_company_read on public.profiles for select to authenticated using (active or id=(select auth.uid()) or app_private.is_admin_or_manager());
create policy profiles_admin_manage on public.profiles for all to authenticated using (app_private.is_admin_or_manager()) with check (app_private.is_admin_or_manager());
create policy roles_read on public.roles for select to authenticated using (true);

create policy projects_read on public.projects for select to authenticated using (app_private.can_project(id,'view'));
create policy projects_manage on public.projects for all to authenticated using (app_private.is_admin_or_manager()) with check (app_private.is_admin_or_manager());
create policy access_self_read on public.user_project_access for select to authenticated using (user_id=(select auth.uid()) or app_private.is_admin_or_manager());
create policy access_admin_manage on public.user_project_access for all to authenticated using (app_private.is_admin_or_manager()) with check (app_private.is_admin_or_manager());
create policy modules_read on public.app_modules for select to authenticated using (enabled or app_private.is_admin_or_manager());
create policy modules_admin_manage on public.app_modules for all to authenticated using (app_private.is_admin_or_manager()) with check (app_private.is_admin_or_manager());
create policy permissions_self_read on public.user_permissions for select to authenticated using (user_id=(select auth.uid()) or app_private.is_admin_or_manager());
create policy permissions_admin_manage on public.user_permissions for all to authenticated using (app_private.is_admin_or_manager()) with check (app_private.is_admin_or_manager());

create policy project_children_read_budget on public.budget_branches for select to authenticated using (app_private.can_project(project_id,'view'));
create policy project_children_write_budget on public.budget_branches for all to authenticated using (app_private.can_project(project_id,'edit')) with check (app_private.can_project(project_id,'edit'));
create policy project_children_read_assets on public.assets for select to authenticated using (app_private.can_project(project_id,'view'));
create policy project_children_write_assets on public.assets for all to authenticated using (app_private.can_project(project_id,'edit') or app_private.can_project(project_id,'create')) with check (app_private.can_project(project_id,'edit') or app_private.can_project(project_id,'create'));
create policy locations_read on public.locations for select to authenticated using (project_id is null or app_private.can_project(project_id,'view'));
create policy locations_write on public.locations for all to authenticated using (app_private.is_admin_or_manager()) with check (app_private.is_admin_or_manager());
create policy spare_parts_read on public.spare_parts for select to authenticated using (true);
create policy spare_parts_write on public.spare_parts for all to authenticated using (app_private.current_role() in ('ADMIN','MANAGER','TECHNICIAN')) with check (app_private.current_role() in ('ADMIN','MANAGER','TECHNICIAN'));

create policy maintenance_read on public.maintenance_tasks for select to authenticated using (exists(select 1 from public.assets a where a.id=asset_id and app_private.can_project(a.project_id,'view')));
create policy maintenance_write on public.maintenance_tasks for all to authenticated using (exists(select 1 from public.assets a where a.id=asset_id and app_private.can_project(a.project_id,'edit'))) with check (exists(select 1 from public.assets a where a.id=asset_id and app_private.can_project(a.project_id,'edit')));
create policy work_orders_read on public.work_orders for select to authenticated using (exists(select 1 from public.assets a where a.id=asset_id and app_private.can_project(a.project_id,'view')));
create policy work_orders_write on public.work_orders for all to authenticated using (exists(select 1 from public.assets a where a.id=asset_id and app_private.can_project(a.project_id,'edit'))) with check (exists(select 1 from public.assets a where a.id=asset_id and app_private.can_project(a.project_id,'edit')));
create policy service_events_read on public.service_events for select to authenticated using (exists(select 1 from public.assets a where a.id=asset_id and app_private.can_project(a.project_id,'view')));
create policy service_events_write on public.service_events for all to authenticated using (exists(select 1 from public.assets a where a.id=asset_id and app_private.can_project(a.project_id,'edit'))) with check (exists(select 1 from public.assets a where a.id=asset_id and app_private.can_project(a.project_id,'edit')));
create policy alerts_read on public.alerts for select to authenticated using (exists(select 1 from public.assets a where a.id=asset_id and app_private.can_project(a.project_id,'view')));
create policy alerts_write on public.alerts for all to authenticated using (exists(select 1 from public.assets a where a.id=asset_id and app_private.can_project(a.project_id,'edit'))) with check (exists(select 1 from public.assets a where a.id=asset_id and app_private.can_project(a.project_id,'edit')));

create policy purchase_requests_read on public.purchase_requests for select to authenticated using (requester_user_id=(select auth.uid()) or app_private.can_project(project_id,'view'));
create policy purchase_requests_create on public.purchase_requests for insert to authenticated with check (requester_user_id=(select auth.uid()) and app_private.can_project(project_id,'view'));
create policy purchase_requests_update on public.purchase_requests for update to authenticated using (requester_user_id=(select auth.uid()) or app_private.can_project(project_id,'approve')) with check (requester_user_id=(select auth.uid()) or app_private.can_project(project_id,'approve'));
create policy purchase_orders_read on public.purchase_orders for select to authenticated using (app_private.can_project(project_id,'view'));
create policy purchase_orders_write on public.purchase_orders for all to authenticated using (app_private.can_project(project_id,'create')) with check (app_private.can_project(project_id,'create'));
create policy activities_read on public.project_activities for select to authenticated using (app_private.can_project(project_id,'view'));
create policy activities_write on public.project_activities for all to authenticated using (app_private.can_project(project_id,'edit')) with check (app_private.can_project(project_id,'edit'));
create policy expenses_read on public.project_expenses for select to authenticated using (app_private.can_project(project_id,'view'));
create policy expenses_write on public.project_expenses for all to authenticated using (app_private.can_project(project_id,'edit')) with check (app_private.can_project(project_id,'edit'));
create policy project_tasks_read on public.project_tasks for select to authenticated using (assignee_user_id=(select auth.uid()) or assigned_by_user_id=(select auth.uid()) or app_private.can_project(project_id,'view'));
create policy project_tasks_create on public.project_tasks for insert to authenticated with check (assigned_by_user_id=(select auth.uid()) and app_private.can_project(project_id,'create'));
create policy project_tasks_update on public.project_tasks for update to authenticated using (assignee_user_id=(select auth.uid()) or assigned_by_user_id=(select auth.uid()) or app_private.can_project(project_id,'edit')) with check (assignee_user_id=(select auth.uid()) or assigned_by_user_id=(select auth.uid()) or app_private.can_project(project_id,'edit'));
create policy task_updates_read on public.project_task_updates for select to authenticated using (exists(select 1 from public.project_tasks t where t.id=task_id));
create policy task_updates_create on public.project_task_updates for insert to authenticated with check (actor_user_id=(select auth.uid()));
create policy notifications_owner on public.notifications for select to authenticated using (user_id=(select auth.uid()));
create policy notifications_owner_update on public.notifications for update to authenticated using (user_id=(select auth.uid())) with check (user_id=(select auth.uid()));
create policy notifications_create on public.notifications for insert to authenticated with check (app_private.current_role() in ('ADMIN','MANAGER','FINANCE','TECHNICIAN'));
create policy diagnostics_read on public.diagnostic_sessions for select to authenticated using (created_by=(select auth.uid()) or asset_id is null or exists(select 1 from public.assets a where a.id=asset_id and app_private.can_project(a.project_id,'view')));
create policy diagnostics_create on public.diagnostic_sessions for insert to authenticated with check (created_by=(select auth.uid()));
create policy import_batches_read on public.asset_import_batches for select to authenticated using (created_by=(select auth.uid()) or app_private.is_admin_or_manager());
create policy import_batches_create on public.asset_import_batches for insert to authenticated with check (created_by=(select auth.uid()));

-- Private Storage buckets. Object names must begin with the authenticated user's UUID.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values
 ('asset-images','asset-images',false,5242880,array['image/jpeg','image/png','image/webp']),
 ('diagnostic-images','diagnostic-images',false,10485760,array['image/jpeg','image/png','image/webp']),
 ('purchase-order-pdfs','purchase-order-pdfs',false,10485760,array['application/pdf']),
 ('reports','reports',false,20971520,array['application/pdf','text/csv','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','text/html']),
 ('manuals','manuals',false,20971520,array['application/pdf'])
on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

create policy storage_owner_read on storage.objects for select to authenticated using (
  bucket_id in ('asset-images','diagnostic-images','purchase-order-pdfs','reports','manuals')
  and (
    owner_id=(select auth.uid())::text
    or exists(select 1 from public.assets a where a.image_path=name and app_private.can_project(a.project_id,'view'))
    or exists(select 1 from public.projects p where p.image_path=name and app_private.can_project(p.id,'view'))
  )
);
create policy storage_owner_insert on storage.objects for insert to authenticated with check (bucket_id in ('asset-images','diagnostic-images','purchase-order-pdfs','reports','manuals') and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy storage_owner_update on storage.objects for update to authenticated using (bucket_id in ('asset-images','diagnostic-images','purchase-order-pdfs','reports','manuals') and (storage.foldername(name))[1]=(select auth.uid())::text) with check (bucket_id in ('asset-images','diagnostic-images','purchase-order-pdfs','reports','manuals') and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy storage_owner_delete on storage.objects for delete to authenticated using (bucket_id in ('asset-images','diagnostic-images','purchase-order-pdfs','reports','manuals') and (storage.foldername(name))[1]=(select auth.uid())::text);

grant usage on schema public to authenticated;
grant select,insert,update,delete on all tables in schema public to authenticated;
grant usage,select on all sequences in schema public to authenticated;

commit;
