-- Asset loan requests: request, stock/purchase fulfillment, issue, and return custody.
begin;

insert into public.app_modules(module_key,title,path,enabled,sort_order)
values ('asset_loans','Asset Loans','/asset-loans',true,25)
on conflict(module_key) do update set title=excluded.title,path=excluded.path,enabled=true,sort_order=excluded.sort_order;

create table if not exists public.asset_loan_requests (
  id text primary key,
  requester_user_id uuid not null references public.profiles(id) on delete restrict,
  project_id uuid not null references public.projects(id) on delete restrict,
  item_name text not null,
  purpose text not null,
  needed_from date not null,
  expected_return_date date not null,
  fulfillment_source text check (fulfillment_source in ('Stock','Purchase')),
  asset_id text references public.assets(id) on delete restrict,
  purchase_request_id text references public.purchase_requests(id) on delete set null,
  status text not null default 'Submitted' check (status in ('Submitted','Awaiting purchase','Ready for delivery','On loan','Returned','Rejected','Cancelled')),
  review_note text not null default '',
  issued_at timestamptz,
  issued_by uuid references public.profiles(id) on delete set null,
  returned_at timestamptz,
  returned_by uuid references public.profiles(id) on delete set null,
  return_condition text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint asset_loan_date_order check (expected_return_date >= needed_from)
);
create index if not exists asset_loan_requester_idx on public.asset_loan_requests(requester_user_id,status);
create index if not exists asset_loan_asset_idx on public.asset_loan_requests(asset_id,status);
create index if not exists asset_loan_project_idx on public.asset_loan_requests(project_id,status);

create table if not exists public.asset_loan_events (
  id bigint generated by default as identity primary key,
  loan_request_id text not null references public.asset_loan_requests(id) on delete cascade,
  actor_user_id uuid references public.profiles(id) on delete set null,
  event_type text not null,
  from_status text,
  to_status text not null,
  note text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists asset_loan_events_request_idx on public.asset_loan_events(loan_request_id,created_at desc);

drop trigger if exists asset_loan_requests_set_updated_at on public.asset_loan_requests;
create trigger asset_loan_requests_set_updated_at before update on public.asset_loan_requests for each row execute function public.set_updated_at();

alter table public.asset_loan_requests enable row level security;
alter table public.asset_loan_events enable row level security;

drop policy if exists asset_loans_read on public.asset_loan_requests;
create policy asset_loans_read on public.asset_loan_requests for select to authenticated
using (requester_user_id=(select auth.uid()) or app_private.current_role() in ('CEO','ADMIN','PROJECT_MANAGER','MANAGER','TECHNICIAN'));
drop policy if exists asset_loans_create on public.asset_loan_requests;
create policy asset_loans_create on public.asset_loan_requests for insert to authenticated
with check (requester_user_id=(select auth.uid()));
drop policy if exists asset_loans_manage on public.asset_loan_requests;
create policy asset_loans_manage on public.asset_loan_requests for update to authenticated
using (app_private.current_role() in ('CEO','ADMIN','PROJECT_MANAGER','MANAGER','TECHNICIAN'))
with check (app_private.current_role() in ('CEO','ADMIN','PROJECT_MANAGER','MANAGER','TECHNICIAN'));
drop policy if exists asset_loan_events_read on public.asset_loan_events;
create policy asset_loan_events_read on public.asset_loan_events for select to authenticated
using (exists(select 1 from public.asset_loan_requests r where r.id=loan_request_id));
drop policy if exists asset_loan_events_create on public.asset_loan_events;
create policy asset_loan_events_create on public.asset_loan_events for insert to authenticated
with check (actor_user_id=(select auth.uid()));

insert into public.user_permissions(user_id,module_key,can_view,can_create,can_edit,can_delete,can_approve)
select p.id,'asset_loans',true,true,
  (r.name in ('CEO','ADMIN','PROJECT_MANAGER','MANAGER','TECHNICIAN')),
  false,
  (r.name in ('CEO','ADMIN','PROJECT_MANAGER','MANAGER'))
from public.profiles p join public.roles r on r.id=p.role_id
on conflict(user_id,module_key) do nothing;

commit;
