"use client";
import {CheckCircle2,Clock3,FileText,Plus,ReceiptText,Send,X} from "lucide-react";
import {useEffect,useMemo,useState} from "react";

type Project={id:string;name:string;status:string;parentProjectName?:string};
type Perms={canInvoiceRequest:boolean;canInvoiceReview:boolean;canInvoiceIssue:boolean;canInvoiceMarkSent:boolean;canInvoiceMarkReceived:boolean;canViewAllFinance:boolean};
type RequestItem={id:string;requestNumber:string;projectId:string;projectName:string;requesterName:string;customerName:string;contractReference:string;milestoneReference:string;milestoneDescription:string;requestedAmount:number;currency:string;expectedInvoiceDate?:string|null;currentStatus:string;workflow?:{id:string;status:string}|null};
type Invoice={id:string;invoiceRequestId?:string|null;projectName:string;customerName:string;invoiceNumber:string;invoiceDate?:string|null;dueDate?:string|null;amount:number;currency:string;status:string;receivedAmount:number;paymentReference?:string};
const money=new Intl.NumberFormat("en-QA",{style:"currency",currency:"QAR"});

export default function FinanceInvoicingPage(){
 const[projects,setProjects]=useState<Project[]>([]),[requests,setRequests]=useState<RequestItem[]>([]),[invoices,setInvoices]=useState<Invoice[]>([]),[perms,setPerms]=useState<Perms|null>(null),[requestOpen,setRequestOpen]=useState(false),[issueOpen,setIssueOpen]=useState<RequestItem|null>(null),[receiptOpen,setReceiptOpen]=useState<Invoice|null>(null),[error,setError]=useState("");
 async function safe(response:Response){const raw=await response.text();if(!raw)return{error:`Empty response (${response.status})`};try{return JSON.parse(raw)}catch{return{error:`Invalid response (${response.status})`}}}
 async function refresh(){const[rr,ir,pr,fr]=await Promise.all([fetch("/api/invoice-requests",{cache:"no-store"}),fetch("/api/customer-invoices",{cache:"no-store"}),fetch("/api/projects?compact=1",{cache:"no-store"}),fetch("/api/finance-permissions",{cache:"no-store"})]);const[r,i,p,f]=await Promise.all([safe(rr),safe(ir),safe(pr),safe(fr)]);if(!rr.ok)throw new Error(r.error||"Unable to load invoice requests");if(!ir.ok)throw new Error(i.error||"Unable to load invoices");setRequests(r.requests||[]);setInvoices(i.invoices||[]);setProjects(p.projects||[]);setPerms(f.permissions||null)}
 useEffect(()=>{refresh().catch(e=>setError(e.message))},[]);
 const outstanding=invoices.filter(i=>["SENT","OUTSTANDING","DUE_SOON","OVERDUE","PARTIALLY_PAID"].includes(i.status)).reduce((s,i)=>s+Math.max(0,i.amount-i.receivedAmount),0);
 const overdue=invoices.filter(i=>i.status==="OVERDUE").length,dueSoon=invoices.filter(i=>i.status==="DUE_SOON").length,paid=invoices.filter(i=>i.status==="PAID").length;

 async function createRequest(fd:FormData){const r=await fetch("/api/invoice-requests",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId:String(fd.get("projectId")),customerName:String(fd.get("customerName")),contractReference:String(fd.get("contractReference")),milestoneReference:String(fd.get("milestoneReference")),milestoneDescription:String(fd.get("milestoneDescription")),requestedAmount:Number(fd.get("requestedAmount")),expectedInvoiceDate:String(fd.get("expectedInvoiceDate"))})}),d=await safe(r);if(!r.ok){setError(d.error||"Unable to create invoice request");return}setRequestOpen(false);await refresh()}
 async function submit(req:RequestItem){const r=await fetch("/api/approvals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({entityType:"CUSTOMER_INVOICE_REQUEST",entityId:req.id})}),d=await safe(r);if(!r.ok){setError(d.error||"Unable to submit request");return}await refresh()}
 async function decide(req:RequestItem,action:"APPROVE"|"REJECT"|"REQUEST_MODIFICATION"){if(!req.workflow?.id)return;const comment=action==="APPROVE"?"Approved":window.prompt(action==="REJECT"?"Reason for rejection":"Required modification")||"";const r=await fetch(`/api/approvals/${req.workflow.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action,comment})}),d=await safe(r);if(!r.ok){setError(d.error||"Unable to review invoice request");return}await refresh()}
 async function issue(fd:FormData){if(!issueOpen)return;const r=await fetch("/api/customer-invoices",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({invoiceRequestId:issueOpen.id,invoiceNumber:String(fd.get("invoiceNumber")),invoiceDate:String(fd.get("invoiceDate")),dueDate:String(fd.get("dueDate"))})}),d=await safe(r);if(!r.ok){setError(d.error||"Unable to issue invoice");return}setIssueOpen(null);await refresh()}
 async function sent(invoice:Invoice){const r=await fetch(`/api/customer-invoices/${invoice.id}/sent`,{method:"POST"}),d=await safe(r);if(!r.ok){setError(d.error||"Unable to mark invoice sent");return}await refresh()}
 async function receipt(fd:FormData){if(!receiptOpen)return;const r=await fetch(`/api/customer-invoices/${receiptOpen.id}/receipt`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({receivedAmount:Number(fd.get("receivedAmount")),receivedDate:String(fd.get("receivedDate")),paymentReference:String(fd.get("paymentReference"))})}),d=await safe(r);if(!r.ok){setError(d.error||"Unable to record receipt");return}setReceiptOpen(null);await refresh()}

 return <main className="dashboard-main section-page"><section className="page-heading"><div><p className="eyebrow">Accounts receivable control</p><h1>Customer Invoicing</h1><p className="page-subtitle">Project delivery → Finance review → invoice → customer → expected payment → received.</p></div>{perms?.canInvoiceRequest&&<button className="button primary" onClick={()=>setRequestOpen(true)}><Plus size={16}/> Request customer invoice</button>}</section>{error&&<p className="form-error">{error}</p>}
 <section className="finance-kpis interactive-finance-kpis"><button className="finance-kpi-button"><span className="finance-icon blue"><ReceiptText/></span><div><small>Outstanding receivables</small><strong>{money.format(outstanding)}</strong></div></button><button className="finance-kpi-button"><span className="finance-icon amber"><Clock3/></span><div><small>Due soon</small><strong>{dueSoon}</strong></div></button><button className="finance-kpi-button"><span className="finance-icon coral"><Clock3/></span><div><small>Overdue</small><strong>{overdue}</strong></div></button><button className="finance-kpi-button"><span className="finance-icon teal"><CheckCircle2/></span><div><small>Paid</small><strong>{paid}</strong></div></button></section>

 <section className="budget-table-card"><div className="panel-heading"><div><h2>Invoice requests</h2><p>Project Manager/requester submits evidence; Finance reviews before issuing the customer invoice.</p></div></div><div className="responsive-table"><table><thead><tr><th>Request</th><th>Project</th><th>Customer</th><th>Milestone / delivery</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{requests.map(req=><tr key={req.id}><td><strong>{req.requestNumber}</strong><small>{req.requesterName}</small></td><td>{req.projectName}</td><td>{req.customerName}</td><td>{req.milestoneDescription}</td><td>{money.format(req.requestedAmount)}</td><td><span className="rag-badge blue">{req.currentStatus.replaceAll("_"," ")}</span></td><td><div className="table-actions">{req.currentStatus==="DRAFT"&&<button className="text-button" onClick={()=>submit(req)}>Submit</button>}{req.currentStatus==="FINANCE_REVIEW"&&perms?.canInvoiceReview&&<><button className="text-button" onClick={()=>decide(req,"APPROVE")}>Approve</button><button className="text-button" onClick={()=>decide(req,"REQUEST_MODIFICATION")}>Modify</button><button className="text-button danger" onClick={()=>decide(req,"REJECT")}>Reject</button></>}{req.currentStatus==="READY_TO_INVOICE"&&perms?.canInvoiceIssue&&<button className="text-button" onClick={()=>setIssueOpen(req)}>Issue invoice</button>}</div></td></tr>)}{!requests.length&&<tr><td colSpan={7} className="empty-row">No invoice requests yet.</td></tr>}</tbody></table></div></section>

 <section className="budget-table-card"><div className="panel-heading"><div><h2>Customer invoices</h2><p>Operational accounts-receivable visibility; due status is calculated from the invoice due date.</p></div></div><div className="responsive-table"><table><thead><tr><th>Invoice</th><th>Project</th><th>Customer</th><th>Invoice date</th><th>Due date</th><th>Amount</th><th>Received</th><th>Status</th><th>Action</th></tr></thead><tbody>{invoices.map(inv=><tr key={inv.id}><td><strong>{inv.invoiceNumber||"—"}</strong></td><td>{inv.projectName}</td><td>{inv.customerName}</td><td>{inv.invoiceDate||"—"}</td><td>{inv.dueDate||"—"}</td><td>{money.format(inv.amount)}</td><td>{money.format(inv.receivedAmount)}</td><td><span className={`rag-badge ${inv.status==="PAID"?"healthy":inv.status==="OVERDUE"?"danger":inv.status==="DUE_SOON"?"warning":"blue"}`}>{inv.status.replaceAll("_"," ")}</span></td><td><div className="table-actions">{inv.status==="ISSUED"&&perms?.canInvoiceMarkSent&&<button className="text-button" onClick={()=>sent(inv)}><Send size={14}/> Sent</button>}{!["PAID","CANCELLED","DRAFT"].includes(inv.status)&&perms?.canInvoiceMarkReceived&&<button className="text-button" onClick={()=>setReceiptOpen(inv)}>Record receipt</button>}</div></td></tr>)}{!invoices.length&&<tr><td colSpan={9} className="empty-row">No issued customer invoices yet.</td></tr>}</tbody></table></div></section>

 {requestOpen&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setRequestOpen(false)}/><section className="modal-card activity-modal"><button className="modal-close inline" onClick={()=>setRequestOpen(false)}><X/></button><h2>Request customer invoice</h2><form action={createRequest}><label>Project / sub-project<select name="projectId" required defaultValue=""><option value="">Choose</option>{projects.filter(p=>p.status!=="Closed").map(p=><option key={p.id} value={p.id}>{p.parentProjectName?`${p.parentProjectName} → `:""}{p.name}</option>)}</select></label><label>Customer<input name="customerName" required/></label><div className="form-grid"><label>Contract reference<input name="contractReference"/></label><label>Milestone reference<input name="milestoneReference"/></label></div><label>Milestone / delivery description<textarea name="milestoneDescription" rows={3} required/></label><div className="form-grid"><label>Requested amount (QAR)<input name="requestedAmount" type="number" min=".01" step=".01" required/></label><label>Expected invoice date<input name="expectedInvoiceDate" type="date"/></label></div><small className="field-note">Signed delivery acceptance/supporting documents will be connected through the Finance Documents layer in the next hardening step.</small><button className="button primary full">Save draft</button></form></section></div>}

 {issueOpen&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setIssueOpen(null)}/><section className="modal-card activity-modal"><h2>Issue customer invoice</h2><p>{issueOpen.customerName} · {money.format(issueOpen.requestedAmount)}</p><form action={issue}><label>Invoice number<input name="invoiceNumber" required/></label><div className="form-grid"><label>Invoice date<input name="invoiceDate" type="date" required/></label><label>Due date<input name="dueDate" type="date" required/></label></div><button className="button primary full"><FileText size={16}/> Issue invoice</button></form></section></div>}

 {receiptOpen&&<div className="modal-layer"><button className="modal-backdrop" onClick={()=>setReceiptOpen(null)}/><section className="modal-card activity-modal"><h2>Record customer payment</h2><p>{receiptOpen.invoiceNumber} · Outstanding {money.format(Math.max(0,receiptOpen.amount-receiptOpen.receivedAmount))}</p><form action={receipt}><div className="form-grid"><label>Received amount<input name="receivedAmount" type="number" min=".01" step=".01" max={Math.max(0,receiptOpen.amount-receiptOpen.receivedAmount)} required/></label><label>Received date<input name="receivedDate" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label></div><label>Payment reference<input name="paymentReference" required/></label><button className="button primary full">Record receipt</button></form></section></div>}</main>
}
